#Requires AutoHotkey v2.0

; imgutil class member functions

    ;########################################################################################################
    ; scalar only, this is just for benchmarking comparison and not meant to be used. v0 is below the psabi 
    ; baseline, there's no equivalent psabi level and get_cpu_psabi_level should never return it.
    ; (theoretically it might, if e.g. SSE has been masked off from CPUID in a VM, so... eh?)
    ;########################################################################################################
    i_get_mcode_map_v0() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 11328 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=core2 -D MARCH_x86_64_v0 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "VlNEi0FASItBCEhjcSBBD6/QRIuQyAAAAEGJ0YnQMdJB9/Ix0kGJw0ONBAhEi0E0QffySGNROExjSTBMY1EYRQHYRA+vwk1jwE0ByEyLSShPjQSBRItJHEUB2UQPr85NY8lN"
    . "AdFMi1EQT40MikE5w31GRItRPEiNHJUAAAAASMHmAkWF0nQxZg8fhAAAAAAAMdJmDx9EAABBiwyQQYkMkUiDwgFMOdJ170GDwwFJAdhJAfFEOdh12Fteww8fRAAASInISGNM"
    . "JCiFyXg0TI1ciATrDg8fRAAASIPABEw52HQfRDpIAkEPk8JEOkABD5PBQYTKdOM6EHLfw2YPH0QAADHAw2ZmLg8fhAAAAAAAZpBBV0FWQVVBVFVXVlNED7ZcJGgPtlwkcA+2"
    . "dCR4hdJJicoPjnwAAACJ0kUx5EyNLJFBD7YKQcZAAwBBD7ZSAUHGQQP/QQ+2QgJBic5FKN6J1UUPQvSJx0Ao3UEPQuxAKPdBD0L8RADZRYgwRRj/QYhoAUQJ+QDaQYh4AkUY"
    . "/0GICUQJ+kAA8EGIUQEY0kmDwgRJg8EECdBJg8AEQYhB/k056nWNMcBbXl9dQVxBXUFeQV/DZmYuDx+EAAAAAAAPHwBBV0FWQVVBVFVXVlNIgew4AQAADxG0JJAAAAAPEbwk"
    . "oAAAAEQPEYQksAAAAEQPEYwkwAAAAEQPEZQk0AAAAEQPEZwk4AAAAEQPEaQk8AAAAEQPEawkAAEAAEQPEbQkEAEAAEQPEbwkIAEAADH/Zg/vwGYPb+hmDzgALeIpAACJ/mYP"
    . "1mwkMEiJz0iJjCSAAQAAifW6AQAAAPAPwReLRywrR0Q50A+M8A8AAEhjRyhIi08gD6/QSGPSSI0MkUhjV0BIKdBIidaLV0xIweACSIlEJGhIAchIiUQkUIXSD4QGCAAASDnI"
    . "cqwPtkddRI12/4msJIwAAABIif1EifMPtldcg+PwRA+2T17zRA9vPR8pAACJXCR4iEQkcESJ8MHoBIhUJHxIweAGRIiMJIgAAABIiUQkSInYTI0chQAAAACJ8CnYTYnfRInz"
    . "iUQkRESJ8EyNJIUEAAAATYnmZg8fRAAASItEJFBED7aMJIgAAABED7ZEJHAPtlQkfEgpyEjB+AKDwAGJRCQg6GT9//9IhcBIicEPhMAGAABEi01URItlUEiLfThFOeEPj9UG"
    . "AABFheRJicNFic0PhMYGAABIi1QkaESJTCRYZkUP79vzRA9+NVwoAABIiUQkYEiJrCSAAQAADx+AAAAAAIX2D44xBgAAg/sPD4ZuBgAATItUJEhIifhMidlmRQ/vyWZFD+/t"
    . "TY0EOvMPbwFmQQ9v12ZBD2/PZkEPb9/zD295EGZBD2/3ZkUPb+dIg8BA8w9vaSBmD9vQZg9x0AhIg8FAZg/bz2YPZ9HzD29J8GYPcdcI80QPb1DQZkEP2+9mD2fHZkEP28dm"
    . "QQ/bz2YPZ+nzD29IwPMPb2DgZkEP2/JmQQ9x0gjzRA9vQPBmD9vZZg9n3mZBD2/3Zg/b9GYPcdEI8w9vefBmRQ/b4GYPcdQIZkEPZ8pmQQ/bz2ZBD3HQCGZBD2f0ZkEPZ+Bm"
    . "QQ/b52YPZ8zzD29h4GYPcdcISTnAZg9x1AhmD2fnZkEP2+dmD2fEZg/ayGYPdMFmD2/mZg9vy2ZBD9v3Zg9x1AhmD2/9ZkEP299mQQ/b72YPcdEIZg9n3mYPZ8xmD2/iZg9x"
    . "1whmQQ/b12YPcdQIZg9n1WYP2tpmD+/tZg9n52YP2sxmD3TTZg904WYP28RmD9vCZg/bBdEmAABmD2/IZg9gzWYPb9FmD2jFZkEPac1mQQ9h1WYP/spmD2/QZkEPacVmQQ9h"
    . "1WYP/sJmD/7IZkQP/skPhWT+//9mQQ9vwWZBD2/5i2wkeGYPc9gIRItUJERLjQw7To0EP2ZBD/7BZg9vyGYPc9kEZg/+wWYPfsBBDxLBZg/++GYP1nwkOEGJ2UEp6UGD+QcP"
    . "hkICAABIweUCZkEPb85mQQ9vxkmNBCtmRQ9vxkgB/fMPfhBmQQ9v3mZBD2/+ZkUPb+7zRA9+YAhBg+H48w9+aBhmD9vKZg9x0ghFKcrzD35wEGZBD9vEZg9nyGZBD3HUCGZB"
    . "D2/GZkEPZ9TzRA9+VQhmRA9v5WYP28VmRA/bxmYP7+1mRA9nwPMPfkUAZg9x1ghmQQ/b+mYPcNII8w9+ZRBmQQ9x1AhmQQ/b1mYPcMkI80QPfk0YZg/b2GYPZ99mQQ9n9GZB"
    . "D2/+ZkQPb+JmD2/QZkUPcMAIZg/b/GZFD9vpZg9x0ghmD2/BZkEPcdIIZg9w2whmQQ9n/USJzWYPcdQIZkEPZ9JmD3DSCGZBD9vWZkEPcdEIZg9w/whmD3D2CGZBD9v2ZkEP"
    . "Z+FmD3DkCGZBD9vmZg9n1GZBD2/gZg9x0AhmRA9n5mYPb/dmD3HUCGZFD3DkCGZBD9v+Zg9w0ghmD2fEZg9v42YPcdYIZg9wwAhmD3HUCGZBD9rUZkEP285mRQ/bxmYPZ+Zm"
    . "QQ9nyGYPcOQIZg9wyQhmD9rgZkEP295mD2ffZg9w2whmD9rZZg90xPMPfjWHJAAASMHlAmYPdMvzD358JDBIAelJAehmQQ901GYP29BmD9vKZg/bzmYPb8FmD2DFZg9gzWYP"
    . "b9hmD3DJTmYPb9FmQQ9h22ZBD2HDZkEPYctmD3DATmZBD2HTZg/+w2YPcMlOZg/+yvMPfmwkOGYP/sFmD/7FZg9vyGYPOAANGCQAAGYP689mD/7BZg9+wEQPtkkCRThIAg+2"
    . "aQFBD5PBQThoAUAPk8VEIc1ED7YJRTgIQQ+TwUUPtslBIelEAchBg/oBD4SZAQAARA+2SQZFOEgGD7ZpBUEPk8FBOGgFQA+TxUQhzUQPtkkERThIBEEPk8FFD7bJQSHpRAHI"
    . "QYP6Ag+EXAEAAEQPtkkJRThICQ+2aQpBD5PBQThoCkAPk8VEIc1ED7ZJCEU4SAhBD5PBRQ+2yUEh6UQByEGD+gMPhB8BAABED7ZJDUU4SA0PtmkOQQ+TwUE4aA5AD5PFRCHN"
    . "RA+2SQxFOEgMQQ+TwUUPtslBIelEAchBg/oED4TiAAAARA+2SRJFOEgSD7ZpEUEPk8FBOGgRQA+TxUQhzUQPtkkQRThIEEEPk8FFD7bJQSHpRAHIQYP6BQ+EpQAAAEQPtkkV"
    . "RThIFQ+2aRZBD5PBQThoFkAPk8VEIc1ED7ZJFEU4SBRBD5PBRQ+2yUEh6UQByEGD+gZ0bEQPtkkaRThIGg+2aRlBD5PBQThoGUAPk8VEIc1ED7ZJGEU4SBhBD5PBRQ+2yUEh"
    . "6UQByEGD+gd0M0QPtlEeRThQHkQPtlEdD7ZJHEEPk8FFOFAdQQ+TwkUh0UE4SBwPk8EPtslEIckByA8fAE0B80wB90EpxUkB00Ep9HQJRTnsD422+f//RYXtRItMJFhIi0wk"
    . "YEiLrCSAAQAAfkFIg8EESDlMJFAPgwj5//9Iie+LrCSMAAAA6Sz4//9Ix0QkOAAAAABBifIx7THASYn4TInZ6XD7//9Fic1Fhe1/v0SJyEiJ70Qp6InFSI1HFEG4AQAAAESJ"
    . "woYQhNJ19zlvEH0HiW8QSIlPCIYQOW9QD4/U9///ie5Ii4QkgAEAAEiLnCSAAQAAi0AshwNIi7wkgAEAAOmu9///Dx9EAABIOUwkUA+CnQcAAEiLRzhEjX7/RItXVESJ+kiJ"
    . "RCRwi0dQQTnCiUQkfEEPnsGFwESJ+EEPlcDB6ASD4vBIweAGiVQkREiJw4nQTI0shQAAAACJ8CnQRYTBiUQkeESJ+EiNFIUEAAAAD4T2BgAASIlcJEhEiftMi3wkaEyJ6PNE"
    . "D289wiAAAESJVCRgSYnViawkiAAAAEiJvCSAAQAADx8ASItsJHBJictIiUwkWGZFD+/bRItkJHxEi3QkYPNED341gyAAAA8fAIX2D44xBgAAg/sPD4aXBgAASIt8JEhMidpI"
    . "ielmRQ/vyWZFD+/tTo0EH/MPbxJmQQ9vz2ZBD2/HZkEPb/fzRA9vUhBmQQ9v32ZBD2/vSIPCQPMPb2LgZg/bymYPcdIISIPBQPNED29C8GZBD9vCZg9nyGZBD2/H8w9vedBm"
    . "D9v0ZkEPcdIIZkEP28BmD2fw8w9vQcBmD3HUCGYP2+9mD3HXCGZBD2fSZkEP29dmD9vYZkEPcdAIZg9n3fNED29h8GYPcdAIZkEPZ+BmQQ/b52YPZ9RmD2fH8w9vYeBmQQ/b"
    . "x2ZFD9vn8w9vefBmD3HUCPMPb2ngSTnQZg9x1whmD2fnZkEP2+dmD2fEZg/awmYPdMJmD2/mZg9v0WZBD9vvZg9x1AhmQQ9n7GYPb/1mQQ/b92YPcdIIZkEP289mQQ/b72YP"
    . "Z85mD2fUZg9v42YPcdcIZg/v9mYPcdQIZkEP299mD2fdZg/a2WYPZ+dmD9riZg90y2YPdNRmD9vCZg/bwWYP2wUIHwAAZg9vyGYPYM5mD2/RZg9oxmZBD2nNZkEPYdVmD/7K"
    . "Zg9v0GZBD2nFZkEPYdVmD/7CZg/+yGZED/7JD4Vj/v//ZkEPb8FmQQ9v+Yt8JERmD3PYCESLVCR4SY0MA0yNRAUAZkEP/sFmD2/IZg9z2QRmD/7BZg9+wkEPEsFmD/74Zg/W"
    . "fCQ4QYnZQSn5QYP5Bw+GRQIAAEjB5wJmQQ9vzmZBD2/GSY0UO2ZFD2/GSAHv8w9+GmZBD2/mZkEPb/5mRQ9v7vNED35iCEGD4fjzD35yEGYP28tmD3HTCEUpyvMPflIYZkEP"
    . "28RmD2fIZkEPcdQIZkEPb8bzRA9+VwhmRA/bxmZBD2fcZg/bwmZED2/iZkQPZ8DzD34H8w9+bxBmQQ9x1AhmQQ/b+mYPcNsI80QPfk8YZg9x1ghmD9vgZkEP295mD2fnZkEP"
    . "Z/RmQQ9v/mZED2/jZg9v2GYP2/1mRQ/b6WZBD3HSCGYPcdMIZg9wyQhmRQ9wwAhmD2/BZg9x1QhmQQ9n2mYPcNsIZkEP295mQQ9x0QhmD3DkCGZBD2f9RInPZkEPZ+lmD3Dt"
    . "CGZBD9vuZg9n3WZBD2/oZg9x0AhmD3D/CGYPcPYIZg9x1QhmQQ/b9mZED2fmZg9v92YPZ8VmD2/sZg9x1ghmRQ9w5AhmD3HVCGYPcMAIZkEP2/5mD3DbCGYPZ+5mQQ/a3GYP"
    . "cO0IZkEP285mD9roZkUP28ZmQQ/b5mZBD2fIZg9n52YPcMkIZg9w5AhmD9rhZg90xWYP7/bzD349vhwAAEjB5wJmD3TM8w9+bCQ4SAH5SQH4ZkEPdNxmD9vYZg/by2YP289m"
    . "D2/ZZg9g3mYPYM5mD3DJTmYPb+FmD2/BZg9vy2ZBD2HjZkEPYdtmQQ9hy2ZBD2HDZg9w205mD3DATmYP/tnzD358JDBmD/7EZg/+w2YP/sVmD2/IZg84AA1LHAAAZg/rz2YP"
    . "/sFmD37CD7Z5AkE4eAIPtnkBQQ+TwUE4eAFAD5PHRCHPRA+2CUU4CEEPk8FFD7bJQSH5RAHKQYP6AQ+ElQEAAA+2eQZBOHgGD7Z5BUEPk8FBOHgFQA+Tx0Qhz0QPtkkERThI"
    . "BEEPk8FFD7bJQSH5RAHKQYP6Ag+EWQEAAA+2eQpBOHgKD7Z5CUEPk8FBOHgJQA+Tx0Qhz0QPtkkIRThICEEPk8FFD7bJQSH5RAHKQYP6Aw+EHQEAAA+2eQ5BOHgOD7Z5DUEP"
    . "k8FBOHgNQA+Tx0Qhz0QPtkkMRThIDEEPk8FFD7bJQSH5RAHKQYP6BA+E4QAAAA+2eRJBOHgSD7Z5EUEPk8FBOHgRQA+Tx0Qhz0QPtkkQRThIEEEPk8FFD7bJQSH5RAHKQYP6"
    . "BQ+EpQAAAA+2eRZBOHgWD7Z5FUEPk8FBOHgVQA+Tx0Qhz0QPtkkURThIFEEPk8FFD7bJQSH5RAHKQYP6BnRtD7Z5GkE4eBoPtnkZQQ+TwUE4eBlAD5PHRCHPRA+2SRhFOEgY"
    . "QQ+TwUUPtslBIflEAcpBg/oHdDUPtnkeQTh4Hg+2eR0PtkkcQQ+TwUE4eB1BD5PCRSHRQThIHA+TwQ+2yUQhyQHKDx+AAAAAAE0B60wB7UEp1k0B+0Ep9HQJRTn0D422+f//"
    . "RYX2SItMJFh+b0iDwQRIOUwkUA+Ddfn//4usJIgAAABIi7wkgAEAAEiLjCSAAAAASIXJD4Rg8P//6V34//8PH4QAAAAAAEiDwQRIOUwkUHJFRYXSf/BFidbrKw8fAEjHRCQ4"
    . "AAAAAEGJ8jH/MdJJiehMidnpSfv//0SLVCRgSIu8JIABAABFKfJIiYwkgAAAAESJ1euaSIuMJIAAAADrkA8QtCSQAAAADxC8JKAAAABEDxCEJLAAAABEDxCMJMAAAABEDxCU"
    . "JNAAAABEDxCcJOAAAABEDxCkJPAAAABEDxCsJAABAABEDxC0JBABAABEDxC8JCABAABIgcQ4AQAAW15fXUFcQV1BXkFfw2YuDx+EAAAAAABXVlOLXCRIRInISGPySInPSGNM"
    . "JEAPtsRFichBicKLRCRYQcHoEA+vxkiYSAHITI0ch4tEJFAPr8ZImEgByEiNDIdMOdlzaYP+AUUPtsBFD7bSRQ+2yXQR62ZmDx9EAABIg8EETDnZc0cPtkEBRCnQmTHQKdAP"
    . "tlECRCnCidbB/h8x8inyOdAPTMIPthFEKcqJ1sH+HzHyKfI50A9MwjnDfb4xwFteX8MPH4QAAAAAALgBAAAAW15fww8fgAAAAABIweYC6xJmLg8fhAAAAAAASAHxTDnZc9gP"
    . "tkECRCnAmTHQKdAPtlEBRCnSidfB/x8x+in6OdAPTMIPthFEKcqJ18H/HzH6Kfo50A9MwjnDfb8xwOuPZmYuDx+EAAAAAABWUw+vVCQ4i1wkQEhj0kiJzkhjTCRQRYnKRInI"
    . "QcHqEA+2xEgB0UyNHI5IY0wkSEgBykiNDJZMOdlzZUUPttJED7bARQ+2yesQDx+AAAAAAEiDwQRMOdlzRw+2QQJEKdCZMdAp0A+2UQFEKcKJ1sH+HzHyKfI50A9Mwg+2EUQp"
    . "yonWwf4fMfIp8jnQD0zCOcN9vjHAW17DZg8fhAAAAAAAuAEAAABbXsMPH4QAAAAAAEFXQVZBVUFUVVdWU0iD7BhEi6QkiAAAAIu8JJAAAABFD6/BSInOi4wkgAAAAEljwEyN"
    . "NIZMOfYPg7gAAABBKdFMY+pBictJweUCTWPBQcHrEEUPttsPtu1ED7bRTIlsJAhJweACMdtNielmDx9EAABIi0QkCEyNPAZMOf5zXEiJ8Q8fgAAAAAAPtkECRCnYmTHQKdAP"
    . "tlEBKepBidVBwf0fRDHqRCnqOdAPTMIPthFEKdJBidVBwf0fRDHqRCnqOdAPTMI5x3wGg8MBRIkhSIPBBEw5+XKxTAHOTAHGTDn2co6J2EiDxBhbXl9dQVxBXUFeQV/DMdvr"
    . "6Q8fgAAAAABTSIPsQESLVCRwTYXAD5TATYXJQQ+Uw0QI2HU8SIXJdDdFD7bSQWnCAAEBAEQJ0A0AAAD/QYnCiGQkKEHB6hCIRCQgRIhUJDDoE+v//0iDxEBbww8fRAAAMcBI"
    . "g8RAW8NBV0FWQVVBVFVXVlNIgexoAQAADxG0JMAAAAAPEbwk0AAAAEQPEYQk4AAAAEQPEYwk8AAAAEQPEZQkAAEAAEQPEZwkEAEAAEQPEaQkIAEAAEQPEawkMAEAAEQPEbQk"
    . "QAEAAEQPEbwkUAEAAESLtCTYAQAARIuUJOABAABNhclIY8JIicsPlMJEicFEi4Qk6AEAAEiDvCTQAQAAAEEPlMFECMoPhUYIAABIhdsPhD0IAABEifJEKdFBD6/Sic+J1olU"
    . "JHhBD77QD6/ySGPWQYnxSGnSH4XrUUHB+R9IwfolRCnKQYnTi5Qk8AEAAIXSD4WFCAAAQYD4ZA+EewgAAIXJD4joBwAARIt8JHhJY85IicJmD+/SRY1m/0gpymYPb/LzRA9v"
    . "PccUAABIjSyFAAAAAEjB4gJEieBmDzgANd8UAABMjRQTZg/WdCRARYX/D5XBRTnfQQ+dwMHoBEUxyUQhwUmJ2ESJ44Pj8EjB4AaITCR8SIlEJEiJ2EyNPIUAAAAARInwiVwk"
    . "VCnYTIn5iUQkWESJ4EiNHIUEAAAAifBJid9IidNIicpNOcJMicEPgigHAACAfCR8AA+ErgcAAImEJJgAAABEieBJidRMifpMiYQkgAAAAEmJ30SJXCRoSImsJIgAAABEiYwk"
    . "kAAAAIm8JJwAAABMiVQkcGYPH0QAAEiLvCTQAQAASYnJSIlMJGBmRQ/v24tsJHhEi2wkaPNED341yRMAAGYPH4QAAAAAAEWF9g+OOAYAAIP4Dw+Gfg8AAEiLXCRITInJSYn4"
    . "ZkUP78lmRQ/v7U6NFAvzD28RZkEPb89mQQ9vx2ZBD2/380QPb1EQZkEPb99mQQ9v70iDwUDzD29h4GYP28pmD3HSCEmDwEDzRA9vQfBmQQ/bwmYPZ8hmQQ9vx/NBD2940GYP"
    . "2/RmQQ9x0ghmQQ/bwGYPZ/BmD3HUCPNBD29AwGYP2+9mD3HXCGZBD2fSZkEP29dmD9vYZkEPcdAIZg9n3fNFD29g8GYPcdAIZkEPZ+BmQQ/b52YPZ9RmD2fH80EPb2DgZkEP"
    . "28dmRQ/b5/NBD2948GYPcdQI80EPb2jgSTnKZg9x1whmD2fnZkEP2+dmD2fEZg/awmYPdMJmD2/mZg9v0WZBD9vvZg9x1AhmQQ9n7GYPb/1mQQ/b92YPcdIIZkEP289mQQ/b"
    . "72YPZ85mD2fUZg9v42YPcdcIZg/v9mYPcdQIZkEP299mD2fdZg/a2WYPZ+dmD9riZg90y2YPdNRmD9vCZg/bwWYP2wVCEgAAZg9vyGYPaMZmD2/QZg9gzmZBD2nFZkEPYdVm"
    . "D/7CZg9v0WZBD2nNZkEPYdVmD/7KZg/+wWZED/7ID4Ve/v//ZkEPb8FmQQ9v+Yt0JFRmD3PYCItcJFhPjRQhTo0cJ2ZBD/7BZg9vyGYPc9kEZg/+wWYPfsFBDxLBZg/++GYP"
    . "1nwkOEGJwEEp8EGD+AcPhkECAABIweYCZkEPb85mQQ9vxkmNDDFmRQ9vxkgB/vMPfhlmQQ9v5mZBD2/+ZkUPb+7zRA9+YQhBg+D48w9+cRBmD9vLZg9x0whEKcPzD35RGGZB"
    . "D9vEZg9nyGZBD3HUCGZBD2/G80QPflYIZkQP28ZmQQ9n3GYP28JmRA9v4mZED2fA8w9+BvMPfm4QZkEPcdQIZkEP2/pmD3DbCPNED35OGGYPcdYIZg/b4GZBD9veZg9n52ZB"
    . "D2f0ZkEPb/5mRA9v42YPb9hmD9v9ZkUP2+lmQQ9x0ghmD3HTCGYPcMkIZkUPcMAIZg9vwWYPcdUIZkEPZ9pmD3DbCGZBD9veZkEPcdEIZg9w5AhmQQ9n/USJxmZBD2fpZg9w"
    . "7QhmQQ/b7mYPZ91mQQ9v6GYPcdAIZg9w/whmD3D2CGYPcdUIZkEP2/ZmRA9n5mYPb/dmD2fFZg9v7GYPcdYIZkUPcOQIZg9x1QhmD3DACGZBD9v+Zg9w2whmD2fuZkEP2txm"
    . "D3DtCGZBD9vOZg/a6GZFD9vGZkEP2+ZmQQ9nyGYPZ+dmD3DJCGYPcOQIZg/a4WYPdMVmD+/28w9+PfoPAABIweYCZg90zPMPfmwkOEkB8kkB82ZBD3TcZg/b2GYP28tmD9vP"
    . "Zg9vwWYPYMZmD2DOZg9v4GYPcMlOZg9v2WZBD2HjZkEPYcNmQQ9hy2YPcMBOZkEPYdtmD/7EZg9wyU5mD/7L8w9+fCRAZg/+wWYP/sVmD2/IZg84AA2LDwAAZg/rz2YP/sFm"
    . "D37BQQ+2cgJBOHMCQQ+2cgFBD5PAQThzAUAPk8ZEIcZFD7YCRTgDQQ+TwEUPtsBBIfBEAcGD+wEPhJwBAABBD7ZyBkE4cwZBD7ZyBUEPk8BBOHMFQA+TxkQhxkUPtkIERThD"
    . "BEEPk8BFD7bAQSHwRAHBg/sCD4RfAQAAQQ+2cgpBOHMKQQ+2cglBD5PAQThzCUAPk8ZEIcZFD7ZCCEU4QwhBD5PARQ+2wEEh8EQBwYP7Aw+EIgEAAEEPtnIOQThzDkEPtnIN"
    . "QQ+TwEE4cw1AD5PGRCHGRQ+2QgxFOEMMQQ+TwEUPtsBBIfBEAcGD+wQPhOUAAABBD7ZyEkE4cxJBD7ZyEUEPk8BBOHMRQA+TxkQhxkUPtkIQRThDEEEPk8BFD7bAQSHwRAHB"
    . "g/sFD4SoAAAAQQ+2chZBOHMWQQ+2chVBD5PAQThzFUAPk8ZEIcZFD7ZCFEU4QxRBD5PARQ+2wEEh8EQBwYP7BnRvQQ+2chpBOHMaQQ+2chlBD5PAQThzGUAPk8ZEIcZFD7ZC"
    . "GEU4QxhBD5PARQ+2wEEh8EQBwYP7B3Q2QQ+2Wh5BOFseQQ+2Wh1BD5PAQThbHQ+Tw0Eh2EEPtlocRTHSQThbHEEPk8JFIcJEAdEPH0AASQHRSAHXQSnNTQH5RCn1dAlEOe0P"
    . "ja75//9Fhe1Ii0wkYA+OZgkAAEiDwQRIOUwkcA+DYfn//0yJ+0SLXCRoSYnXTIniTIuEJIAAAABBicRIi6wkiAAAAESLjCSQAAAAi7wknAAAAIuEJJgAAABMi1QkcEGDwQFJ"
    . "AehJAepBOfkPjrn4//8xyQ8QtCTAAAAASInIDxC8JNAAAABEDxCEJOAAAABEDxCMJPAAAABEDxCUJAABAABEDxCcJBABAABEDxCkJCABAABEDxCsJDABAABEDxC0JEABAABE"
    . "DxC8JFABAABIgcRoAQAAW15fXUFcQV1BXkFfw0iDwQRJOcoPgm////+D+GN/7kWJ3emCCAAASIuMJNABAAAPtlECD7ZJAcHiEMHhCAnKSIuMJNABAAAPtgkJyoHKAAAA/4X/"
    . "QYnUD4g/////SWPOSInCRYngZkUP7/ZIKcpmQQ9v7vNED289IgwAAESJnCSAAAAASI00lQAAAACLVCR4Zg84AC01DAAAZg/WbCRASI0sM0iJtCSQAAAAQY12/0GJ9IXSD5XB"
    . "RDnaD53CSMHgAkUx0iHRSImEJLgAAACJ8In6QYnNwegEifGD4fBIweAGSInvRIisJIgAAABIiUQkWInIRInVTI08hQAAAABEifCJTCRUKciJRCRIifBIid5MiftIjQSFBAAA"
    . "AEiJhCSwAAAASDn3SInxD4IcBwAARInARYnlTIukJLAAAABEiEQkcA+2xImsJJwAAACJRCR8RInAwegQRImEJKAAAACIhCSYAAAAiZQkpAAAAEiJfCRgSIm0JKgAAAAPH0QA"
    . "AEiLRCRgRA+2jCSYAAAARA+2RCR8D7ZUJHBIKchIwfgCg8ABiUQkIOi03///SIXASInBD4RvBgAAgLwkiAAAAABEi7wkgAAAAA+EQQYAAEiLtCTQAQAASYnDSIlEJGhmRQ/v"
    . "24tsJHhEi7wkgAAAAEyLjCSQAAAA80QPfjWgCgAARYX2D47wBQAAQYP9Dw+GeAYAAEiLTCRYSInwTInaZkUP78lmRQ/v7UgB8fMPbwJmQQ9v12ZBD2/PZkEPb9/zD296EGZB"
    . "D2/3ZkUPb+dIg8BA8w9vaiBmD9vQZg9x0AhIg8JAZg/bz2YPZ9HzD29K8GYPcdcI80QPb1DQZkEP2+9mD2fHZkEP28dmQQ/bz2YPZ+nzD29IwPMPb2DgZkEP2/JmQQ9x0gjz"
    . "RA9vQPBmD9vZZg9n3mZBD2/3Zg/b9GYPcdEI8w9vevBmRQ/b4GYPcdQIZkEPZ8pmQQ/bz2ZBD3HQCGZBD2f0ZkEPZ+BmQQ/b52YPZ8zzD29i4GYPcdcISDnBZg9x1AhmD2fn"
    . "ZkEP2+dmD2fEZg/ayGYPdMFmD2/mZg9vy2ZBD9v3Zg9x1AhmD2/9ZkEP299mQQ/b72YPcdEIZg9n3mYPZ8xmD2/iZg9x1whmQQ/b12YPcdQIZg9n1WYP2tpmD+/tZg9n52YP"
    . "2sxmD3TTZg904WYP28RmD9vCZg/bBSgJAABmD2/IZg9gzWYPb9FmD2jFZkEPYc1mQQ9p1WYP/spmD2/QZkEPYcVmQQ9p1WYP/sJmD/7IZkQP/skPhWT+//9mQQ9vwWZBD2/5"
    . "i3wkVGYPc9gIRItUJEhJjQwbTI0EHmZBD/7BZg9vyGYPc9kEZg/+wWYPfsBBDxLBZg/++GYP1nwkOESJ6in6g/oHD4Y/AgAASMHnAmZBD2/OZkEPb8ZJjQQ7ZkUPb8ZIAffz"
    . "D34QZkEPb95mQQ9v/oPi+PNED35gCGZFD2/uQSnS8w9+aBhmD9vKZg9x0gjzD35wEGZBD9vEZg9nyGZBD3HUCGZBD2/GZkEPZ9TzRA9+VwhmRA9v5WYP28VmRA/bxmYP7+1m"
    . "RA9nwPMPfgdmD3HWCGZBD9v6Zg9w0gjzD35nEGZBD3HUCGZBD9vWZg9wyQjzRA9+TxhmD9vYZg9n34nXZkEPZ/RmQQ9v/kjB5wJmRA9v4mYPb9BmD9v8Zg9vwWZFD9vpZg9x"
    . "0ghmRQ9wwAhmD3DbCGZBD2f9Zg9x1AhmD3D/CGYPcPYIZkEP2/ZmD3HQCGZED2fmZg9v92ZBD9vOZg9x1ghmRQ9w5AhIAflJAfhmQQ9x0ghmQQ/b/mZBD3HRCGZBD2fSZg9w"
    . "0ghmQQ/b1mZBD2fhZg9w5AhmQQ/b5mYPZ9RmQQ9v4GYPcNIIZkUP28ZmQQ/a1GYPcdQIZkEPZ8hmD3DJCGYPZ8RmD2/jZg9wwAhmQQ/b3mYPcdQIZg9n32YPcNsIZg/a2WYP"
    . "Z+ZmD3DkCGYP2uBmD3TLZg90xPMPfnwkQPMPfjXPBgAAZkEPdNRmD9vQZg/bymYP285mD2/BZg9gxWYPYM1mD2/YZg9wyU5mD2/RZkEPYdtmQQ9hw2ZBD2HLZg9wwE5mQQ9h"
    . "02YP/sNmD3DJTmYP/srzD35sJDhmD/7BZg/+xWYPb8hmDzgADXQGAABmD+vPZg/+wWYPfsAPtlECQThQAg+2eQEPk8JBOHgBQA+TxyHXD7YRQTgQD5PCD7bSIfoB0EGD+gEP"
    . "hGUBAAAPtlEGQThQBg+2eQUPk8JBOHgFQA+TxyHXD7ZRBEE4UAQPk8IPttIh+gHQQYP6Ag+EMAEAAA+2UQlBOFAJD7Z5Cg+TwkE4eApAD5PHIdcPtlEIQThQCA+Twg+20iH6"
    . "AdBBg/oDD4T7AAAAD7ZRDUE4UA0PtnkOD5PCQTh4DkAPk8ch1w+2UQxBOFAMD5PCD7bSIfoB0EGD+gQPhMYAAAAPtlESQThQEg+2eREPk8JBOHgRQA+TxyHXD7ZREEE4UBAP"
    . "k8IPttIh+gHQQYP6BQ+EkQAAAA+2URVBOFAVD7Z5Fg+TwkE4eBZAD5PHIdcPtlEUQThQFA+Twg+20iH6AdBBg/oGdGAPtlEaQThQGg+2eRkPk8JBOHgZQA+TxyHXD7ZRGEE4"
    . "UBgPk8IPttIh+gHQQYP6B3QvD7ZRHkE4UB4PtnkdD7ZJHA+TwkE4eB1BD5PCRCHSQThIHA+TwQ+2ySHRAcgPHwBNAeNMAeZBKcdNActEKfV0CUQ5/Q+N9vn//0iLTCRoRYX/"
    . "D461AAAASIPBBEg5TCRgD4NZ+f//i6wknAAAAEWJ7ESLhCSgAAAAi5QkpAAAAEiLfCRgSIu0JKgAAABIi4QkuAAAAIPFAUgBxkgBxznVD46/+P//6TP3//8PH0QAAEjHRCQ4"
    . "AAAAAESJ8zH2MclJiftNicrpZfL//0jHRCQ4AAAAAEWJ8jH/McBJifBMidnpZfv//0SLXCRoSIO8JPgBAAAAD4Tm9v//SIuEJPgBAABFKetEiRjp0/b//0iDvCT4AQAAAESL"
    . "nCSAAAAAD4S89v//SIucJPgBAABEidhEKfiJA+mn9v//Dx+AAAAAAFVXVlNIgeyIAAAASIusJNAAAABIi7Qk2AAAAGYPboQk4AAAAESLlCTwAAAASIXtZkgPbs1mSA9u0UiL"
    . "nCQAAQAAZkgPbuYPlMBIhfZmSA9u6kmJy2YPbMwPlMFmD26kJOgAAABmQQ9u2GYPbNUIyGZBD27pZg9ixGYPYt0PhQ4BAABIhdIPhAUBAAAxwLkJAAAAi5Qk4AAAAA+vlCTo"
    . "AAAASI18JCDzSKuLhCT4AAAAZg/WRCRgTI1EJCAPEVQkOGYPbuJmD9ZcJEgPEUwkUIXAD5XAQYD6ZMcHAAAAAA+UwUSIVCRoRQ++0gnID7ZOAUQPr9IPtsAPtlUBZg9uwGYP"
    . "YsRmD9ZEJGxJY8JBwfofSGnAH4XrUcHiCMHhCEjB+CVEKdCJRCR0D7ZFAsHgEAnQD7ZVAAnQD7ZWAmYPbsDB4hAJyg+2DgnKTInZgcoAAAD/Zg9u6mYPYsVIjRUP2P//Zg/W"
    . "RCR4Qf+T0AAAAEiF23QGi0QkMIkDSItEJChIgcSIAAAAW15fXcNmDx9EAAAxwEiBxIgAAABbXl9dw2aQVlNMi1QkOIt0JGBIhckPhLQAAABNhdIPhKsAAACLRCRIRTHbRAnA"
    . "C0QkQAnQD4iKAAAAi0QkWIXAD46JAAAAhfYPjoEAAABFD6/BSGPSTWPJSo0cjQAAAABJY8BIAdBIY1QkQEyNBIGLRCRID69EJFBImEgB0EmNDIJIY0QkUESLVCRYTI0MhQAA"
    . "AAAPH0AAMcBmDx9EAACLFIFBiRSASIPAAUk5wnXwQYPDAUkB2EwByUQ53n/ZQbsBAAAARInYW17DDx9EAABFMdtEidhbXsNmZi4PH4QAAAAAAA8fQABIg+x4TIucJKgAAABI"
    . "hdJIicgPhOgAAABNhdsPhN8AAACLjCS4AAAARTHSRAnJC4wksAAAAEQJwQ+IugAAAESLlCTIAAAARYXSD46xAAAAi4wk0AAAAIXJD46iAAAAZkgPbtKLlCSgAAAAZkgPbsBm"
    . "QQ9u2WYPbMIPEUQkKEiJwWZBD27AZg9iw2YP1kQkOGYPbowkwAAAAEyNRCQgZg9upCTIAAAAx0QkIAAAAABmD26EJLAAAACJVCRAi5Qk0AAAAGYPYsxMiVwkSGYPbqwkuAAA"
    . "AGYPYsVmD2zBDxFEJFCJVCRgSI0VNNT///+Q0AAAAEG6AQAAAESJ0EiDxHjDRTHSRInQSIPEeMMPH0QAADHAw2ZmLg8fhAAAAAAAZpD/AP8A/wD/AP8A/wD/AP8AAQEBAQEB"
    . "AQEBAQEBAQEBAQQFBgeAgICAgICAgICAgICAgICAAAECA4CAgICAgICA"
    mcode_imgutil_column_uniform := 0x0012e0 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x001400 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_replace_color  := 0x0014b0 ; i32 imgutil_replace_color(argb *ptr, i32 width, i32 height, i32 stride, argb cold, argb cnew, i32 tolerance)
    mcode_imgutil_make_sat_masks := 0x0015b0 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x001610 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x002860 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x002a00 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x002ae0 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x002bf0 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_replace_color",     code + mcode_imgutil_replace_color
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    }

    ;############################################################################################################
    ; -march=x86-64 baseline optimized machine code blob
    ;############################################################################################################
    i_get_mcode_map_v1() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 5824 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64 -D MARCH_x86_64_v1 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "QVZVV1ZTSYnLi0lASYtDCEGLazgPr9FBi3MgRIuIyAAAAEGJ0InQMdJB9/Ex0kGJwkKNBAFJY0swQffxQYtTNEQB0g+v1Uhj0kgBykmLSyhMjQSRQYtTHEljSxhEAdIPr9ZI"
    . "Y9JIAcpJi0sQTI0MkUE5wg+N1QAAAA8fgAAAAABBi1s8g/sDD47LAAAAjWv8MdKJ7sHuAo1OAUjB4QRmkPNBD28EEEEPEQQRSIPCEEg50XXs995JjTwJTAHBjVS1AEGLazhB"
    . "i3MghdJ0HkSLMUSJN4P6AXQTRItxBESJdwSD+gJ0BotRCIlXCEhj1UhjzkGDwgFIweICSMHhAkkB0EkByUQ50HRGg/sDD49v////RYtbPA8fAEWF23QiQYsYQYkZQYP7AXQW"
    . "QYtYBEGJWQRBg/sCdAhBi1gIQYlZCEGDwgFJAdBJAclEOdB/ylteX11BXsMPHwCJ2kyJz0yJwelk////ZmYuDx+EAAAAAABBV0FWQVVBVFVXVlNIg+xIDxF0JDAxwGYPdsm6"
    . "AQAAAPAPwRFEi0EsRCtBREE50A+MwAUAAExjaShMi0kgQQ+v1Uhj0kmNFJFEi0lATWPBTSnFRItBTEnB5QJOjTwqRYXAD4QJAwAASTnXcq9FjVH88w9vYWDzD29ZcEWJ0EHB"
    . "6AJFjWABQffYR400gknB5ARBicAPH0QAAEyJ+Egp0EjB+AKDwAGD+AN/FukhAgAAkIPoBEiDwhCD+AMPjhACAADzD28CZg9v7GYPb9NmD97QZg/e6GYPdMVmD3TTZg/bwmYP"
    . "dsFmRA/X0EWF0nTC80UPvNJBwfoCSWPCSI0Ugot5VItxUEiLWTBMi1k4OfcPjw0CAABIidCJ/YX2D4QAAgAAiXwkCEiJVCQQZg8fRAAARTHSMdJBg/kDD46JAQAAiWwkKA8f"
    . "RAAA80IPbwQQ80IPbxQT80MPbywTZg/e0GYP3uhmD3TC80MPbxQTSYPCEGYPdNVmD9vCZg92wWYP1+iJ72bR72aB51VVKf2J72bB7QJmgeczM2aB5TMzAf2J72bB7wQB72aB"
    . "5w8Pif1mwe0IAe9mwe8Cg+cHAfpNOdR1h4tsJChMAeNNAeNMAeBFifJFhdIPhLUAAABmD24oZkEPbjNmD24TZg9vxWYP3tVmD97GZg901WYPdMZmD9vCZg92wWYP1/iD5wEB"
    . "+kGD+gF0cGYPbmgEZkEPbnMEZg9uUwRmD2/FZg/e1WYP3sZmD3TVZg90xmYP28JmD3bBZg/X+IPnAQH6QYP6AnQ1ZkEPblMIZg9uQAhmD25rCGYPb/JmD97oZg/e8GYPdMVm"
    . "D3TWZg/bwmYPdsFmD9f4g+cBAfpJweICTAHTTQHTTAHQKdVMAehEKc50CDn1D46P/v//i3wkCEiLVCQQhe1+eUiDwgRJOdcPg939//9EicDpWP3//w8fRAAARYnK6QH///+F"
    . "wHTnTI0Ugg8fhAAAAAAAZg9uAmYPb+xmD2/TZg/e0GYP3uhmD3TFZg9002YP28JmD3bBZg/XwKgBD4Xu/f//SIPCBEw50nXHRInA6fr8//+J/YXtf4eJ+CnoTI1BFEG6AQAA"
    . "AEWJ0UWGCEWEyXX1OUEQD43CAgAAiUEQSIlRCEWGCDtBUA+Mv/z//4tRLIcR6bX8//9mLg8fhAAAAAAASTnXD4IyAgAASItxMIt5UESLUVRMi2E4SIl0JBhBjXH8QTn6QYn2"
    . "D57Dhf9BD5XDQcHuAkWJ8EGNbgFB99hIweUERo00hkSE2w+EEgIAAESJVCQQTYngiUQkLEiJjCSQAAAADx9EAABIiVQkCEyLVCQYSInQTYnDRItkJBCJ+0yJxmYPH0QAAEUx"
    . "wDHJRInKQYP5Aw+OoAAAAESJZCQokPNCD28EAPNDD28UAvNDD28cA2YP3tBmD97YZg90wvNDD28UA0mDwBBmD3TTZg/bwmYPdsFmRA/X4ESJ4mbR6maB4lVVQSnURIniZkHB"
    . "7AJmgeIzM2ZBgeQzM0EB1ESJ4mbB6gREAeJmgeIPD0GJ1GZBwewIRAHiZsHqAoPiBwHRTDnFD4V3////RItkJChJAepJAetIAehEifKF0g+EvwAAAGYPbhhmQQ9uI2ZBD24S"
    . "Zg9vw2YP3tNmD97EZg9002YPdMRmD9vCZg92wWZED9fAQYPgAUQBwYP6AXR3Zg9uWARmQQ9uYwRmQQ9uUgRmD2/DZg/e02YP3sRmD3TTZg90xGYP28JmD3bBZkQP18BBg+AB"
    . "RAHBg/oCdDlmQQ9uUwhmD25ACGZBD25aCGYPb+JmD97YZg/e4GYPdMNmD3TUZg/bwmYPdsFmRA/XwEGD4AFEAcFIweICSQHSSQHTSAHQQSnMTAHoRCnLdAlBOdwPjnP+//9I"
    . "i1QkCEmJ8EWF5H5JSIPCBEk51w+DOf7//4tEJCxIi4wkkAAAAEiDfCQgAA+EZPr//0iLVCQg6Wr9//8PH4AAAAAASIPCBEk513LaRYXSf/JFidTrDUSLVCQQSIuMJJAAAABE"
    . "idBIiVQkIEQp4Ou2DxB0JDBIg8RIW15fXUFcQV1BXkFfw0WGCDlBUA+PBPr//+lA/f//Dx9AAFdWU4tcJEhEichIY/JIY1QkQEWJyA+2xEHB6BBBicKLRCRYD6/GSJhIAdBM"
    . "jRyBi0QkUA+vxkiYSAHQSI0UgUw52nNsRQ+2wEUPttJFD7bJg/4BdBTraWYPH4QAAAAAAEiDwgRMOdpzRw+2SgFEKdGJyPfYD0jBD7ZKAkQpwYnO994PSc45yA9MwQ+2CkQp"
    . "yYnO994PSc45yA9MwTnDfcAxwFteX8NmLg8fhAAAAAAAuAEAAABbXl/DDx+AAAAAAEjB5gLrEmYuDx+EAAAAAABIAfJMOdpz2A+2SgJEKcGJyPfYD0jBD7ZKAUQp0YnP998P"
    . "Sc85yA9MwQ+2CkQpyYnP998PSc85yA9MwTnDfcExwOuPZmYuDx+EAAAAAABmkFZTD69UJDiLXCRASGPSSInOSGNMJFBEichFicoPtsRBweoQSAHRTI0cjkhjTCRISAHKSI0U"
    . "lkw52nNdRQ+20kQPtsBFD7bJ6xAPH4AAAAAASIPCBEw52nM/D7ZKAkQp0YnI99gPSMEPtkoBRCnBic733g9JzjnID0zBD7YKRCnJic733g9JzjnID0zBOcN9wDHAW17DDx8A"
    . "uAEAAABbXsNBV0FWQVVBVFVXVlNIg+wYi6wkiAAAAIu0JJAAAABFD6/BSInLi4wkgAAAAEljwEyNNINMOfMPg7oAAABMY+pBKdFBicsPtv1JweUCTWPhQcHrEEQPttFMiWwk"
    . "CEUPtttJweQCRTHJTYnvZg8fRAAASItEJAhMjQQDTDnDc1xIidoPH4AAAAAAD7ZCAg+2SgFEKdhBicVB991ED0joKfmJyPfYD0jBD7YKQTnFQQ9NxUQp0UGJzUH33UQPSOlE"
    . "OehBD0zFOcZ8BokqQYPBAUiDwgRMOcJysUwB+0wB40w583KORInISIPEGFteX11BXEFdQV5BX8NFMcnr5w8fRAAARItUJChNhcCJ0A+Uwk2FyUEPlMNECNoPheEAAABIhckP"
    . "hNgAAABFD7bSQWnSAAEBAEQJ0oHKAAAA/2YPbuJmD3DcAIP4A35URI1Y/GYPb8sxwEWJ2kHB6gJBjVIBSMHiBA8fgAAAAADzD28EAWYPb9BmD9zBZg/Y0UEPEQQBQQ8RFABI"
    . "g8AQSDnCddxB99pIAdFJAdFJAdBDjQSThcB0XmYPbgFmD2/IZg/cw2YP2MtmQQ9+AWZBD34Ig/gBdD9mD25BBGYPb8hmD9zDZg/Yy2ZBD35BBGZBD35IBIP4AnQdZg9uSQhm"
    . "D2/BZg/Yw2YP3NlmQQ9+QAhmQQ9+WQgxwMNmZi4PH4QAAAAAAA8fQABBV0FWQVVBVFVXVlNIg+xoDxF0JEAPEXwkUIu0JOAAAACLnCToAAAATYXJRYnCTYnLSInIQQ+UwIuM"
    . "JNgAAABIg7wk0AAAAABBD5TBRQjID4URAwAASIXAD4QIAwAAQYnPRA++w0QPr/5FD6/HTWPIRInHTWnJH4XrUcH/H0nB+SVBKflFic5FidFEi5Qk8AAAAEEp8UWF0g+F/gIA"
    . "AID7ZA+E9QIAAEWFyQ+ItgIAAEhj0kxj0UyJnCTIAAAARYnzSYnUSI08lQAAAABIicJNKdRIiXwkGGYPduRJweQCRYX/D5XDRTn3So00IEyLtCTIAAAAQQ+dwkQh00SNUfxE"
    . "idDB6AKNeAH32EWNLIKJ2EjB5wREicNFMdJBicBIidBIOdYPgiUCAABFhMAPhFoCAABEiXwkDIlcJDhEiVwkCESJVCQgRIhEJChIiXQkEEiJVCQwRIlMJDwPH4AAAAAAi1wk"
    . "DItsJAhIicJNifFMi5Qk0AAAAGYuDx+EAAAAAAAx9kUx20GJyIP5Aw+OowAAAA8fgAAAAADzD28EMvNBD28MMfNBD28UMmYP3shmD97QZg90wfNBD28MMkiDxhBmD3TKZg/b"
    . "wWYPdsRmRA/X+EWJ+GZB0ehmQYHgVVVFKcdFifhmQcHvAmZBgeAzM2ZBgeczM0UBx0WJ+GZBwegERQH4ZkGB4A8PRYnHZkHB7whFAfhmQcHoAkGD4AdFAcNIOf4PhXD///9J"
    . "AflJAfpIAfpFiehFhcAPhMAAAABmD24SZkEPbhpmQQ9uCWYPb8JmD97KZg/ew2YPdMpmD3TDZg/bwWYPdsRmD9fwg+YBQQHzQYP4AXR5Zg9uUgRmQQ9uWgRmQQ9uSQRmD2/C"
    . "Zg/eymYP3sNmD3TKZg90w2YP28FmD3bEZg/X8IPmAUEB80GD+AJ0PGZBD25KCGYPbkIIZkEPblEIZg9v2WYP3tBmD97YZg90wmYPdMtmD9vBZg92xGYP1/CD5gFBAfMPH0QA"
    . "AEnB4AJNAcFNAcJMAcJEKd1MAeIpy3QIOd0PjnH+//+F7Q+OJQQAAEiDwARIOUQkEA+DOv7//0SLfCQMi1wkOESLXCQIRItUJCBED7ZEJChIi3QkEEiLVCQwRItMJDxIi0Qk"
    . "GEGDwgFIAcJIAcZFOcoPjrf9//8xwA8QdCRADxB8JFBIg8RoW15fXUFcQV1BXkFfw0iDwARIOcZywoP7Y3/yRYneRInd6aUDAABFD7ZDAkUPtlMBSIucJNAAAABBweIIQcHg"
    . "EEUJ0EUPthNFCdBED7ZTAWZBD27YRA+2QwJBweIIZg9w2wBBweAQRQnQRA+2E0UJ0EGByAAAAP9mQQ9u4GYPcOQARYXJD4hm////SGPSTGPBZg920kmJ1E0pxEnB5AJFhf9B"
    . "D5XCRTn3So00IEEPncBFIcJJicBEiFQkGEyNFJUAAAAAjVH8idDB6AKNaAH32ESNLIJIweUEMdJMicBmD2/MTDnGD4J9AgAAiVQkOEyJRCQgTIlUJChEiUwkMA8fRAAASIny"
    . "SCnCSMH6AoPCAYP6A38W6WUCAACQg+oESIPAEIP6Aw+OVAIAAPMPbwBmD2/zZg9v6WYP3uhmD97wZg90xmYPdOlmD9vFZg92wmZED9fARYXAdMLzRQ+8wEHB+AJJY9BIjQSQ"
    . "gHwkGABEifcPhMkBAABEiXwkCEiJwk2J2USJ+0SJdCQMTIuUJNAAAABIiXQkEA8fQABFMfYx9kGJyIP5Aw+OpAAAAA8fgAAAAADzQg9vBDLzQw9vLDHzQw9vNDJmD97oZg/e"
    . "8GYPdMXzQw9vLDJJg8YQZg907mYP28VmD3bCZkQP1/hFifhmQdHoZkGB4FVVRSnHRYn4ZkHB7wJmQYHgMzNmQYHnMzNFAcdFifhmQcHoBEUB+GZBgeAPD0WJx2ZBwe8IRQH4"
    . "ZkHB6AJBg+AHRAHGSTnuD4Vv////SQHpSQHqSAHqRYnoRYXAD4THAAAAZg9uMmZBD246ZkEPbilmD2/GZg/e7mYP3sdmD3TuZg90x2YP28VmD3bCZkQP1/BBg+YBRAH2QYP4"
    . "AXR+Zg9ucgRmQQ9uegRmQQ9uaQRmD2/GZg/e7mYP3sdmD3TuZg90x2YP28VmD3bCZkQP1/BBg+YBRAH2QYP4AnQ/ZkEPbmoIZg9uQghmQQ9ucQhmD2/9Zg/e8GYP3vhmD3TG"
    . "Zg9072YP28VmD3bCZkQP1/BBg+YBRAH2Zg8fRAAAScHgAkwBwk0BwU0Bwin3TAHiKct0CDnfD45q/v//RIt8JAhEi3QkDEiLdCQQhf8PjqYAAABIg8AESDnGD4Ou/f//i1Qk"
    . "OEyLRCQgTItUJChEi0wkMIPCAU0B0EwB1kQ5yg+OYf3//+ly/P//hdJ00kyNBJAPH0AAZg9uAGYPb/NmD2/pZg/e6GYP3vBmD3TGZg906WYP28VmD3bCZg/X0IPiAQ+Frf3/"
    . "/0iDwARMOcB1xuuORIt0JAhIg7wk+AAAAAAPhBj8//9Ii5wk+AAAAEEp7kSJM+kF/P//SIO8JPgAAAAAD4T2+///SIucJPgAAABEifIp+okT6eL7//9mLg8fhAAAAAAAQVVB"
    . "VFVXVlNIgeyoAAAASIu0JAABAABMi5wkCAEAAIusJBABAABEi6wkGAEAAEiF9kiLnCQwAQAAD5TATYXbSYnKD5TBSYnUi5QkIAEAAAjID4URAQAATYXkD4QIAQAAMcBIjXwk"
    . "ILkMAAAA80iri4QkKAEAAIlsJGCIVCRohcBEiUQkSEyNRCQgD5XAgPpkD77STIlUJDgPlMFBD6/tTIlkJEAJyESJTCRMTInRD7bASIl0JFAPr9WJRCRsTIlcJFhEiWwkZEhj"
    . "wsH6H4lsJHBIacAfhetRSMH4JSnQD7ZWAYlEJHQPtkYCweIIweAQCdAPthYJ0EEPtlMBZg9uyEEPtkMCweIIZg9wwQDB4BAPEYQkgAAAAAnQQQ+2EwnQSI0VWe3//w0AAAD/"
    . "Zg9u0GYPcMIADxGEJJAAAABB/5LQAAAASIXbdAaLRCQwiQNIi0QkKEiBxKgAAABbXl9dQVxBXcMPH0AAMcBIgcSoAAAAW15fXUFcQV3DZg8fRAAAQVZBVFVXVlNMi1QkWItc"
    . "JHiLtCSAAAAASIXJD4T/AAAATYXSD4T2AAAAi0QkaEUx20QJwAtEJGAJ0A+I0AAAAIXbD47YAAAAhfYPjtAAAABFD6/BSGPSTWPJSGN8JHBKjSyNAAAAAESNS/xIwecCSWPA"
    . "SAHQSGNUJGBIjQyBi0QkaA+vRCRwSJhIAdBJjRSCRInIwegCRI1AAffYScHgBEWNJIEPH0AAMcCD+wMPjn0AAAAPH0QAAPMPbwQCDxEEAUiDwBBMOcB17kqNBAJOjRQBRYXk"
    . "dCRFieFEizBFiTJBg/kBdBVEi3AERYlyBEGD+QJ0B4tACEGJQghBg8MBSAHpSAH6RDnef55BuwEAAABEidhbXl9dQVxBXsMPH0AARTHbRInYW15fXUFcQV7DkEGJ2UmJykiJ"
    . "0OufDx9EAABIg+x4TIucJKgAAABIichIhdIPhNgAAABNhdsPhM8AAACLjCS4AAAARTHSRAnJC4wksAAAAEQJwQ+IpwAAAESLlCTIAAAARYXSD46hAAAAi4wk0AAAAIXJD46S"
    . "AAAASIlUJDCLlCSgAAAASInBZg9ujCTAAAAARIlEJDhMjUQkIGYPbpQkyAAAAIlUJEBmD26EJLAAAACLlCTQAAAAx0QkIAAAAABmD26cJLgAAABmD2LKSIlEJCiJVCRgSI0V"
    . "jun//2YPYsNEiUwkPGYPbMFMiVwkSA8RRCRQ/5DQAAAAQboBAAAARInQSIPEeMMPHwBFMdJEidBIg8R4ww8fRAAAuAEAAADDkJCQkJCQkJCQkA=="
    mcode_imgutil_column_uniform := 0x000790 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x0008b0 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_replace_color  := 0x000950 ; i32 imgutil_replace_color(argb *ptr, i32 width, i32 height, i32 stride, argb cold, argb cnew, i32 tolerance)
    mcode_imgutil_make_sat_masks := 0x000a50 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000b60 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x0012f0 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x001470 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x0015b0 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x0016b0 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                   
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_replace_color",     code + mcode_imgutil_replace_color
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    }

    ;############################################################################################################
    ; -march=x86-64-v2 optimized SSE4 machine code blob
    ;############################################################################################################
    i_get_mcode_map_v2() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 5536 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64-v2 -D MARCH_x86_64_v2 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "QVZVV1ZTSYnLi0lASYtDCEGLazgPr9FBi3MgRIuIyAAAAEGJ0InQMdJB9/Ex0kGJwkKNBAFJY0swQffxQYtTNEQB0g+v1Uhj0kgBykmLSyhMjQSRQYtTHEljSxhEAdIPr9ZI"
    . "Y9JIAcpJi0sQTI0MkUE5wg+N1QAAAA8fgAAAAABBi1s8g/sDD47LAAAAjWv8MdKJ7sHuAo1OAUjB4QRmkPNBD28EEEEPEQQRSIPCEEg50XXs995JjTwJTAHBjVS1AEGLazhB"
    . "i3MghdJ0HkSLMUSJN4P6AXQTRItxBESJdwSD+gJ0BotRCIlXCEhj1UhjzkGDwgFIweICSMHhAkkB0EkByUQ50HRGg/sDD49v////RYtbPA8fAEWF23QiQYsYQYkZQYP7AXQW"
    . "QYtYBEGJWQRBg/sCdAhBi1gIQYlZCEGDwgFJAdBJAclEOdB/ylteX11BXsMPHwCJ2kyJz0yJwelk////ZmYuDx+EAAAAAABBV0FWQVVBVFVXVlNIg+xIDxF0JDAx0mYPdslI"
    . "iciJ0UG4AQAAAPBED8EAi1AsK1BERDnCD4wyBQAATGNgKESLUEBMi0ggRQ+vxElj0kkp1ItQTEnB5AJNY8BPjQSBT400IIXSD4TWAgAATTnGcrFFjUr88w9vYGBBic9NifNE"
    . "icrzD29YcMHqAo1qAffaSMHlBEWNLJFmLg8fhAAAAAAATInaTCnCSMH6AoPCAYP6A38e6fEBAABmDx+EAAAAAACD6gRJg8AQg/oDD47YAQAA80EPbwBmD2/sZg9v02YP3tBm"
    . "D97oZg90xWYPdNNmD9vCZg92wWYP18iFyXTD8w+8ycH5Akhj0U2NBJBEi0hURItwUEiLcDBIi1g4RTnxD4/PAQAATInBRInPRYX2D4TAAQAARIlMJAhMiUQkEA8fADHSRTHA"
    . "QYP6Aw+OUQEAAJDzD28EEfMPbxQW8w9vLBNmD97QZg/e6GYPdMLzD28UE0iDwhBmD3TVZg/bwmYPdsFmRA/XyPNFD7jJQcH5AkUByEg51XW6SAHuSAHrSAHpRInqhdIPhLkA"
    . "AABmD24pZg9uM2YPbhZmD2/FZg/e1WYP3sZmD3TVZg90xmYP28JmD3bBZkQP18hBg+EBRQHIg/oBdHNmD25pBGYPbnMEZg9uVgRmD2/FZg/e1WYP3sZmD3TVZg90xmYP28Jm"
    . "D3bBZkQP18hBg+EBRQHIg/oCdDdmD25TCGYPbkEIZg9ubghmD2/yZg/e6GYP3vBmD3TFZg901mYP28JmD3bBZkQP18hBg+EBRQHISMHiAkgB1kgB00gB0UQpx0wB4UUp1nQJ"
    . "RDn3D47J/v//RItMJAhMi0QkEIX/fnVJg8AETTnDD4MO/v//RIn56Yb9//9mDx9EAABEidLp+v7//4XSdOZJjQyQZkEPbgBmD2/sZg9v02YP3tBmD97oZg90xWYPdNNmD9vC"
    . "Zg92wWYP19CD4gEPhSn+//9Jg8AESTnIdcVEifnpLf3//0SJz4X/f4tEickp+UiNUBRBugEAAABFidFEhgpFhMl19TlIEA+NZQIAAIlIEEyJQAhEhgo7SFAPjPD8//+LUCyH"
    . "EOnm/P//Zg8fRAAATTnGD4LSAQAARIt4UESLSFRBjXL8SIt4MInyRTn5SIl8JBAPnsNIi3g4RYX/QQ+Vw8HqAkiJfCQYjXoB99pIwecERI0slkSE2w+EsgEAAIlMJCxIiYQk"
    . "kAAAAA8fRAAATIlEJAhIi1wkGEyJwkSJ/kyLXCQQRInNDx+EAAAAAAAxwDHJQYP6Aw+OggEAAGaQ8w9vBALzQQ9vFAPzD28cA2YP3tBmD97YZg90wvMPbxQDSIPAEGYPdNNm"
    . "D9vCZg92wWZED9fA80UPuMBBwfgCRAHBSDnHdblJAftIAftIAfpEieiFwA+EvAAAAGYPbhpmD24jZkEPbhNmD2/DZg/e02YP3sRmD3TTZg90xGYP28JmD3bBZkQP18BBg+AB"
    . "RAHBg/gBdHVmD25aBGYPbmMEZkEPblMEZg9vw2YP3tNmD97EZg9002YPdMRmD9vCZg92wWZED9fAQYPgAUQBwYP4AnQ4Zg9uUwhmD25CCGZBD25bCGYPb+JmD97YZg/e4GYP"
    . "dMNmD3TUZg/bwmYPdsFmRA/XwEGD4AFEAcFIweACSQHDSAHDSAHCKc1MAeJEKdZ0CDn1D47H/v//TItEJAiF7X5WSYPABE05xg+Dkf7//4tMJCxIi4QkkAAAAEiDfCQgAA+E"
    . "+fr//0yLRCQg6c79//8PH4AAAAAASYPABE05xnLaRYXJf/JEic3rFQ8fRAAARInQ6cv+//9Ii4QkkAAAAESJyUyJRCQgKenrrw8QdCQwSIPESFteX11BXEFdQV5BX8NEhgo5"
    . "SFAPj5L6///pnf3//2ZmLg8fhAAAAAAAZpBXVlOLXCRIRInISGPySGNUJEBFicgPtsRBwegQQYnCi0QkWA+vxkiYSAHQTI0cgYtEJFAPr8ZImEgB0EiNFIFMOdpzbEUPtsBF"
    . "D7bSRQ+2yYP+AXQU62lmDx+EAAAAAABIg8IETDnac0cPtkoBRCnRicj32A9IwQ+2SgJEKcGJzvfeD0nOOcgPTMEPtgpEKcmJzvfeD0nOOcgPTME5w33AMcBbXl/DZi4PH4QA"
    . "AAAAALgBAAAAW15fww8fgAAAAABIweYC6xJmLg8fhAAAAAAASAHyTDnac9gPtkoCRCnBicj32A9IwQ+2SgFEKdGJz/ffD0nPOcgPTMEPtgpEKcmJz/ffD0nPOcgPTME5w33B"
    . "McDrj2ZmLg8fhAAAAAAAZpBWUw+vVCQ4i1wkQEhj0kiJzkhjTCRQRInIRYnKD7bEQcHqEEgB0UyNHI5IY0wkSEgBykiNFJZMOdpzXUUPttJED7bARQ+2yesQDx+AAAAAAEiD"
    . "wgRMOdpzPw+2SgJEKdGJyPfYD0jBD7ZKAUQpwYnO994PSc45yA9MwQ+2CkQpyYnO994PSc45yA9MwTnDfcAxwFteww8fALgBAAAAW17DQVdBVkFVQVRVV1ZTSIPsGIusJIgA"
    . "AACLtCSQAAAARQ+vwUiJy4uMJIAAAABJY8BMjTSDTDnzD4O6AAAATGPqQSnRQYnLD7b9ScHlAk1j4UHB6xBED7bRTIlsJAhFD7bbScHkAkUxyU2J72YPH0QAAEiLRCQITI0E"
    . "A0w5w3NcSInaDx+AAAAAAA+2QgIPtkoBRCnYQYnFQffdRA9I6Cn5icj32A9IwQ+2CkE5xUEPTcVEKdFBic1B991ED0jpRDnoQQ9MxTnGfAaJKkGDwQFIg8IETDnCcrFMAftM"
    . "AeNMOfNyjkSJyEiDxBhbXl9dQVxBXUFeQV/DRTHJ6+cPH0QAAESLVCQoTYXAidAPlMJNhclBD5TDRAjaD4XhAAAASIXJD4TYAAAARQ+20kFp0gABAQBECdKBygAAAP9mD27i"
    . "Zg9w3ACD+AN+VESNWPxmD2/LMcBFidpBweoCQY1SAUjB4gQPH4AAAAAA8w9vBAFmD2/QZg/cwWYP2NFBDxEEAUEPERQASIPAEEg5wnXcQffaSAHRSQHRSQHQQ40Ek4XAdF5m"
    . "D24BZg9vyGYP3MNmD9jLZkEPfgFmQQ9+CIP4AXQ/Zg9uQQRmD2/IZg/cw2YP2MtmQQ9+QQRmQQ9+SASD+AJ0HWYPbkkIZg9vwWYP2MNmD9zZZkEPfkAIZkEPflkIMcDDZmYu"
    . "Dx+EAAAAAAAPH0AAQVdBVkFVQVRVV1ZTSIPsWA8RdCQwDxF8JECLtCTQAAAAi5wk2AAAAE2FyU2Jz0hjwkSJwkEPlMFEi4QkyAAAAEiDvCTAAAAAAEEPlMJFCNEPhZcCAABI"
    . "hckPhI4CAABFicZED77LKfJED6/2RYnKRQ+v1k1j2kWJ0U1p2x+F61FBwfkfScH7JUUpy0GJ0YuUJOAAAACF0g+FhgIAAID7ZA+EfQIAAEWFyQ+IPgIAAElj0EmJxGYPduRJ"
    . "KdRJweQCRYX2D5XDRTneD53CSMHgAiHTSIlEJAhIiciJ3kqNHCFBjUj8icrB6gKNegH32kSNLJFEicpIwecEQYnxMclEidZBidJIicJIOcMPgsYBAABFhMkPhP0BAABEiXQk"
    . "EIl0JBREiRwkiUwkKESITCQYSIlEJCBEiVQkLA8fgAAAAACLdCQQiywkSInRTYn5TIuUJMAAAAAPHwAxwEUx20GD+AMPjskEAABmDx+EAAAAAADzD28EAfNBD28MAfNBD28U"
    . "AmYP3shmD97QZg90wfNBD28MAkiDwBBmD3TKZg/bwWYPdsRmRA/X8PNFD7j2QcH+AkUB80g5+HW3SQH5SQH6SAH5RInohcAPhMAAAABmD24RZkEPbhpmQQ9uCWYPb8JmD97K"
    . "Zg/ew2YPdMpmD3TDZg/bwWYPdsRmRA/X8EGD5gFFAfOD+AF0eGYPblEEZkEPbloEZkEPbkkEZg9vwmYP3spmD97DZg90ymYPdMNmD9vBZg92xGZED9fwQYPmAUUB84P4AnQ6"
    . "ZkEPbkoIZg9uQQhmQQ9uUQhmD2/ZZg/e0GYP3thmD3TCZg90y2YP28FmD3bEZkQP1/BBg+YBRQHzkEjB4AJJAcFJAcJIAcFEKd1MAeFEKcZ0CDn1D464/v//he0PjvkDAABI"
    . "g8IESDnTD4OL/v//RIt0JBCLdCQURIscJItMJChED7ZMJBhIi0QkIESLVCQsSItUJAiDwQFIAdBIAdNEOdEPjhf+//8x0g8QdCQwDxB8JEBIidBIg8RYW15fXUFcQV1BXkFf"
    . "w0iDwgRIOdNywIP+Y3/yRInd6YIDAABBD7ZXAkUPtlcBSIucJMAAAABBweIIweIQRAnSRQ+2F0QJ0kQPtlMBZg9u2kiLlCTAAAAAQcHiCGYPcNsAD7ZSAsHiEEQJ0kQPthNE"
    . "CdKBygAAAP9mD27iZg9w5ABFhckPiGT///9JY9BIicVEiXQkFGYPdtJIKdVEidtIweUCRYX2QQ+VwkU53kyNLCkPncJBIdJBjVD8RIhUJCxMjRSFAAAAAInQwegCjXgB99hE"
    . "jSSCSMHnBDHAZg9vzEk5zQ+CLgIAAIlEJChED7ZcJCxEicpIiUwkGEyJVCQgSIkMJA8fRAAATIsMJEyJ6EwpyEjB+AKDwAGD+AN/GukpAgAADx9EAACD6ARJg8EQg/gDD44Q"
    . "AgAA80EPbwFmD2/zZg9v6WYP3uhmD97wZg90xmYPdOlmD9vFZg92wmYP18iFyXTD8w+8ycH5AkhjwUmNBIFIiQQkid5FhNsPhGkBAABIiwwkRIt0JBSJXCQQTYn5RIhcJAhM"
    . "i5QkwAAAAJAxwEUx20GD+AMPjpEBAACQ8w9vBAHzQQ9vLAHzQQ9vNAJmD97oZg/e8GYPdMXzQQ9vLAJIg8AQZg907mYP28VmD3bCZg/X2PMPuNvB+wJBAdtIOfh1ukkB+UkB"
    . "+kgB+USJ4IXAD4TDAAAAZg9uMWZBD246ZkEPbilmD2/GZg/e7mYP3sdmD3TuZg90x2YP28VmD3bCZg/X2IPjAUEB24P4AXR9Zg9ucQRmQQ9uegRmQQ9uaQRmD2/GZg/e7mYP"
    . "3sdmD3TuZg90x2YP28VmD3bCZg/X2IPjAUEB24P4AnRBZkEPbmoIZg9uQQhmQQ9ucQhmD2/9Zg/e8GYP3vhmD3TGZg9072YP28VmD3bCZg/X2IPjAUEB22YuDx+EAAAAAABI"
    . "weACSAHBSQHBSQHCRCneSAHpRSnGdAlEOfYPjr/+//+LXCQQRA+2XCQIhfYPjtQAAABIgwQkBEiLBCRJOcUPgwP+//+LRCQoSItMJBhBidFMi1QkIIPAAUwB0U0B1UQ5yA+O"
    . "s/3//+nA/P//Dx8ARInA6Y37//8PH4QAAAAAAESJwOm6/v//TIkMJIXAdLVIizQkSI0MhkiJ8OsMDx8ASIPABEg5yHScZg9uAGYPb/NmD2/pZg/e6GYP3vBmD3TGZg906WYP"
    . "28VmD3bCZkQP18hBg+EBdMhIiQQk6db9//9EixwkSIO8JOgAAAAAD4Q7/P//SIuEJOgAAABBKetEiRjpKPz//0iDvCToAAAAAEiLFCRBidsPhBL8//9Ii4Qk6AAAAEEp80SJ"
    . "GOn/+///QVVBVFVXVlNIgeyoAAAASIu0JAABAABMi5wkCAEAAIusJBABAABEi6wkGAEAAEiF9kiLnCQwAQAAD5TATYXbSYnKD5TBSYnUi5QkIAEAAAjID4URAQAATYXkD4QI"
    . "AQAAMcBIjXwkILkMAAAA80iri4QkKAEAAIlsJGCIVCRohcBEiUQkSEyNRCQgD5XAgPpkD77STIlUJDgPlMFBD6/tTIlkJEAJyESJTCRMTInRD7bASIl0JFAPr9WJRCRsTIlc"
    . "JFhEiWwkZEhjwsH6H4lsJHBIacAfhetRSMH4JSnQD7ZWAYlEJHQPtkYCweIIweAQCdAPthYJ0EEPtlMBZg9uyEEPtkMCweIIZg9wwQDB4BAPEYQkgAAAAAnQQQ+2EwnQSI0V"
    . "ee7//w0AAAD/Zg9u0GYPcMIADxGEJJAAAABB/5LQAAAASIXbdAaLRCQwiQNIi0QkKEiBxKgAAABbXl9dQVxBXcMPH0AAMcBIgcSoAAAAW15fXUFcQV3DZg8fRAAAQVZBVFVX"
    . "VlNMi1QkWItcJHiLtCSAAAAASIXJD4T/AAAATYXSD4T2AAAAi0QkaEUx20QJwAtEJGAJ0A+I0AAAAIXbD47YAAAAhfYPjtAAAABFD6/BSGPSTWPJSGN8JHBKjSyNAAAAAESN"
    . "S/xIwecCSWPASAHQSGNUJGBIjQyBi0QkaA+vRCRwSJhIAdBJjRSCRInIwegCRI1AAffYScHgBEWNJIEPH0AAMcCD+wMPjn0AAAAPH0QAAPMPbwQCDxEEAUiDwBBMOcB17kqN"
    . "BAJOjRQBRYXkdCRFieFEizBFiTJBg/kBdBVEi3AERYlyBEGD+QJ0B4tACEGJQghBg8MBSAHpSAH6RDnef55BuwEAAABEidhbXl9dQVxBXsMPH0AARTHbRInYW15fXUFcQV7D"
    . "kEGJ2UmJykiJ0OufDx9EAABIg+x4TIucJKgAAABIichIhdIPhNgAAABNhdsPhM8AAACLjCS4AAAARTHSRAnJC4wksAAAAEQJwQ+IowAAAESLlCTIAAAARYXSD46hAAAAi4wk"
    . "0AAAAIXJD46SAAAASIlUJDCLlCSgAAAASInBZg9ujCTAAAAARIlEJDhMjUQkIGYPOiKMJMgAAAABiVQkQGYPboQksAAAAIuUJNAAAABIiUQkKGYPOiKEJLgAAAABx0QkIAAA"
    . "AACJVCRgSI0Vrur//2YPbMFEiUwkPEyJXCRIDxFEJFD/kNAAAABBugEAAABEidBIg8R4ww8fgAAAAABFMdJEidBIg8R4ww8fRAAAuAIAAADDkJCQkJCQkJCQkA=="
    mcode_imgutil_column_uniform := 0x000710 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x000830 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_replace_color  := 0x0008d0 ; i32 imgutil_replace_color(argb *ptr, i32 width, i32 height, i32 stride, argb cold, argb cnew, i32 tolerance)
    mcode_imgutil_make_sat_masks := 0x0009d0 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000ae0 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x0011d0 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x001350 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x001490 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x001590 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
    
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_replace_color",     code + mcode_imgutil_replace_color
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    }

    ;############################################################################################################
    ; -march=x86-64-v3 optimized AVX2 machine code blob
    ;############################################################################################################
    i_get_mcode_map_v3() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 6272 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64-v3 -D MARCH_x86_64_v3 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "V1ZTSInLi0lASItDCA+v0USLiMgAAABBidCJ0DHSQffxMdKJx0KNBAFIY0swQffxi1M0AfoPr1M4SGPSSAHKSItLKEyNFJGLUxxIY0sYAfoPr1MgSGPSSAHKSItLEEyNDJE5"
    . "xw+NowAAAGYPH0QAAItTPIP6Bw+OnAAAAESNQvgx0kSJxsHuA41OAUjB4QWQxMF+bwQSxMF+fwQRSIPCIEg50XXr995NjRwKTAHJQY0U8IP6A34VxMF6bwtIg8EQSYPDEIPq"
    . "BMX6f0nwhdJ0H0WLA0SJAYP6AXQURYtDBESJQQSD+gJ0B0GLUwiJUQhIY1M4g8cBTY0UkkhjUyBNjQyROfgPhWb////F+HdbXl/DDx+AAAAAAEyJyU2J0+uSQVdBVkFVQVRV"
    . "V1ZTSIHs6AAAAMX4EbQkkAAAAMX4EbwkoAAAAMV4EYQksAAAAMV4EYwkwAAAAMV4EZQk0AAAAMXldtvF8XbJSI1UJF/HRCQsAAAAAEiJyEiD4uBIiVQkOLkBAAAA8A/BCItQ"
    . "LCtQRDnKD4wmBgAASGN4KItYQEyLQCAPr89IY9NIKdeLUExIwecCSGPJTY0MiEmNNDlIiXQkEIXSD4SdAwAATDnOcrGNS/jF+m9wYMX6b2BwicrF+m+QgAAAAEyLdCQ4weoD"
    . "xXpvgJAAAABEjWoB99pEjTzRScHlBUiJ8UiJxg8fRAAASInIxMF6fxZMKcjEQXp/RhDEwX5vLkjB+ALEwXp/diCDwAHEwXp/ZjCD+AcPjjUCAADEwX5vfiDrFmYPH0QAAIPo"
    . "CEmDwSCD+AcPjhcCAADEwX5vAcVV3sjFRd7Qxa10wMU1dM3FtdvAxf12w8X919CF0nTL8w+80oPiPEkB0USLXlBMi1YwTItGOItuVEWF2w+EaAIAAEyJykGJ7EQ53Q+PWQIA"
    . "AIlsJAhMiUwkEEiJTCQYDx9AADHAMe2D+wcPjpsBAAAPHwDF/m8EAsTBfd4sAMTBfd48AsTBVXQsAEiDwCDF/XTHxf3bxcX9dsPF/dfI8w+4ycH5AgHNSTnFdcdNAepNAehM"
    . "AepEifiD+AMPjjoBAADF+m8CxMF53ihJg8IQg+gExMF53nrwSYPAEEiDwhDEwVF0aPDF+XTHxfnbxcX5dsHF+dfI8w+4ycH5AoXAD4SwAAAAxfluOsRBeW4IxMF5birFwd7t"
    . "xbHex8WxdMDF0XTvxfnbxcX5dsHFedfIQYPhAUQByYP4AXRtxfluegTEQXluSATEwXluagTFwd7txbHex8WxdMDF0XTvxfnbxcX5dsHFedfIQYPhAUQByYP4AnQ0xfluQgjE"
    . "wXluaAjEwXluegjFUd7Ixfne/8X5dMfFsXTtxfnbxcX5dsHFedfIQYPhAUQByUjB4AJJAcJJAcBIAcIB6UgB+kEpzEEp23QJRTncD46Z/v//i2wkCEyLTCQQSItMJBhFheQP"
    . "jtUAAABJg8EETDnJD4O9/f//SInw6Sb9//8PH0QAADHJ6fr+//9mDx+EAAAAAACJ2Omm/v//xMF6b34gxMF6by6D+AN+LcTBem8BxVHeyMV53tfFqXTAxEFRdMnFsdvAxfl2"
    . "wcX519CF0nVNSYPBEIPoBIXAdJtJjRSBDx9AAMTBeW4BxVHeyMVB3tDFqXTAxTF0zcWx28DF+XbBxfnXwKgBD4Wm/f//SYPBBEk50XXOSInw6Yf8//9m8w+8wmbB6AIPt8BN"
    . "jQyB6YD9//9BiexFheQPjyv///9BietIifBFKeNEiVwkLEiNUBRBuAEAAABEicGGCoTJdfeLfCQsOXgQD425AgAAiXgQTIlICIYKO3hQD4wm/P//i1AshxDpHPz//w8fAEw5"
    . "TCQQD4L2AQAARItAUESLaFREjVv4SItwMESJ2kU5xUEPnsJFhcBIiXQkGEiLcDgPlcHB6gONagH32kiJdCQgSMHlBUWNPNNBhMoPhNEBAABIiYQkMAEAAGYPH0QAAEyJTCQI"
    . "TItcJCBMicpEicZMi1QkGEWJ7DHARTHJg/sHD46yAQAAZpDF/m8EAsTBfd4UA8TBfd4kAsTBbXQUA0iDwCDF/XTExf3bwsX9dsPF/dfI8w+4ycH5AkEByUg5xXXGSQHqSQHr"
    . "SAHqRIn4g/gDD45ZAQAAxfpvAsTBed4TSYPCEIPoBMTBed5i8EmDwxBIg8IQxMFpdFPwxfl0xMX528LF+XbBxfnXyPMPuMnB+QKFwA+EsAAAAMX5biLEwXluK8TBeW4Sxdne"
    . "0sXZ3sXF+XTFxel01MX528LF+XbBxXnX8EGD5gFEAfGD+AF0bcX5bmIExMF5bmsExMF5blIExdne0sXZ3sXF+XTFxel01MX528LF+XbBxXnX8EGD5gFEAfGD+AJ0NMX5bkII"
    . "xMF5blMIxMF5bmIIxene6MX53uTF+XTExel01cX528LF+XbBxXnX8EGD5gFEAfFIweACSQHDSQHCSAHCRAHJSAH6QSnMKd50CUE59A+OmP7//0yLTCQIRYXkflVJg8EETDlM"
    . "JBAPg2f+//9Ii4QkMAEAAEiDfCQwAA+EDPr//0yLTCQw6ar9//+QSYPBBEw5TCQQct5Fhe1/8EWJ7OsaDx8AMcnp2/7//5CJ2OmP/v//SIuEJDABAABFKeVMiUwkMESJbCQs"
    . "66vF+HfF+BC0JJAAAADF+BC8JKAAAADFeBCEJLAAAADFeBCMJMAAAADFeBCUJNAAAABIgcToAAAAW15fXUFcQV1BXkFfw4YKi3wkLDl4UA+PcPn//+lF/f//Zi4PH4QAAAAA"
    . "AFdWU4tcJEhEichIY/JIY1QkQEWJyA+2xEHB6BBBicKLRCRYD6/GSJhIAdBMjRyBi0QkUA+vxkiYSAHQSI0UgUw52nNsRQ+2wEUPttJFD7bJg/4BdBTraWYPH4QAAAAAAEiD"
    . "wgRMOdpzRw+2SgFEKdGJyPfYD0jBD7ZKAkQpwYnO994PSc45yA9MwQ+2CkQpyYnO994PSc45yA9MwTnDfcAxwFteX8NmLg8fhAAAAAAAuAEAAABbXl/DDx+AAAAAAEjB5gLr"
    . "EmYuDx+EAAAAAABIAfJMOdpz2A+2SgJEKcGJyPfYD0jBD7ZKAUQp0YnP998PSc85yA9MwQ+2CkQpyYnP998PSc85yA9MwTnDfcExwOuPZmYuDx+EAAAAAABmkFZTD69UJDiL"
    . "XCRASGPSSInOSGNMJFBEichFicoPtsRBweoQSAHRTI0cjkhjTCRISAHKSI0Ulkw52nNdRQ+20kQPtsBFD7bJ6xAPH4AAAAAASIPCBEw52nM/D7ZKAkQp0YnI99gPSMEPtkoB"
    . "RCnBic733g9JzjnID0zBD7YKRCnJic733g9JzjnID0zBOcN9wDHAW17DDx8AuAEAAABbXsNBV0FWQVVBVFVXVlNIg+wYi6wkiAAAAIu0JJAAAABFD6/BSInLi4wkgAAAAElj"
    . "wEyNNINMOfMPg7oAAABMY+pBKdFBicsPtv1JweUCTWPhQcHrEEQPttFMiWwkCEUPtttJweQCRTHJTYnvZg8fRAAASItEJAhMjQQDTDnDc1xIidoPH4AAAAAAD7ZCAg+2SgFE"
    . "KdhBicVB991ED0joKfmJyPfYD0jBD7YKQTnFQQ9NxUQp0UGJzUH33UQPSOlEOehBD0zFOcZ8BokqQYPBAUiDwgRMOcJysUwB+0wB40w583KORInISIPEGFteX11BXEFdQV5B"
    . "X8NFMcnr5w8fRAAARItUJChNhcCJ0A+Uwk2FyUEPlMNECNoPhQYBAABIhckPhP0AAABFD7bSQWnSAAEBAEQJ0oHKAAAA/8X5btLE4n1Y0oP4B35SRI1Y+MX9b8oxwEWJ2kHB"
    . "6gNBjVIBSMHiBQ8fgAAAAADF/m8cAcXl2MHEwX5/BADF9dzDxMF+fwQBSIPAIEg5wnXeQffaSAHRSQHRSQHQQ40E08X5b8KD+AN+J8X6byFJg8EQSIPBEEmDwBCD6ATF2djK"
    . "xMF6f0jwxenczMTBen9J8IXAdGLF+W4JxfHY0MX53MnEwXl+EMTBeX4Jg/gBdEfF+W5JBMXx2NDF+dzJxMF5flAExMF5fkkEg/gCdCnF+W5RCMXp2MjF+dzCxMF5fkgIxMF5"
    . "fkEIxfh3McDDZi4PH4QAAAAAAMX4dzHAw2YuDx+EAAAAAABBV0FWQVVBVFVXVlNIgezIAAAAxfgRdCRAxfgRfCRQxXgRRCRgxXgRTCRwxXgRlCSAAAAAxXgRnCSQAAAAxXgR"
    . "pCSgAAAAxXgRrCSwAAAAi5wkQAEAAESLnCRIAQAATImMJCgBAABIichIg7wkKAEAAABIY8pBD5TCRIuMJDgBAABEicJIg7wkMAEAAABAD5TGQQjyD4XWAgAASIXAD4TNAgAA"
    . "RYnIRQ++0ynaRA+vw4ucJFABAABFD6/QTWPiRInWTWnkH4XrUcH+H0nB/CVBKfSF2w+FEgMAAEGA+2QPhAgDAACF0g+IhAIAAE1j2UmJzkSJVCQ4xeV2200p3sXpdtJJweYC"
    . "RYXAD5XDRTngSo0sMEEPncNEIdtFjVn4QYndSI0cjQAAAABEidnB6QNFiepFicVMi4QkMAEAAI1xAffZRY08y4nRSMHmBUiJ2kUx24nLSInBSDnFD4L6AQAARYTSD4RlAgAA"
    . "RIhUJBhEiWwkDESJZCQIRIlcJCBIiUQkKEiJVCQwSIlsJBCJXCQ8i2wkDIt8JAhIicpMicNMi5wkKAEAAGYuDx+EAAAAAAAxwEUx5EGD+QcPjpEFAACQxf5vBALF/d4MA8TB"
    . "fd4kA8X1dAwDSIPAIMX9dMTF/dvBxf12w8V919DzRQ+40kHB+gJFAdRIOcZ1xkkB80gB80gB8kSJ+IP4Aw+OMQUAAMX6bwLF+d4Lg+gESYPDEMTBed5j8EiDwxBIg8IQxfF0"
    . "S/DF+XTExfnbwcX5dsLFedfQ80UPuNJBwfoChcAPhLMAAADF+W4ixfluK8TBeW4LxdneycXZ3sXF+XTFxfF0zMX528HF+XbCxXnX6EGD5QFFAeqD+AF0ccX5bmIExfluawTE"
    . "wXluSwTF2d7JxdnexcX5dMXF8XTMxfnbwcXpdsDFedfoQYPlAUUB6oP4AnQ5xfluQgjF+W5LCMTBeW5jCMXx3ujF+d7kxfl0xMXxdM3F+dvBxel2wMV51+hBg+UBRQHqZg8f"
    . "RAAASMHgAkkBw0gBw0gBwkUB4kwB8kQp10QpzXQIOe8PjpX+//+F/w+O4AQAAEiDwQRIOUwkEA+DXv7//0QPtlQkGESLbCQMRItkJAhEi1wkIEiLRCQoSItUJDBIi2wkEItc"
    . "JDxBg8MBSAHQSAHVQTnbD47n/f//xfh3McnF+BB0JEDF+BB8JFBIicjFeBBEJGDFeBBMJHDFeBCUJIAAAADFeBCcJJAAAADFeBCkJKAAAADFeBCsJLAAAABIgcTIAAAAW15f"
    . "XUFcQV1BXkFfw0iDwQRIOc1yjIN8JDhjf/BIg7wkWAEAAABEiecPhTAEAADF+HfrhkiLtCQoAQAARA+2VgJED7ZeAUHB4hBBweMIRQnaRA+2HkiLtCQwAQAARQnaRA+2XgHE"
    . "QXlu0kQPtlYCQcHjCMRCfVjSQcHiEEUJ2kQPth5FCdpBgcoAAAD/xEF5bsrEQn1YyYXSD4gW////TWPRxXl/1sV5f8xJic3EQXlvwsXpdtLF5XbbTSnVScHlAkWFwEEPlcNF"
    . "OeBKjSwoQQ+dwkWJ30WNWfhFIddMjRSNAAAAAESJ2cHpA415AffZRY00y0jB5wVFMdvF+W/8xX1/1cV9f8lIicFIOcUPglgCAABEiVwkOEiJRCQYTIlUJCCJVCQoZpBIiehI"
    . "KchIwfgCg8ABg/gHfx7pgQIAAGYPH4QAAAAAAIPoCEiDwSCD+AcPjmgCAADF/m8BxXXe2MVV3uDFnXTAxSV02cWl28DF/XbDxf3X0IXSdMzzD7zSg+I8SAHRRInmRYT/D4Sx"
    . "AQAARIlEJAhIicpEicNMi5wkMAEAAESJZCQMTIuUJCgBAABEiHwkEJAxwEUx/0GD+QcPjvEBAACQxf5vBALEQX3eHAPEQX3eJALEQSV0HANIg8AgxZ10wMWl28DF/XbDxX3X"
    . "wPNFD7jAQcH4AkUBx0g5+HXESQH6SQH7SAH6RInwg/gDD46PAQAAxfpvAsRBed4bg+gESYPCEMRBed5i8EmDwxBIg8IQxEEhdFvwxZl0wMWh28DF+XbCxXnXwPNFD7jAQcH4"
    . "AoXAD4S/AAAAxXluIsRBeW4rxEF5bhrEQRne28TBGd7FxZF0wMRBIXTcxaHbwMX5dsLFedfgQYPkAUUB4IP4AXR5xXluYgTEQXluawTEQXluWgTEQRne28TBGd7FxZF0wMRB"
    . "IXTcxaHbwMXpdsDFedfgQYPkAUUB4IP4AnQ9xfluQgjEQXluWwjEQXluYgjFId7oxEF53uTFmXTAxEEhdN3FodvAxel2wMV51+BBg+QBRQHgDx+AAAAAAEjB4AJJAcJJAcNI"
    . "AcJFAfhMAepEKcZEKct0CDneD46F/v//RItEJAhEi2QkDEQPtnwkEIX2D44qAQAASIPBBEg5zQ+D0P3//0SLXCQ4SItEJBhMi1QkIItUJChBg8MBTAHQTAHVQTnTD459/f//"
    . "xfh36TL8//9mkEUx0ukC+///Dx+EAAAAAABEicjprvr//w8fhAAAAAAARTHA6ab+//8PH4QAAAAAAESJyOlQ/v//g/gDfizF+m8BxVne2MV53ubFmXTAxEFZdNvFodvAxfl2"
    . "wsX519CF0nVMSIPBEIPoBIXAD4Rf////SI0UgQ8fAMX5bgHFQd7YxTne4MWZdMDFIXTfxaHbwMX5dsLF+dfAqAEPhV79//9Ig8EESDnRdc/pIv///2bzD7zCZsHoAg+3wEiN"
    . "DIHpO/3//0iDvCRYAQAAAESLZCQID4TQ+///SIuEJFgBAABBKfxEiSDF+HfpRfv//0iDvCRYAQAAAA+Eq/v//0iLhCRYAQAAQSn0RIkgxfh36SD7//9mZi4PH4QAAAAAAA8f"
    . "AEFWQVVBVFVXVlNIgezQAAAASIusJDABAABMi5wkOAEAAESLpCRAAQAARIu0JEgBAABIi7QkYAEAAEiNXCQ/SYnKSYnVi5QkUAEAAEiD4+BIhe0PlMBNhdsPlMEIyA+FBQEA"
    . "AE2F7Q+E/AAAADHAuQwAAABIid/zSKuLhCRYAQAARIljQIhTSIXATIlTGA+VwID6ZA++0kSJQygPlMFFD6/mRIlLLEmJ2AnITIlbOEyJ0Q+2wEyJayBBD6/UiUNMSIlrMESJ"
    . "c0RIY8LB+h9EiWNQSGnAH4XrUUjB+CUp0A+2VQGJQ1QPtkUCweIIweAQCdAPtlUACdBBD7ZTAcX5bsBBD7ZDAsHiCMTifVjAweAQxf5/Q2AJ0EEPthMJ0EiNFXzr//8NAAAA"
    . "/8X5bsDE4n1YwMX+f4OAAAAAxfh3Qf+S0AAAAEiF9nQFi0MQiQZIi0MISIHE0AAAAFteX11BXEFdQV7DDx9AADHA6+YPH0AAQVZBVFVXVlNMi1QkWItcJHiLtCSAAAAASIXJ"
    . "D4QnAQAATYXSD4QeAQAAi0QkaEUx20QJwAtEJGAJ0A+I+QAAAIXbD44AAQAAhfYPjvgAAABFD6/BSGPSTWPJSGN8JHBKjSyNAAAAAESNS/hIwecCSWPASAHQSGNUJGBIjQyB"
    . "i0QkaA+vRCRwSJhIAdBJjRSCRInIwegDRI1AAffYRY0kwUnB4AVFMclmDx+EAAAAAAAxwIP7Bw+OpQAAAA8fRAAAxf5vBALF/n8EAUiDwCBJOcB17U6NFAJKjQQBRYnjQYP8"
    . "A34WxMF6bwpIg8AQSYPCEEGD6wTF+n9I8EWF23QiRYsyRIkwQYP7AXQWRYtyBESJcARBg/sCdAhFi1IIRIlQCEGDwQFIAelIAfpEOc5/gEG7AQAAAMX4d0SJ2FteX11BXEFe"
    . "ww8fAEUx20SJ2FteX11BXEFew2YPH4QAAAAAAEGJ20iJyEmJ0oP7Aw+Pcv///+uLZmYuDx+EAAAAAACQSIPseEyLnCSoAAAASInISIXSD4TYAAAATYXbD4TPAAAAi4wkuAAA"
    . "AEUx0kQJyQuMJLAAAABECcEPiKQAAABEi5QkyAAAAEWF0g+OoQAAAIuMJNAAAACFyQ+OkgAAAEiJVCQwi5QkoAAAAEiJwcX5bpQkwAAAAESJRCQ4TI1EJCDE42kijCTIAAAA"
    . "AYlUJEDF+W6cJLAAAACLlCTQAAAASIlEJCjE42EihCS4AAAAAcdEJCAAAAAAiVQkYEiNFc7n///F+WzBRIlMJDxMiVwkSMX6f0QkUP+Q0AAAAEG6AQAAAESJ0EiDxHjDZg8f"
    . "RAAARTHSRInQSIPEeMMPH0QAALgDAAAAw5CQkJCQkJCQkJA="
    mcode_imgutil_column_uniform := 0x000820 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x000940 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_replace_color  := 0x0009e0 ; i32 imgutil_replace_color(argb *ptr, i32 width, i32 height, i32 stride, argb cold, argb cnew, i32 tolerance)
    mcode_imgutil_make_sat_masks := 0x000ae0 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000c20 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x001480 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x0015f0 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x001770 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x001870 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform  
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_replace_color",     code + mcode_imgutil_replace_color
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    } 

    ;############################################################################################################
    ; -march=x86-64-v4 optimized AVX512 machine code blob
    ;############################################################################################################
    i_get_mcode_map_v4() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 5568 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64-v4 -D MARCH_x86_64_v4 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "VVdWU0SLQUBIi0EIRIuQyAAAAEEPr9BBidGJ0DHSQffyMdKJw0ONBAhMY0EwQffyi1E0AdoPr1E4SGPSTAHCTItBKE2NDJCLURxMY0EYAdoPr1EgSGPSTAHCTItBEE2NFJA5"
    . "ww+NgwAAAL4BAAAAkItRPIP6Dw+OnwAAAESNWvAx0kSJ38HvBESNRwFJweAGYtH+SG8MEWLR/kh/DBJIg8JASTnQdenB5wREidpLjSwBTQHQKfqF0nQ+xOJp99aNev+DwwHF"
    . "+JLPYvF+yW9FAGLRfkl/AEhjUThNjQyRSGNRIE2NFJI5w3WGxfh3W15fXcNmDx9EAABIY1E4g8MBTY0MkUhjUSBNjRSSOdh024tRPIP6Dw+PYf///02J0EyJzeuTZmYuDx+E"
    . "AAAAAABmkEFXQVZBVUFUVVdWU0iD7EhFMcli831IJcD/Qb8BAAAASYnNuAEAAADwQQ/BRQBBi1VMQStVZDnCD4wcBgAAQYt9SEmLVUBJY01gD6/HiXwkPEiYTI0cgkhjx0iJ"
    . "ykgpyEGLTWxJjQSDSIlEJBCFyQ+EdQMAAEw52HKpRI1i8CnXSIlcJChi0f5Ib20CRIngRIlMJDBIY+9i0f5Ib2UDwegEQYPkD0jB5QKJRCQ4Dx8ASItEJBBMKdhIwfgCg8AB"
    . "g/gPD462AgAAYvH9SG/dYvH9SG/U6xpmLg8fhAAAAAAAg+gQSYPDQIP4Dw+OjgIAAGLRf0hvC2LzdUg+ywVi83VJPsoCYvJ+SCjJYvN1SB/AAMX4mMB0ycX4k8Bm8w+8wA+3"
    . "wEmNNINBi0V0RYtNcE2LVVBJi11YiUQkHEGJw0WFyQ+EEAIAAEQ5yA+PBwIAAItEJDhIifFIifdEjXABTIl0JAiD+g8PjnQCAABIi3QkCEUxwDHASMHmBmYPH0QAAGKxf0hv"
    . "FAFik21IPgwCBWKzbUk+DAMCSYPAQGLyfkgoyWLzdUgf+ADFeJP380UPuPZEAfBJOfB1x00BwkwBw0wBwU1jxEWFwA+FGgEAAESLdCQ8QSnDRInISIn+KdBBKdZNY/ZJweYC"
    . "TAHxRDnYD4xjAQAAhcAPhFsBAACLfCQ4SIl0JAhIiWwkIESNTwFJweEGZg8fRAAAg/oPD45fBAAAMfZFMcBmLg8fhAAAAAAAYvF/SG8UMWLTbUg+DDIFYvNtST4MMwJIg8ZA"
    . "YvJ+SCjJYvN1SB/4AMX4k//zD7j/QQH4TDnOdchNAcpMActMAclFKcMp0EwB8UQ52HwEhcB1lkiLdCQISItsJCBFhdsPj8sAAACLfCQcSItcJChIifFEKd9BiflJjUUUQbgB"
    . "AAAARInChhCE0nX3RTlNEA+NqgMAAEWJTRBJiU0IhhBFO01wD4xL/f//QYtFTEGHRQDpPv3//w8fAMTCOff3g+4BScHgAsX7ks5i8X7Jbwli0X7JbxpNAcJi8X7JbxNMAcNJ"
    . "Aehi83VIPtMFTAHBYvN1Sj7SAmLyfkgoymLzdUgfwADF/EHhxfiT9GbzD7j2D7f2AcZBKfNBKdF0CUU5yw+OD/7//0iJ/kWF2w+ONf///0yNXgRMOVwkEA+DQf3//0iLXCQo"
    . "RItMJDDppfz//4XAdO3Ewnn3x4PoAcX4kshi0X7Jbwti83VIPtUFYvN1Sj7EAmLyfkgoyGLzdUkfyADF+JjJdLrF+JPBZvMPvMAPt8BJjTSDSIX2D4VZ/f//SItcJChEi0wk"
    . "MOlG/P//Dx8ATGPCMcDp2/3//0w5XCQQD4KjAQAASYtFUIn9jUrwQYt9dEWLdXAp1UiJXCQwxMH5buVIiUQkIEmLRVhIY+1EiUwkPEjB5QJFifVIiUQkKInIg+EPwegEiXwk"
    . "OIlEJByJyEyJ2UGJw2YPH4QAAAAAAIt8JDhIi1wkIESJ6EiLdCQoQYn6RYXtD4QEAQAARDnvD4/7AAAAi3wkHEmJyUSNdwFMiXQkCIP6Dw+OoQEAAJBMi3QkCDH/RTHAScHm"
    . "BmaQYtF/SG8sOWLzVUg+DDsFYvNVST4MPgJIg8dAYvJ+SCjJYvN1SB/oAMV4k+XzRQ+45EUB4Ew593XHSAH7SQH5SAH+SWP7hf8PhcMAAABFKcIp0EQ50Hx6hcB0dot8JBxJ"
    . "AelEjWcBScHkBmYPH0QAAIP6Dw+OIgEAADH/RTHAZpBi0X9Ibyw5YvNVSD4MOwVi81VJPgw+AkiDx0Bi8n5IKMli83VIH/AAxXiT9vNFD7j2RQHwTDnndcdMAeNNAeFMAeZF"
    . "KcJJAekp0HQFQTnCfp9FhdIPjskAAABIg8EESDlMJBAPg8f+//9Ii1wkMESLTCQ8xMH5fuVIhdsPhIL6//9Iidnp/vz//w8fgAAAAADEQkH350WNdCT/SMHnAinQxMF7ks5i"
    . "0X7Jbwli8X7JbxtIAfti8X7JbxZIAf5IAe9i83VIPtMFSQH5YvN1Sj7SAmLyfkgoymLzdUgfwADF/EHZxXiT42bzRQ+45EUPt+RFAcRFKeJEOdAPjFL///+FwA+ESv///4P6"
    . "Dw+PYP7//0hj+kUxwOmq/v//RTHA6R////+LfCQ4xMH5fuVIictEKddBifnpPv///8X4d0iDxEhbXl9dQVxBXUFeQV/DhhBFOU1wD4+p+f//6Vn8//+QRTHA6en7//8PH4QA"
    . "AAAAAFdWU0SLVCRITGPCi1QkWESJyEWJy0xjTCRAD7bcQcHrEEEPr9BIY9JMAcpIjTSRi1QkUEEPr9BIY9JMAcpIjRSRSDnyc2pFD7bbD7bbRA+2yEGD+AF0EutnDx+AAAAA"
    . "AEiDwgRIOfJzRw+2SgEp2YnI99gPSMEPtkoCRCnZQYnIQffYQQ9JyDnID0zBD7YKRCnJQYnIQffYQQ9JyDnID0zBQTnCfboxwFteX8MPH0AAuAEAAABbXl/DDx+AAAAAAEnB"
    . "4ALrEmYuDx+EAAAAAABMAcJIOfJz2A+2SgJEKdmJyPfYD0jBD7ZKASnZic/33w9JzznID0zBD7YKRCnJic/33w9JzznID0zBQTnCfcExwOuVZmYuDx+EAAAAAABmkFZTD69U"
    . "JDhMY0QkUESLVCRASGPSSQHQRInIRInLSo00gUxjRCRID7bEwesQTAHCSI0UkUg58nNgD7bbRA+22EUPtsnrDA8fAEiDwgRIOfJzRw+2SgIp2YnI99gPSMEPtkoBRCnZQYnI"
    . "QffYQQ9JyDnID0zBD7YKRCnJQYnIQffYQQ9JyDnID0zBQTnCfboxwFteww8fRAAAuAEAAABbXsNBV0FWQVVBVFVXVlOLRCRoRItcJHhJicpEicmJ00SLTCRwRA+vwU1jwEuN"
    . "FIJJOdIPg8EAAABIY/NBicUp2Q+2/EjB5gJBwe0QSGPZQYn+RQ+27UQPtuBIweMCRTHASIn3xOH5bsJmLg8fhAAAAAAASY0UMkk50nNhTInVSInRkA+2RQJEKehBicdB999B"
    . "D0nHRA+2fQFFKfeJwkSJ+PfYQQ9Ix0QPtn0AOcIPTcJFKedEifr32kQPSfpEOfhBD0zHQTnDfAhEiU0AQYPAAUiDxQRIOc1yqUkB+kkB2sTh+X7ASTnCcolEicBbXl9dQVxB"
    . "XUFeQV/DRTHARInAW15fXUFcQV1BXkFfw2YPH0QAAESLVCQoTYXAidAPlMJNhclBD5TDRAjaD4W2AAAASIXJD4StAAAARQ+20kFp0gABAQBECdKBygAAAP9i8n1IfNKD+A9+"
    . "WESNWPBi8f1Ib8oxwEWJ2kHB6gRBjVIBSMHiBmLxf0hvHAFi8WVI2MFi0f5IfwQAYvF1SNzDYtH+SH8EAUiDwEBIOdB11kgBwUkBwUkBwEHB4gREidhEKdCFwHQ/ugEAAADE"
    . "4nn3woPoAcX4kshi8X7JbwFi8X1I2Mpi8X1I3MJi0X5Jfwhi0X5JfwHF+HcxwMNmLg8fhAAAAAAAxfh3McDDZi4PH4QAAAAAAEFXQVZBVUFUVVdWU0iD7DiLtCSwAAAATIuU"
    . "JMgAAABMiYwkmAAAAEiJyESJw0xj2kiDvCSYAAAAAIuUJKgAAAAPlMFEi4wkuAAAAEiDvCSgAAAAAEEPlMBECMEPhYEBAABIhcAPhHgBAACJ0UUPvsEp8w+vzkQPr8GJTCQI"
    . "SWPIRInHSGnJH4XrUcH/H0jB+SUp+UGJz4uMJMAAAACFyQ+FVAEAAEGA+WQPhEoBAACF2w+IKwEAAEhjyk2J3ESNavBEiUQkKEkpzItMJAhIiUQkGGLzdUglyf9JweQCiVwk"
    . "LEG+AQAAAEQ5+UyJlCTIAAAASo0sIEEPncGFyQ+VwUEhyUqNDJ0AAAAARTHbSIlMJCBEienB6QREiEwkEI15AcHhBESJXCQMQSnNSMHnBkSJbCQESItEJBhJicFIOcUPgnwE"
    . "AACAfCQQAHQS6WUDAABJg8EETDnND4JjBAAAg3wkKGN/7EyLlCTIAAAARIn+TYXSD4WuBAAAxfh362eFwHQ3xMJ598aD6AHF+JLIYtF+yW8BYvN9SD7VBWLzfUo+xAJi8n5I"
    . "KMBi831JH8EAxfiYwA+FrgEAAEiLRCQQTItcJBhEi0QkIItcJChBg8ABTAHYTAHdQTnYD474AAAAxfh3RTHJTInISIPEOFteX11BXEFdQV5BX8NIi7QkmAAAAEiLjCSYAAAA"
    . "RA+2RgEPtkkCQcHgCMHhEEQJwUQPtgZIi7QkoAAAAEQJwUQPtkYBYvJ9SHzpSIuMJKAAAABBweAID7ZJAsHhEEQJwUQPtgZECcGByQAAAP9i8n1IfOGF2w+IeP///0hjyk2J"
    . "3ESNavBEiXwkDEkpzItMJAhMiZQkyAAAAEG+AQAAAEnB5AJi83VIJcn/hclKjSwgQQ+VwEQ5+Q+dwUnB4wJBIchEiEQkLEmJwESJ6MHoBI14AcHgBEEpxTHASMHnBkSJbCQE"
    . "icFMicBBichJicFi8f1Ib91i8f1Ib9RIOcUPgt3+//9IiUQkEA+2TCQsTIlcJBhEiUQkIIlcJChmDx+EAAAAAABIiehMKchIwfgCg8ABg/gPfx7pV/7//2YPH4QAAAAAAIPo"
    . "EEmDwUCD+A8Pjj7+//9i0X9IbwFi831IPssFYvN9ST7KAmLyfkgowWLzfUgfwQDF+JjAdMnF+JPAZvMPvMCLdCQMD7fATY0MgYTJD4TwAAAASIucJKAAAABMi5wkmAAAAE2J"
    . "yESLVCQIi3QkDJAxwEUx/4P6Dw+OAAEAAGaQYtF/SG8EAGLTfUg+DAMFYvN9ST4MAwJIg8BAYvJ+SCjBYvN9SB/xAMV4k+7zRQ+47UUB70g5+HXHSGNEJARJAftJAfhIAfuF"
    . "wA+EkQAAAMRCeffuQYPtAUjB4AJBKdLEwXuSzWLRfslvAGLBfslvA0kBw2LhfslvC0gBw0wB4GKzfUg+0AVJAcBis31KPtECYvJ+SCjCYvN9SB/BAMX8QenFeJPtZvNFD7jt"
    . "RQ+37UUB/UQp7kE58nwJRYXSD4Ut////hfYPjroBAABJg8EETDnND4OI/v//6Sz9//8PHwBEKf5NAeBBKdJ02EQ51n/TMcBFMf+D+g8PjwL///9IY8LpQf///0iJ6Q8fgAAA"
    . "AABIi5wkoAAAAESLVCQITYnIRIn+TIucJJgAAAAPH0QAADHARTHtg/oPD44gAQAAZpBi0X9IbyQAYtNdSD4MAwVi811JPgwDAkiDwEBi8n5IKMFi831IH9kAxfiT6/MPuO1B"
    . "Ae1IOfh1yEhjRCQESQH7SQH4SAH7hcAPhLIAAADEwnn37oPtAUjB4AJBKdLF+5LNYtF+yW8AYtF+yW8bSQHDYvF+yW8TSAHDTAHgYvN9SD7TBUkBwGLzfUo+0gJi8n5IKMJi"
    . "831IH8EAxfxB4cX4k+xm8w+47Q+37UQB7SnuRDnWfwlFhdIPhTP///+F9n5lSYPBBEw5yQ+DAv///0iJzUiLdCQgg0QkDAGLTCQsi0QkDEgBdCQYSAH1OcgPjlH7///F+Hfp"
    . "9/v//w8fRAAARCnuTQHgQSnSdLJEOdZ/rTHARTHtg/oPD4/i/v//SGPC6SD///9Mi5QkyAAAAE2F0g+EUvv//0Ep90WJOsX4d+mw+///TIuUJMgAAABEi3wkDE2F0g+ELvv/"
    . "/0SJ+CnwQYkCxfh36Yr7//8PH0QAAEFVQVRVV1ZTSIHsWAEAAEyLnCSwAQAATIuUJLgBAACLvCTAAQAARIukJMgBAACLhCTQAQAASIu0JOABAABIjVwkX0iD48BNhdtAD5TF"
    . "TYXSQQ+UxUQI7Q+FAwEAAEiF0g+E+gAAAMX578Bi8X9If0MBSIlTQIuUJNgBAABEiUNIhdKJe2APlcI8ZIhDaA++wEEPlMBBD6/8YvF/SH8DRAnCSIlLGEmJ2A+20kSJS0wP"
    . "r8eJU2xMiVtQTIlTWEhj0MH4H0SJY2RIadIfhetRiXtwSMH6JSnCQQ+2QwKJU3RBD7ZTAcHgEMHiCAnQQQ+2EwnQQQ+2UgFi8n1IfMBBD7ZCAmLxfkh/QwLB4gjB4BAJ0EEP"
    . "thIJ0EiNFTLu//8NAAAA/2LyfUh8wGLxfkh/QwPF+Hf/kdAAAABIhfZ0BYtDEIkGSItDCEiBxFgBAABbXl9dQVxBXcNmDx+EAAAAAAAxwEiBxFgBAABbXl9dQVxBXcNmZi4P"
    . "H4QAAAAAAA8fAEFVQVRVV1ZTSItcJFhEi1QkeESLnCSAAAAASIXJD4QFAQAASIXbD4T8AAAAi0QkaDH2RAnAC0QkYAnQD4ixAAAARYXSD47eAAAARYXbD47VAAAARQ+vwUhj"
    . "0kGNcvBNY8lKjSyNAAAAAEG8AQAAAEUxyUljwEgB0EhjVCRgSI0MgYtEJGgPr0QkcEiYSAHQSI0Ug4nwSGNcJHDB6AREjUABweAESMHjAknB4AYpxmaQMcBBg/oPD458AAAA"
    . "Dx9AAGLx/khvDAJi8f5IfwwBSIPAQEk5wHXphfZ1JUGDwQFIAelIAdpFOct/xr4BAAAAxfh3ifBbXl9dQVxBXcMPHwBOjSwCSo08AYnwxMJ598SD6AHF+JLIYtF+yW9FAGLx"
    . "fkl/B+u2Dx8AMfaJ8FteX11BXEFdww8fAESJ0EiJz0mJ1evHZmYuDx+EAAAAAABmkEiD7HhMi5wkqAAAAEiF0g+E0wAAAE2F2w+EygAAAIuEJLgAAABFMdJECcgLhCSwAAAA"
    . "RAnAD4ihAAAARIuUJMgAAABFhdIPjpwAAACLhCTQAAAAhcAPjo0AAACLhCSgAAAASIlUJDBIjRXi6v//xflulCTAAAAARIlEJDhMjUQkIMTjaSKMJMgAAAABiUQkQMX5bpwk"
    . "sAAAAIuEJNAAAABIiUwkKMTjYSKEJLgAAAABx0QkIAAAAABEiUwkPMX5bMFMiVwkSIlEJGDF+n9EJFD/kdAAAABBugEAAABEidBIg8R4ww8fQABFMdJEidBIg8R4w2ZmLg8f"
    . "hAAAAAAAZpC4BAAAAMOQkJCQkJCQkJCQ"
    mcode_imgutil_column_uniform := 0x0007c0 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x0008e0 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_replace_color  := 0x000980 ; i32 imgutil_replace_color(argb *ptr, i32 width, i32 height, i32 stride, argb cold, argb cnew, i32 tolerance)
    mcode_imgutil_make_sat_masks := 0x000a90 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000b80 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x0011e0 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x001360 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x0014b0 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x0015b0 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                                                
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_replace_color",     code + mcode_imgutil_replace_color
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                    )
    }

    ;############################################################################################################
    ; base code, independent of optimization level/architecture
    ;############################################################################################################
    i_get_mcode_map_base() {
        ; this can't be part of the main blob as we don't want GCC to taint it with
        ; vectorization or the use of other instructions that may not be available
        ; on older CPUs
        static b64 := ""
    . "" ; imgutil_lib.c
    . "" ; 2880 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -mabi=ms -m64 -D __HEADLESS__ -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "VVdWU0iD7Di/AQAAAEiJy/APwbnMAAAASIuRkAAAAEhjx0iNdCQg8w9+BMJIjSzFAAAAAA8WgZgAAAAPEUQkIOsjZg8fRAAASIuLwAAAAIn6/5O4AAAASIuDoAAAAEiLDCj/"
    . "U3BFMcBBuf////9IifK5AgAAAP+TiAAAAIXAdMgxwEiDxDhbXl9dww8fRAAAVlNIg+woMcBIictIhcl1EEiDxChbXsNmDx+EAAAAAABIh5G4AAAATIeBwAAAAIuJyAAAAIXJ"
    . "dCQx9mYPH0QAAEiLg5AAAABIiwzwSIPGAf9TcIuLyAAAADnOcuRIi5OgAAAAQbn/////QbgBAAAA/5OIAAAAuAEAAABIg8QoW17DZmYuDx+EAAAAAAAPH0AAVVdWU0iD7BhF"
    . "McBFMdtFMclEicBEicEPokSJwUyNBR0IAACJxrgAAACASY2o0AEAAA+iicdBi1AMQYsAQTnTRA9C2j0AAACAdj45x3JCRInJRYtQCA+iiQQkSWNABIlcJASJTCQIiVQkDEQj"
    . "FIR0IEmDwBBJOeh1vESJ2EiDxBhbXl9dww8fADnGc8KFwHi+QYPrAUSJ2EiDxBhbXl9dw2VIiwQlYAAAAEiLQBhIi0AgSIsASIsASItAIMNHZXRQcm9jQWRkcmVzcwAPH0QA"
    . "AFZTSYnLTInZi0E8SAHISI1AGEiNQHBIi8CLEEiNBBGLWBiLUCCF23RTRTHSSY00E0KLFJZBuEcAAABMjQ2r////TAHaD7YKhMl1HusmDx8ARDjBdR4PtkoBSIPCAUmDwQFF"
    . "D7YBhMl0BUWEwHXiRDjBdA5Jg8IBSTnadbQxwFtew4tQJEuNDFOLQBwPtxQRSY0Uk4sEAkwB2Fteww8fQABWU0iD7ChIictIhckPhLYAAABIi4mYAAAA/1NwSIuTqAAAAIuL"
    . "yAAAAEG5/////0G4AQAAAP+TiAAAAEiLi5gAAAD/k4AAAACLg8gAAACFwHRFMfYPH0AASIuDqAAAAEiLDPD/k4AAAABIi4OgAAAASIsM8P+TgAAAAEiLg5AAAABIiwzwSIPG"
    . "Af+TgAAAADuzyAAAAHLBSIuLoAAAAP9TKEiLi5AAAAD/UyhIi4uoAAAA/1MoSItDKEiJ2UiDxChbXkj/4A8fAEiDxChbXsOQVVdWU0iD7EhIi0FQx0QkOAAAAABIic5IhcAP"
    . "hAABAABIjXwkPEUxyTHSMclJifjHRCQ8AAAAAEjHRCQgAAAAAP/Qi1QkPLlAAAAA/1YgSInDSIXAD4S2AAAARTHJi1QkPEmJ+EiJwUjHRCQgAAAAAP9WUIXAD4SVAAAARItE"
    . "JDxFhcAPhC8BAABIidoxyUG6/////0Ux2zHtRTHJ6x5mkIPFAUGJwmYuDx+EAAAAAACLAgHBSAHCRDnBczSLQgSFwHXtD7ZCD0Q50HTkQYPBAYB6EgB0ykGJwosCQYPDAQHB"
    . "SAHCRDnBctMPH4AAAAAARInPKe9FhdtBD0T5SInZ/1YoifhIg8RIW15fXcMPHwAx/4n4SIPESFteX13DDx8AMdtIjXwkOOsuDx+AAAAAAP9WMIP4enXYSIXbdAZIidn/ViiL"
    . "VCQ4uUAAAAD/ViBIicNIhcB0uUiJ+kiJ2f9WSIXAdMyLRCQ4g/gfdkuNSOAx/0iJ2EGJyEHB6AVBjVABSMHiBUgB2mYPH4QAAAAAAIN4CAGD1wBIg8AgSDnCdfBBweAFichE"
    . "KcCJRCQ46Ur///9mDx9EAAAx/+k9////R2xvYmFsRnJlZQBHbG9iYWxBbGxvYwBMb2FkTGlicmFyeUEARnJlZUxpYnJhcnkAkEdldExvZ2ljYWxQcm9jZXNzb3JJbmZvcm1h"
    . "dGlvbgBHZXRTeXN0ZW1DcHVTZXRJbmZvcm1hdGlvbgBHZXRMYXN0RXJyb3IAUXVlcnlQZXJmb3JtYW5jZUNvdW50ZXIAUXVlcnlQZXJmb3JtYW5jZUZyZXF1ZW5jeQBDcmVh"
    . "dGVUaHJlYWQAV2FpdEZvclNpbmdsZU9iamVjdABDcmVhdGVFdmVudEEAU2V0RXZlbnQAUmVzZXRFdmVudABDbG9zZUhhbmRsZQBXYWl0Rm9yTXVsdGlwbGVPYmplY3RzAGaQ"
    . "QVVBVFVXVlNIg+w4ZUiLBCVgAAAASItAGEiLQCBIiwBIiwBIi0AgSInGic1IhcAPhOUCAABIicHog/v//0iNFav+//9IifFIicf/0EiNFaf+//9IifFJicX/17rYAAAAuUAA"
    . "AABJicT/0EiJw0iFwA+EpAIAAEiNBeP5//9IjRWC/v//SInxSIkzSImD0AAAAEyJYyBIiXsITIlrKP/XSI0Vbf7//0iJ8UiJQxD/10iNFWr+//9IifFIiUMY/9dIjRV5/v//"
    . "SInxSIlDSP/XSI0VhP7//0iJ8UiJQ1D/10iNFYH+//9IifFIiUMw/9dIjRWJ/v//SInxSIlDOP/XSI0Vk/7//0iJ8UiJQ0D/10iNFZD+//9IifFIiUNY/9dIjRWU/v//SInx"
    . "SIlDYP/XSI0Vkf7//0iJ8UiJQ2j/10iNFYr+//9IifFIiUNw/9dIjRWF/v//SInxSIlDeP/XSI0Vgf7//0iJ8UiJg4AAAAD/10iJg4gAAACF7Q+EVwEAAI0U7QAAAAC5QAAA"
    . "AImryAAAAEH/1LlAAAAASImDqAAAAIuDyAAAAI0UxQAAAABB/9S5QAAAAEiJg5AAAACLg8gAAACNFMUAAAAAQf/UMclFMclFMcBIiYOgAAAAugEAAAD/U2hIg7uoAAAAAEjH"
    . "g7gAAAAAAAAASImDmAAAAEiLi5AAAABIx4PAAAAAAAAAAMeDzAAAAAAAAAAPhM8AAABIhckPhMYAAABIi4OgAAAASIXAD4S2AAAAi5PIAAAAhdJ0fTHtTI0lg/f//+sIkEiL"
    . "g6AAAABIjTTtAAAAAEUxyUUxwDHSSI08MDHJSIPFAf9TaEUxyUUxwDHSSIkHSIu7kAAAADHJ/1NoSYnZTYngMdJIAfcxyUiJB0gDs6gAAABIx0QkKAAAAADHRCQgAAAAAP9T"
    . "WEiJBjuryAAAAHKPSInYSIPEOFteX11BXEFdww8fgAAAAABIidnoUPr//4nF6Zr+//9mDx+EAAAAAAD/k4AAAABIi4ugAAAA/1MoSIuLqAAAAP9TKEiLi7AAAAD/UyhIidlB"
    . "/9Ux20iJ2EiDxDhbXl9dQVxBXcMPH0AAAQAAAAMAAAABAAAAAQAAAAEAAAADAAAAAAEAAAEAAAABAAAAAwAAAAAIAAABAAAAAQAAAAMAAAAAgAAAAQAAAAEAAAADAAAAAAAA"
    . "AQEAAAABAAAAAwAAAAAAgAABAAAAAQAAAAMAAAAAAAABAQAAAAEAAAADAAAAAAAAAgEAAAABAAAAAwAAAAAAAAQBAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAACAAAAIA"
    . "AAABAAAAAgAAAAAACAACAAAAAQAAAAIAAAAAABAAAgAAAAEAAAACAAAAAACAAAIAAAABAACAAgAAAAEAAAACAAAAAQAAAAIAAAAAEAAAAwAAAAEAAAACAAAAAABAAAMAAAAB"
    . "AAAAAgAAAAAAAAgDAAAAAQAAAAIAAAAAAAAQAwAAAAEAAAACAAAAAAAAIAMAAAABAACAAgAAACAAAAADAAAABwAAAAEAAAAIAAAAAwAAAAcAAAABAAAAIAAAAAMAAAAHAAAA"
    . "AQAAAAABAAADAAAABwAAAAEAAAAAAAEABAAAAAcAAAABAAAAAAACAAQAAAAHAAAAAQAAAAAAABAEAAAABwAAAAEAAAAAAABABAAAAAcAAAABAAAAAAAAgAQAAACQkJCQkJCQ"
    . "kJCQkJCQkJCQ"
    mcode_mt_threadproc         := 0x000000 ; 
    mcode_mt_run                := 0x000090 ; 
    mcode_get_cpu_psabi_level   := 0x000120 ; int get_cpu_psabi_level()
    mcode_gpa_getkernel32       := 0x0001c0 ; 
    mcode_gpa_getgetprocaddress := 0x0001f0 ; 
    mcode_mt_deinit             := 0x000290 ; 
    mcode_mt_get_cputhreads     := 0x000360 ; int mt_get_cputhreads(mt_ctx *ctx)
    mcode_mt_init               := 0x000630 ; 
    ;----------------- end of ahkmcodegen auto-generated section ------------------
            
        static code := this.i_b64decode(b64)
        codemap := Map( "get_cpu_psabi_level",       code + mcode_get_cpu_psabi_level
                      , "mt_get_cputhreads",         code + mcode_mt_get_cputhreads
                      , "mt_init",                   code + mcode_mt_init
                      , "mt_deinit",                 code + mcode_mt_deinit
                      )
        return codemap
    }








