#Requires AutoHotkey v2.0

; imgutil class member functions

    ;########################################################################################################
    ; scalar only, this is just for benchmarking comparison and not meant to be used. v0 is below the psabi 
    ; baseline, there's no equivalent psabi level and get_cpu_psabi_level should never return it.
    ; (theoretically it might, if e.g. SSE has been masked off from CPUID in a VM, so... eh?)
    ;########################################################################################################
    i_get_mcode_map_v0() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 11072 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=core2 -D MARCH_x86_64_v0 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "VlNEi0FASItBCEhjcSBBD6/QRIuQyAAAAEGJ0YnQMdJB9/Ix0kGJw0ONBAhEi0E0QffySGNROExjSTBMY1EYRQHYRA+vwk1jwE0ByEyLSShPjQSBRItJHEUB2UQPr85NY8lN"
    . "AdFMi1EQT40MikE5w31GRItRPEiNHJUAAAAASMHmAkWF0nQxZg8fhAAAAAAAMdJmDx9EAABBiwyQQYkMkUiDwgFMOdJ170GDwwFJAdhJAfFEOdh12Fteww8fRAAASInISGNM"
    . "JCiFyXg0TI1ciATrDg8fRAAASIPABEw52HQfRDpIAkEPk8JEOkABD5PBQYTKdOM6EHLfw2YPH0QAADHAw2ZmLg8fhAAAAAAAZpBBV0FWQVVBVFVXVlNED7ZcJGgPtlwkcA+2"
    . "dCR4hdJJicoPjnwAAACJ0kUx5EyNLJFBD7YKQcZAAwBBD7ZSAUHGQQP/QQ+2QgJBic5FKN6J1UUPQvSJx0Ao3UEPQuxAKPdBD0L8RADZRYgwRRj/QYhoAUQJ+QDaQYh4AkUY"
    . "/0GICUQJ+kAA8EGIUQEY0kmDwgRJg8EECdBJg8AEQYhB/k056nWNMcBbXl9dQVxBXUFeQV/DZmYuDx+EAAAAAAAPHwBBV0FWQVVBVFVXVlNIgew4AQAADxG0JJAAAAAPEbwk"
    . "oAAAAEQPEYQksAAAAEQPEYwkwAAAAEQPEZQk0AAAAEQPEZwk4AAAAEQPEaQk8AAAAEQPEawkAAEAAEQPEbQkEAEAAEQPEbwkIAEAADH/Zg/vwGYPb+hmDzgALeIoAACJ/mYP"
    . "1mwkMEiJz0iJjCSAAQAAifW6AQAAAPAPwReLRywrR0Q50A+M8A8AAEhjRyhIi08gD6/QSGPSSI0MkUhjV0BIKdBIidaLV0xIweACSIlEJGhIAchIiUQkUIXSD4QGCAAASDnI"
    . "cqwPtkddRI12/4msJIwAAABIif1EifMPtldcg+PwRA+2T17zRA9vPR8oAACJXCR4iEQkcESJ8MHoBIhUJHxIweAGRIiMJIgAAABIiUQkSInYTI0chQAAAACJ8CnYTYnfRInz"
    . "iUQkRESJ8EyNJIUEAAAATYnmZg8fRAAASItEJFBED7aMJIgAAABED7ZEJHAPtlQkfEgpyEjB+AKDwAGJRCQg6GT9//9IhcBIicEPhMAGAABEi01URItlUEiLfThFOeEPj9UG"
    . "AABFheRJicNFic0PhMYGAABIi1QkaESJTCRYZkUP79vzRA9+NVwnAABIiUQkYEiJrCSAAQAADx+AAAAAAIX2D44xBgAAg/sPD4ZuBgAATItUJEhIifhMidlmRQ/vyWZFD+/t"
    . "TY0EOvMPbwFmQQ9v12ZBD2/PZkEPb9/zD295EGZBD2/3ZkUPb+dIg8BA8w9vaSBmD9vQZg9x0AhIg8FAZg/bz2YPZ9HzD29J8GYPcdcI80QPb1DQZkEP2+9mD2fHZkEP28dm"
    . "QQ/bz2YPZ+nzD29IwPMPb2DgZkEP2/JmQQ9x0gjzRA9vQPBmD9vZZg9n3mZBD2/3Zg/b9GYPcdEI8w9vefBmRQ/b4GYPcdQIZkEPZ8pmQQ/bz2ZBD3HQCGZBD2f0ZkEPZ+Bm"
    . "QQ/b52YPZ8zzD29h4GYPcdcISTnAZg9x1AhmD2fnZkEP2+dmD2fEZg/ayGYPdMFmD2/mZg9vy2ZBD9v3Zg9x1AhmD2/9ZkEP299mQQ/b72YPcdEIZg9n3mYPZ8xmD2/iZg9x"
    . "1whmQQ/b12YPcdQIZg9n1WYP2tpmD+/tZg9n52YP2sxmD3TTZg904WYP28RmD9vCZg/bBdElAABmD2/IZg9gzWYPb9FmD2jFZkEPac1mQQ9h1WYP/spmD2/QZkEPacVmQQ9h"
    . "1WYP/sJmD/7IZkQP/skPhWT+//9mQQ9vwWZBD2/5i2wkeGYPc9gIRItUJERLjQw7To0EP2ZBD/7BZg9vyGYPc9kEZg/+wWYPfsBBDxLBZg/++GYP1nwkOEGJ2UEp6UGD+QcP"
    . "hkICAABIweUCZkEPb85mQQ9vxkmNBCtmRQ9vxkgB/fMPfhBmQQ9v3mZBD2/+ZkUPb+7zRA9+YAhBg+H48w9+aBhmD9vKZg9x0ghFKcrzD35wEGZBD9vEZg9nyGZBD3HUCGZB"
    . "D2/GZkEPZ9TzRA9+VQhmRA9v5WYP28VmRA/bxmYP7+1mRA9nwPMPfkUAZg9x1ghmQQ/b+mYPcNII8w9+ZRBmQQ9x1AhmQQ/b1mYPcMkI80QPfk0YZg/b2GYPZ99mQQ9n9GZB"
    . "D2/+ZkQPb+JmD2/QZkUPcMAIZg/b/GZFD9vpZg9x0ghmD2/BZkEPcdIIZg9w2whmQQ9n/USJzWYPcdQIZkEPZ9JmD3DSCGZBD9vWZkEPcdEIZg9w/whmD3D2CGZBD9v2ZkEP"
    . "Z+FmD3DkCGZBD9vmZg9n1GZBD2/gZg9x0AhmRA9n5mYPb/dmD3HUCGZFD3DkCGZBD9v+Zg9w0ghmD2fEZg9v42YPcdYIZg9wwAhmD3HUCGZBD9rUZkEP285mRQ/bxmYPZ+Zm"
    . "QQ9nyGYPcOQIZg9wyQhmD9rgZkEP295mD2ffZg9w2whmD9rZZg90xPMPfjWHIwAASMHlAmYPdMvzD358JDBIAelJAehmQQ901GYP29BmD9vKZg/bzmYPb8FmD2DFZg9gzWYP"
    . "b9hmD3DJTmYPb9FmQQ9h22ZBD2HDZkEPYctmD3DATmZBD2HTZg/+w2YPcMlOZg/+yvMPfmwkOGYP/sFmD/7FZg9vyGYPOAANGCMAAGYP689mD/7BZg9+wEQPtkkCRThIAg+2"
    . "aQFBD5PBQThoAUAPk8VEIc1ED7YJRTgIQQ+TwUUPtslBIelEAchBg/oBD4SZAQAARA+2SQZFOEgGD7ZpBUEPk8FBOGgFQA+TxUQhzUQPtkkERThIBEEPk8FFD7bJQSHpRAHI"
    . "QYP6Ag+EXAEAAEQPtkkJRThICQ+2aQpBD5PBQThoCkAPk8VEIc1ED7ZJCEU4SAhBD5PBRQ+2yUEh6UQByEGD+gMPhB8BAABED7ZJDUU4SA0PtmkOQQ+TwUE4aA5AD5PFRCHN"
    . "RA+2SQxFOEgMQQ+TwUUPtslBIelEAchBg/oED4TiAAAARA+2SRJFOEgSD7ZpEUEPk8FBOGgRQA+TxUQhzUQPtkkQRThIEEEPk8FFD7bJQSHpRAHIQYP6BQ+EpQAAAEQPtkkV"
    . "RThIFQ+2aRZBD5PBQThoFkAPk8VEIc1ED7ZJFEU4SBRBD5PBRQ+2yUEh6UQByEGD+gZ0bEQPtkkaRThIGg+2aRlBD5PBQThoGUAPk8VEIc1ED7ZJGEU4SBhBD5PBRQ+2yUEh"
    . "6UQByEGD+gd0M0QPtlEeRThQHkQPtlEdD7ZJHEEPk8FFOFAdQQ+TwkUh0UE4SBwPk8EPtslEIckByA8fAE0B80wB90EpxUkB00Ep9HQJRTnsD422+f//RYXtRItMJFhIi0wk"
    . "YEiLrCSAAQAAfkFIg8EESDlMJFAPgwj5//9Iie+LrCSMAAAA6Sz4//9Ix0QkOAAAAABBifIx7THASYn4TInZ6XD7//9Fic1Fhe1/v0SJyEiJ70Qp6InFSI1HFEG4AQAAAESJ"
    . "woYQhNJ19zlvEH0HiW8QSIlPCIYQOW9QD4/U9///ie5Ii4QkgAEAAEiLnCSAAQAAi0AshwNIi7wkgAEAAOmu9///Dx9EAABIOUwkUA+CnQcAAEiLRzhEjX7/RItXVESJ+kiJ"
    . "RCRwi0dQQTnCiUQkfEEPnsGFwESJ+EEPlcDB6ASD4vBIweAGiVQkREiJw4nQTI0shQAAAACJ8CnQRYTBiUQkeESJ+EiNFIUEAAAAD4T2BgAASIlcJEhEiftMi3wkaEyJ6PNE"
    . "D289wh8AAESJVCRgSYnViawkiAAAAEiJvCSAAQAADx8ASItsJHBJictIiUwkWGZFD+/bRItkJHxEi3QkYPNED341gx8AAA8fAIX2D44xBgAAg/sPD4aXBgAASIt8JEhMidpI"
    . "ielmRQ/vyWZFD+/tTo0EH/MPbxJmQQ9vz2ZBD2/HZkEPb/fzRA9vUhBmQQ9v32ZBD2/vSIPCQPMPb2LgZg/bymYPcdIISIPBQPNED29C8GZBD9vCZg9nyGZBD2/H8w9vedBm"
    . "D9v0ZkEPcdIIZkEP28BmD2fw8w9vQcBmD3HUCGYP2+9mD3HXCGZBD2fSZkEP29dmD9vYZkEPcdAIZg9n3fNED29h8GYPcdAIZkEPZ+BmQQ/b52YPZ9RmD2fH8w9vYeBmQQ/b"
    . "x2ZFD9vn8w9vefBmD3HUCPMPb2ngSTnQZg9x1whmD2fnZkEP2+dmD2fEZg/awmYPdMJmD2/mZg9v0WZBD9vvZg9x1AhmQQ9n7GYPb/1mQQ/b92YPcdIIZkEP289mQQ/b72YP"
    . "Z85mD2fUZg9v42YPcdcIZg/v9mYPcdQIZkEP299mD2fdZg/a2WYPZ+dmD9riZg90y2YPdNRmD9vCZg/bwWYP2wUIHgAAZg9vyGYPYM5mD2/RZg9oxmZBD2nNZkEPYdVmD/7K"
    . "Zg9v0GZBD2nFZkEPYdVmD/7CZg/+yGZED/7JD4Vj/v//ZkEPb8FmQQ9v+Yt8JERmD3PYCESLVCR4SY0MA0yNRAUAZkEP/sFmD2/IZg9z2QRmD/7BZg9+wkEPEsFmD/74Zg/W"
    . "fCQ4QYnZQSn5QYP5Bw+GRQIAAEjB5wJmQQ9vzmZBD2/GSY0UO2ZFD2/GSAHv8w9+GmZBD2/mZkEPb/5mRQ9v7vNED35iCEGD4fjzD35yEGYP28tmD3HTCEUpyvMPflIYZkEP"
    . "28RmD2fIZkEPcdQIZkEPb8bzRA9+VwhmRA/bxmZBD2fcZg/bwmZED2/iZkQPZ8DzD34H8w9+bxBmQQ9x1AhmQQ/b+mYPcNsI80QPfk8YZg9x1ghmD9vgZkEP295mD2fnZkEP"
    . "Z/RmQQ9v/mZED2/jZg9v2GYP2/1mRQ/b6WZBD3HSCGYPcdMIZg9wyQhmRQ9wwAhmD2/BZg9x1QhmQQ9n2mYPcNsIZkEP295mQQ9x0QhmD3DkCGZBD2f9RInPZkEPZ+lmD3Dt"
    . "CGZBD9vuZg9n3WZBD2/oZg9x0AhmD3D/CGYPcPYIZg9x1QhmQQ/b9mZED2fmZg9v92YPZ8VmD2/sZg9x1ghmRQ9w5AhmD3HVCGYPcMAIZkEP2/5mD3DbCGYPZ+5mQQ/a3GYP"
    . "cO0IZkEP285mD9roZkUP28ZmQQ/b5mZBD2fIZg9n52YPcMkIZg9w5AhmD9rhZg90xWYP7/bzD349vhsAAEjB5wJmD3TM8w9+bCQ4SAH5SQH4ZkEPdNxmD9vYZg/by2YP289m"
    . "D2/ZZg9g3mYPYM5mD3DJTmYPb+FmD2/BZg9vy2ZBD2HjZkEPYdtmQQ9hy2ZBD2HDZg9w205mD3DATmYP/tnzD358JDBmD/7EZg/+w2YP/sVmD2/IZg84AA1LGwAAZg/rz2YP"
    . "/sFmD37CD7Z5AkE4eAIPtnkBQQ+TwUE4eAFAD5PHRCHPRA+2CUU4CEEPk8FFD7bJQSH5RAHKQYP6AQ+ElQEAAA+2eQZBOHgGD7Z5BUEPk8FBOHgFQA+Tx0Qhz0QPtkkERThI"
    . "BEEPk8FFD7bJQSH5RAHKQYP6Ag+EWQEAAA+2eQpBOHgKD7Z5CUEPk8FBOHgJQA+Tx0Qhz0QPtkkIRThICEEPk8FFD7bJQSH5RAHKQYP6Aw+EHQEAAA+2eQ5BOHgOD7Z5DUEP"
    . "k8FBOHgNQA+Tx0Qhz0QPtkkMRThIDEEPk8FFD7bJQSH5RAHKQYP6BA+E4QAAAA+2eRJBOHgSD7Z5EUEPk8FBOHgRQA+Tx0Qhz0QPtkkQRThIEEEPk8FFD7bJQSH5RAHKQYP6"
    . "BQ+EpQAAAA+2eRZBOHgWD7Z5FUEPk8FBOHgVQA+Tx0Qhz0QPtkkURThIFEEPk8FFD7bJQSH5RAHKQYP6BnRtD7Z5GkE4eBoPtnkZQQ+TwUE4eBlAD5PHRCHPRA+2SRhFOEgY"
    . "QQ+TwUUPtslBIflEAcpBg/oHdDUPtnkeQTh4Hg+2eR0PtkkcQQ+TwUE4eB1BD5PCRSHRQThIHA+TwQ+2yUQhyQHKDx+AAAAAAE0B60wB7UEp1k0B+0Ep9HQJRTn0D422+f//"
    . "RYX2SItMJFh+b0iDwQRIOUwkUA+Ddfn//4usJIgAAABIi7wkgAEAAEiLjCSAAAAASIXJD4Rg8P//6V34//8PH4QAAAAAAEiDwQRIOUwkUHJFRYXSf/BFidbrKw8fAEjHRCQ4"
    . "AAAAAEGJ8jH/MdJJiehMidnpSfv//0SLVCRgSIu8JIABAABFKfJIiYwkgAAAAESJ1euaSIuMJIAAAADrkA8QtCSQAAAADxC8JKAAAABEDxCEJLAAAABEDxCMJMAAAABEDxCU"
    . "JNAAAABEDxCcJOAAAABEDxCkJPAAAABEDxCsJAABAABEDxC0JBABAABEDxC8JCABAABIgcQ4AQAAW15fXUFcQV1BXkFfw2YuDx+EAAAAAABXVlOLXCRIRInISGPySInPSGNM"
    . "JEAPtsRFichBicKLRCRYQcHoEA+vxkiYSAHITI0ch4tEJFAPr8ZImEgByEiNDIdMOdlzaYP+AUUPtsBFD7bSRQ+2yXQR62ZmDx9EAABIg8EETDnZc0cPtkEBRCnQmTHQKdAP"
    . "tlECRCnCidbB/h8x8inyOdAPTMIPthFEKcqJ1sH+HzHyKfI50A9MwjnDfb4xwFteX8MPH4QAAAAAALgBAAAAW15fww8fgAAAAABIweYC6xJmLg8fhAAAAAAASAHxTDnZc9gP"
    . "tkECRCnAmTHQKdAPtlEBRCnSidfB/x8x+in6OdAPTMIPthFEKcqJ18H/HzH6Kfo50A9MwjnDfb8xwOuPZmYuDx+EAAAAAABWUw+vVCQ4i1wkQEhj0kiJzkhjTCRQRYnKRInI"
    . "QcHqEA+2xEgB0UyNHI5IY0wkSEgBykiNDJZMOdlzZUUPttJED7bARQ+2yesQDx+AAAAAAEiDwQRMOdlzRw+2QQJEKdCZMdAp0A+2UQFEKcKJ1sH+HzHyKfI50A9Mwg+2EUQp"
    . "yonWwf4fMfIp8jnQD0zCOcN9vjHAW17DZg8fhAAAAAAAuAEAAABbXsMPH4QAAAAAAFNIg+xARItUJHBNhcAPlMBNhclBD5TDRAjYdTxIhcl0N0UPttJBacIAAQEARAnQDQAA"
    . "AP9BicKIZCQoQcHqEIhEJCBEiFQkMOgT7P//SIPEQFvDDx9EAAAxwEiDxEBbw0FXQVZBVUFUVVdWU0iB7GgBAAAPEbQkwAAAAA8RvCTQAAAARA8RhCTgAAAARA8RjCTwAAAA"
    . "RA8RlCQAAQAARA8RnCQQAQAARA8RpCQgAQAARA8RrCQwAQAARA8RtCRAAQAARA8RvCRQAQAARIu0JNgBAABEi5Qk4AEAAE2FyUhjwkiJyw+UwkSJwUSLhCToAQAASIO8JNAB"
    . "AAAAQQ+UwUQIyg+FRggAAEiF2w+EPQgAAESJ8kQp0UEPr9KJz4nWiVQkeEEPvtAPr/JIY9ZBifFIadIfhetRQcH5H0jB+iVEKcpBidOLlCTwAQAAhdIPhYUIAABBgPhkD4R7"
    . "CAAAhckPiOgHAABEi3wkeEljzkiJwmYP79JFjWb/SCnKZg9v8vNED289xxQAAEiNLIUAAAAASMHiAkSJ4GYPOAA13xQAAEyNFBNmD9Z0JEBFhf8PlcFFOd9BD53AwegERTHJ"
    . "RCHBSYnYRInjg+PwSMHgBohMJHxIiUQkSInYTI08hQAAAABEifCJXCRUKdhMifmJRCRYRIngSI0chQQAAACJ8EmJ30iJ00iJyk05wkyJwQ+CKAcAAIB8JHwAD4SuBwAAiYQk"
    . "mAAAAESJ4EmJ1EyJ+kyJhCSAAAAASYnfRIlcJGhIiawkiAAAAESJjCSQAAAAibwknAAAAEyJVCRwZg8fRAAASIu8JNABAABJiclIiUwkYGZFD+/bi2wkeESLbCRo80QPfjXJ"
    . "EwAAZg8fhAAAAAAARYX2D444BgAAg/gPD4Z+DwAASItcJEhMiclJifhmRQ/vyWZFD+/tTo0UC/MPbxFmQQ9vz2ZBD2/HZkEPb/fzRA9vURBmQQ9v32ZBD2/vSIPBQPMPb2Hg"
    . "Zg/bymYPcdIISYPAQPNED29B8GZBD9vCZg9nyGZBD2/H80EPb3jQZg/b9GZBD3HSCGZBD9vAZg9n8GYPcdQI80EPb0DAZg/b72YPcdcIZkEPZ9JmQQ/b12YP29hmQQ9x0Ahm"
    . "D2fd80UPb2DwZg9x0AhmQQ9n4GZBD9vnZg9n1GYPZ8fzQQ9vYOBmQQ/bx2ZFD9vn80EPb3jwZg9x1AjzQQ9vaOBJOcpmD3HXCGYPZ+dmQQ/b52YPZ8RmD9rCZg90wmYPb+Zm"
    . "D2/RZkEP2+9mD3HUCGZBD2fsZg9v/WZBD9v3Zg9x0ghmQQ/bz2ZBD9vvZg9nzmYPZ9RmD2/jZg9x1whmD+/2Zg9x1AhmQQ/b32YPZ91mD9rZZg9n52YP2uJmD3TLZg901GYP"
    . "28JmD9vBZg/bBUISAABmD2/IZg9oxmYPb9BmD2DOZkEPacVmQQ9h1WYP/sJmD2/RZkEPac1mQQ9h1WYP/spmD/7BZkQP/sgPhV7+//9mQQ9vwWZBD2/5i3QkVGYPc9gIi1wk"
    . "WE+NFCFOjRwnZkEP/sFmD2/IZg9z2QRmD/7BZg9+wUEPEsFmD/74Zg/WfCQ4QYnAQSnwQYP4Bw+GQQIAAEjB5gJmQQ9vzmZBD2/GSY0MMWZFD2/GSAH+8w9+GWZBD2/mZkEP"
    . "b/5mRQ9v7vNED35hCEGD4PjzD35xEGYP28tmD3HTCEQpw/MPflEYZkEP28RmD2fIZkEPcdQIZkEPb8bzRA9+VghmRA/bxmZBD2fcZg/bwmZED2/iZkQPZ8DzD34G8w9+bhBm"
    . "QQ9x1AhmQQ/b+mYPcNsI80QPfk4YZg9x1ghmD9vgZkEP295mD2fnZkEPZ/RmQQ9v/mZED2/jZg9v2GYP2/1mRQ/b6WZBD3HSCGYPcdMIZg9wyQhmRQ9wwAhmD2/BZg9x1Qhm"
    . "QQ9n2mYPcNsIZkEP295mQQ9x0QhmD3DkCGZBD2f9RInGZkEPZ+lmD3DtCGZBD9vuZg9n3WZBD2/oZg9x0AhmD3D/CGYPcPYIZg9x1QhmQQ/b9mZED2fmZg9v92YPZ8VmD2/s"
    . "Zg9x1ghmRQ9w5AhmD3HVCGYPcMAIZkEP2/5mD3DbCGYPZ+5mQQ/a3GYPcO0IZkEP285mD9roZkUP28ZmQQ/b5mZBD2fIZg9n52YPcMkIZg9w5AhmD9rhZg90xWYP7/bzD349"
    . "+g8AAEjB5gJmD3TM8w9+bCQ4SQHySQHzZkEPdNxmD9vYZg/by2YP289mD2/BZg9gxmYPYM5mD2/gZg9wyU5mD2/ZZkEPYeNmQQ9hw2ZBD2HLZg9wwE5mQQ9h22YP/sRmD3DJ"
    . "TmYP/svzD358JEBmD/7BZg/+xWYPb8hmDzgADYsPAABmD+vPZg/+wWYPfsFBD7ZyAkE4cwJBD7ZyAUEPk8BBOHMBQA+TxkQhxkUPtgJFOANBD5PARQ+2wEEh8EQBwYP7AQ+E"
    . "nAEAAEEPtnIGQThzBkEPtnIFQQ+TwEE4cwVAD5PGRCHGRQ+2QgRFOEMEQQ+TwEUPtsBBIfBEAcGD+wIPhF8BAABBD7ZyCkE4cwpBD7ZyCUEPk8BBOHMJQA+TxkQhxkUPtkII"
    . "RThDCEEPk8BFD7bAQSHwRAHBg/sDD4QiAQAAQQ+2cg5BOHMOQQ+2cg1BD5PAQThzDUAPk8ZEIcZFD7ZCDEU4QwxBD5PARQ+2wEEh8EQBwYP7BA+E5QAAAEEPtnISQThzEkEP"
    . "tnIRQQ+TwEE4cxFAD5PGRCHGRQ+2QhBFOEMQQQ+TwEUPtsBBIfBEAcGD+wUPhKgAAABBD7ZyFkE4cxZBD7ZyFUEPk8BBOHMVQA+TxkQhxkUPtkIURThDFEEPk8BFD7bAQSHw"
    . "RAHBg/sGdG9BD7ZyGkE4cxpBD7ZyGUEPk8BBOHMZQA+TxkQhxkUPtkIYRThDGEEPk8BFD7bAQSHwRAHBg/sHdDZBD7ZaHkE4Wx5BD7ZaHUEPk8BBOFsdD5PDQSHYQQ+2WhxF"
    . "MdJBOFscQQ+TwkUhwkQB0Q8fQABJAdFIAddBKc1NAflEKfV0CUQ57Q+Nrvn//0WF7UiLTCRgD45mCQAASIPBBEg5TCRwD4Nh+f//TIn7RItcJGhJiddMieJMi4QkgAAAAEGJ"
    . "xEiLrCSIAAAARIuMJJAAAACLvCScAAAAi4QkmAAAAEyLVCRwQYPBAUkB6EkB6kE5+Q+Oufj//zHJDxC0JMAAAABIicgPELwk0AAAAEQPEIQk4AAAAEQPEIwk8AAAAEQPEJQk"
    . "AAEAAEQPEJwkEAEAAEQPEKQkIAEAAEQPEKwkMAEAAEQPELQkQAEAAEQPELwkUAEAAEiBxGgBAABbXl9dQVxBXUFeQV/DSIPBBEk5yg+Cb////4P4Y3/uRYnd6YIIAABIi4wk"
    . "0AEAAA+2UQIPtkkBweIQweEICcpIi4wk0AEAAA+2CQnKgcoAAAD/hf9BidQPiD////9JY85IicJFieBmRQ/v9kgpymZBD2/u80QPbz0iDAAARImcJIAAAABIjTSVAAAAAItU"
    . "JHhmDzgALTUMAABmD9ZsJEBIjSwzSIm0JJAAAABBjXb/QYn0hdIPlcFEOdoPncJIweACRTHSIdFIiYQkuAAAAInwifpBic3B6ASJ8YPh8EjB4AZIie9EiKwkiAAAAEiJRCRY"
    . "ichEidVMjTyFAAAAAESJ8IlMJFQpyIlEJEiJ8EiJ3kyJ+0iNBIUEAAAASImEJLAAAABIOfdIifEPghwHAABEicBFieVMi6QksAAAAESIRCRwD7bEiawknAAAAIlEJHxEicDB"
    . "6BBEiYQkoAAAAIiEJJgAAACJlCSkAAAASIl8JGBIibQkqAAAAA8fRAAASItEJGBED7aMJJgAAABED7ZEJHwPtlQkcEgpyEjB+AKDwAGJRCQg6LTg//9IhcBIicEPhG8GAACA"
    . "vCSIAAAAAESLvCSAAAAAD4RBBgAASIu0JNABAABJicNIiUQkaGZFD+/bi2wkeESLvCSAAAAATIuMJJAAAADzRA9+NaAKAABFhfYPjvAFAABBg/0PD4Z4BgAASItMJFhIifBM"
    . "idpmRQ/vyWZFD+/tSAHx8w9vAmZBD2/XZkEPb89mQQ9v3/MPb3oQZkEPb/dmRQ9v50iDwEDzD29qIGYP29BmD3HQCEiDwkBmD9vPZg9n0fMPb0rwZg9x1wjzRA9vUNBmQQ/b"
    . "72YPZ8dmQQ/bx2ZBD9vPZg9n6fMPb0jA8w9vYOBmQQ/b8mZBD3HSCPNED29A8GYP29lmD2feZkEPb/dmD9v0Zg9x0QjzD2968GZFD9vgZg9x1AhmQQ9nymZBD9vPZkEPcdAI"
    . "ZkEPZ/RmQQ9n4GZBD9vnZg9nzPMPb2LgZg9x1whIOcFmD3HUCGYPZ+dmQQ/b52YPZ8RmD9rIZg90wWYPb+ZmD2/LZkEP2/dmD3HUCGYPb/1mQQ/b32ZBD9vvZg9x0QhmD2fe"
    . "Zg9nzGYPb+JmD3HXCGZBD9vXZg9x1AhmD2fVZg/a2mYP7+1mD2fnZg/azGYPdNNmD3ThZg/bxGYP28JmD9sFKAkAAGYPb8hmD2DNZg9v0WYPaMVmQQ9hzWZBD2nVZg/+ymYP"
    . "b9BmQQ9hxWZBD2nVZg/+wmYP/shmRA/+yQ+FZP7//2ZBD2/BZkEPb/mLfCRUZg9z2AhEi1QkSEmNDBtMjQQeZkEP/sFmD2/IZg9z2QRmD/7BZg9+wEEPEsFmD/74Zg/WfCQ4"
    . "RInqKfqD+gcPhj8CAABIwecCZkEPb85mQQ9vxkmNBDtmRQ9vxkgB9/MPfhBmQQ9v3mZBD2/+g+L480QPfmAIZkUPb+5BKdLzD35oGGYP28pmD3HSCPMPfnAQZkEP28RmD2fI"
    . "ZkEPcdQIZkEPb8ZmQQ9n1PNED35XCGZED2/lZg/bxWZED9vGZg/v7WZED2fA8w9+B2YPcdYIZkEP2/pmD3DSCPMPfmcQZkEPcdQIZkEP29ZmD3DJCPNED35PGGYP29hmD2ff"
    . "iddmQQ9n9GZBD2/+SMHnAmZED2/iZg9v0GYP2/xmD2/BZkUP2+lmD3HSCGZFD3DACGYPcNsIZkEPZ/1mD3HUCGYPcP8IZg9w9ghmQQ/b9mYPcdAIZkQPZ+ZmD2/3ZkEP285m"
    . "D3HWCGZFD3DkCEgB+UkB+GZBD3HSCGZBD9v+ZkEPcdEIZkEPZ9JmD3DSCGZBD9vWZkEPZ+FmD3DkCGZBD9vmZg9n1GZBD2/gZg9w0ghmRQ/bxmZBD9rUZg9x1AhmQQ9nyGYP"
    . "cMkIZg9nxGYPb+NmD3DACGZBD9veZg9x1AhmD2ffZg9w2whmD9rZZg9n5mYPcOQIZg/a4GYPdMtmD3TE8w9+fCRA8w9+Nc8GAABmQQ901GYP29BmD9vKZg/bzmYPb8FmD2DF"
    . "Zg9gzWYPb9hmD3DJTmYPb9FmQQ9h22ZBD2HDZkEPYctmD3DATmZBD2HTZg/+w2YPcMlOZg/+yvMPfmwkOGYP/sFmD/7FZg9vyGYPOAANdAYAAGYP689mD/7BZg9+wA+2UQJB"
    . "OFACD7Z5AQ+TwkE4eAFAD5PHIdcPthFBOBAPk8IPttIh+gHQQYP6AQ+EZQEAAA+2UQZBOFAGD7Z5BQ+TwkE4eAVAD5PHIdcPtlEEQThQBA+Twg+20iH6AdBBg/oCD4QwAQAA"
    . "D7ZRCUE4UAkPtnkKD5PCQTh4CkAPk8ch1w+2UQhBOFAID5PCD7bSIfoB0EGD+gMPhPsAAAAPtlENQThQDQ+2eQ4Pk8JBOHgOQA+TxyHXD7ZRDEE4UAwPk8IPttIh+gHQQYP6"
    . "BA+ExgAAAA+2URJBOFASD7Z5EQ+TwkE4eBFAD5PHIdcPtlEQQThQEA+Twg+20iH6AdBBg/oFD4SRAAAAD7ZRFUE4UBUPtnkWD5PCQTh4FkAPk8ch1w+2URRBOFAUD5PCD7bS"
    . "IfoB0EGD+gZ0YA+2URpBOFAaD7Z5GQ+TwkE4eBlAD5PHIdcPtlEYQThQGA+Twg+20iH6AdBBg/oHdC8PtlEeQThQHg+2eR0PtkkcD5PCQTh4HUEPk8JEIdJBOEgcD5PBD7bJ"
    . "IdEByA8fAE0B40wB5kEpx00By0Qp9XQJRDn9D432+f//SItMJGhFhf8PjrUAAABIg8EESDlMJGAPg1n5//+LrCScAAAARYnsRIuEJKAAAACLlCSkAAAASIt8JGBIi7QkqAAA"
    . "AEiLhCS4AAAAg8UBSAHGSAHHOdUPjr/4///pM/f//w8fRAAASMdEJDgAAAAARInzMfYxyUmJ+02Jyull8v//SMdEJDgAAAAARYnyMf8xwEmJ8EyJ2ell+///RItcJGhIg7wk"
    . "+AEAAAAPhOb2//9Ii4Qk+AEAAEUp60SJGOnT9v//SIO8JPgBAAAARIucJIAAAAAPhLz2//9Ii5wk+AEAAESJ2EQp+IkD6af2//8PH4AAAAAAVVdWU0iB7IgAAABIi6wk0AAA"
    . "AEiLtCTYAAAAZg9uhCTgAAAARIuUJPAAAABIhe1mSA9uzWZID27RSIucJAABAABmSA9u5g+UwEiF9mZID27qSYnLZg9szA+UwWYPbqQk6AAAAGZBD27YZg9s1QjIZkEPbulm"
    . "D2LEZg9i3Q+FDgEAAEiF0g+EBQEAADHAuQkAAACLlCTgAAAAD6+UJOgAAABIjXwkIPNIq4uEJPgAAABmD9ZEJGBMjUQkIA8RVCQ4Zg9u4mYP1lwkSA8RTCRQhcAPlcBBgPpk"
    . "xwcAAAAAD5TBRIhUJGhFD77SCcgPtk4BRA+v0g+2wA+2VQFmD27AZg9ixGYP1kQkbEljwkHB+h9IacAfhetRweIIweEISMH4JUQp0IlEJHQPtkUCweAQCdAPtlUACdAPtlYC"
    . "Zg9uwMHiEAnKD7YOCcpMidmBygAAAP9mD27qZg9ixUiNFQ/Z//9mD9ZEJHhB/5PQAAAASIXbdAaLRCQwiQNIi0QkKEiBxIgAAABbXl9dw2YPH0QAADHASIHEiAAAAFteX13D"
    . "ZpBWU0yLVCQ4i3QkYEiFyQ+EtAAAAE2F0g+EqwAAAItEJEhFMdtECcALRCRACdAPiIoAAACLRCRYhcAPjokAAACF9g+OgQAAAEUPr8FIY9JNY8lKjRyNAAAAAEljwEgB0Ehj"
    . "VCRATI0EgYtEJEgPr0QkUEiYSAHQSY0MgkhjRCRQRItUJFhMjQyFAAAAAA8fQAAxwGYPH0QAAIsUgUGJFIBIg8ABSTnCdfBBg8MBSQHYTAHJRDnef9lBuwEAAABEidhbXsMP"
    . "H0QAAEUx20SJ2Ftew2ZmLg8fhAAAAAAADx9AAEiD7HhMi5wkqAAAAEiF0kiJyA+E6AAAAE2F2w+E3wAAAIuMJLgAAABFMdJECckLjCSwAAAARAnBD4i6AAAARIuUJMgAAABF"
    . "hdIPjrEAAACLjCTQAAAAhckPjqIAAABmSA9u0ouUJKAAAABmSA9uwGZBD27ZZg9swg8RRCQoSInBZkEPbsBmD2LDZg/WRCQ4Zg9ujCTAAAAATI1EJCBmD26kJMgAAADHRCQg"
    . "AAAAAGYPboQksAAAAIlUJECLlCTQAAAAZg9izEyJXCRIZg9urCS4AAAAZg9ixWYPbMEPEUQkUIlUJGBIjRU01f///5DQAAAAQboBAAAARInQSIPEeMNFMdJEidBIg8R4ww8f"
    . "RAAAMcDDZmYuDx+EAAAAAABmkP8A/wD/AP8A/wD/AP8A/wABAQEBAQEBAQEBAQEBAQEBBAUGB4CAgICAgICAgICAgICAgIAAAQIDgICAgICAgIA="
    mcode_imgutil_column_uniform := 0x0012e0 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x001400 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_make_sat_masks := 0x0014b0 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x001510 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x002760 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x002900 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x0029e0 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x002af0 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    }

    ;############################################################################################################
    ; -march=x86-64 baseline optimized machine code blob
    ;############################################################################################################
    i_get_mcode_map_v1() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 5568 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64 -D MARCH_x86_64_v1 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "QVZVV1ZTSYnLi0lASYtDCEGLazgPr9FBi3MgRIuIyAAAAEGJ0InQMdJB9/Ex0kGJwkKNBAFJY0swQffxQYtTNEQB0g+v1Uhj0kgBykmLSyhMjQSRQYtTHEljSxhEAdIPr9ZI"
    . "Y9JIAcpJi0sQTI0MkUE5wg+N1QAAAA8fgAAAAABBi1s8g/sDD47LAAAAjWv8MdKJ7sHuAo1OAUjB4QRmkPNBD28EEEEPEQQRSIPCEEg50XXs995JjTwJTAHBjVS1AEGLazhB"
    . "i3MghdJ0HkSLMUSJN4P6AXQTRItxBESJdwSD+gJ0BotRCIlXCEhj1UhjzkGDwgFIweICSMHhAkkB0EkByUQ50HRGg/sDD49v////RYtbPA8fAEWF23QiQYsYQYkZQYP7AXQW"
    . "QYtYBEGJWQRBg/sCdAhBi1gIQYlZCEGDwgFJAdBJAclEOdB/ylteX11BXsMPHwCJ2kyJz0yJwelk////ZmYuDx+EAAAAAABBV0FWQVVBVFVXVlNIg+xIDxF0JDAxwGYPdsm6"
    . "AQAAAPAPwRFEi0EsRCtBREE50A+MwAUAAExjaShMi0kgQQ+v1Uhj0kmNFJFEi0lATWPBTSnFRItBTEnB5QJOjTwqRYXAD4QJAwAASTnXcq9FjVH88w9vYWDzD29ZcEWJ0EHB"
    . "6AJFjWABQffYR400gknB5ARBicAPH0QAAEyJ+Egp0EjB+AKDwAGD+AN/FukhAgAAkIPoBEiDwhCD+AMPjhACAADzD28CZg9v7GYPb9NmD97QZg/e6GYPdMVmD3TTZg/bwmYP"
    . "dsFmRA/X0EWF0nTC80UPvNJBwfoCSWPCSI0Ugot5VItxUEiLWTBMi1k4OfcPjw0CAABIidCJ/YX2D4QAAgAAiXwkCEiJVCQQZg8fRAAARTHSMdJBg/kDD46JAQAAiWwkKA8f"
    . "RAAA80IPbwQQ80IPbxQT80MPbywTZg/e0GYP3uhmD3TC80MPbxQTSYPCEGYPdNVmD9vCZg92wWYP1+iJ72bR72aB51VVKf2J72bB7QJmgeczM2aB5TMzAf2J72bB7wQB72aB"
    . "5w8Pif1mwe0IAe9mwe8Cg+cHAfpNOdR1h4tsJChMAeNNAeNMAeBFifJFhdIPhLUAAABmD24oZkEPbjNmD24TZg9vxWYP3tVmD97GZg901WYPdMZmD9vCZg92wWYP1/iD5wEB"
    . "+kGD+gF0cGYPbmgEZkEPbnMEZg9uUwRmD2/FZg/e1WYP3sZmD3TVZg90xmYP28JmD3bBZg/X+IPnAQH6QYP6AnQ1ZkEPblMIZg9uQAhmD25rCGYPb/JmD97oZg/e8GYPdMVm"
    . "D3TWZg/bwmYPdsFmD9f4g+cBAfpJweICTAHTTQHTTAHQKdVMAehEKc50CDn1D46P/v//i3wkCEiLVCQQhe1+eUiDwgRJOdcPg939//9EicDpWP3//w8fRAAARYnK6QH///+F"
    . "wHTnTI0Ugg8fhAAAAAAAZg9uAmYPb+xmD2/TZg/e0GYP3uhmD3TFZg9002YP28JmD3bBZg/XwKgBD4Xu/f//SIPCBEw50nXHRInA6fr8//+J/YXtf4eJ+CnoTI1BFEG6AQAA"
    . "AEWJ0UWGCEWEyXX1OUEQD43CAgAAiUEQSIlRCEWGCDtBUA+Mv/z//4tRLIcR6bX8//9mLg8fhAAAAAAASTnXD4IyAgAASItxMIt5UESLUVRMi2E4SIl0JBhBjXH8QTn6QYn2"
    . "D57Dhf9BD5XDQcHuAkWJ8EGNbgFB99hIweUERo00hkSE2w+EEgIAAESJVCQQTYngiUQkLEiJjCSQAAAADx9EAABIiVQkCEyLVCQYSInQTYnDRItkJBCJ+0yJxmYPH0QAAEUx"
    . "wDHJRInKQYP5Aw+OoAAAAESJZCQokPNCD28EAPNDD28UAvNDD28cA2YP3tBmD97YZg90wvNDD28UA0mDwBBmD3TTZg/bwmYPdsFmRA/X4ESJ4mbR6maB4lVVQSnURIniZkHB"
    . "7AJmgeIzM2ZBgeQzM0EB1ESJ4mbB6gREAeJmgeIPD0GJ1GZBwewIRAHiZsHqAoPiBwHRTDnFD4V3////RItkJChJAepJAetIAehEifKF0g+EvwAAAGYPbhhmQQ9uI2ZBD24S"
    . "Zg9vw2YP3tNmD97EZg9002YPdMRmD9vCZg92wWZED9fAQYPgAUQBwYP6AXR3Zg9uWARmQQ9uYwRmQQ9uUgRmD2/DZg/e02YP3sRmD3TTZg90xGYP28JmD3bBZkQP18BBg+AB"
    . "RAHBg/oCdDlmQQ9uUwhmD25ACGZBD25aCGYPb+JmD97YZg/e4GYPdMNmD3TUZg/bwmYPdsFmRA/XwEGD4AFEAcFIweICSQHSSQHTSAHQQSnMTAHoRCnLdAlBOdwPjnP+//9I"
    . "i1QkCEmJ8EWF5H5JSIPCBEk51w+DOf7//4tEJCxIi4wkkAAAAEiDfCQgAA+EZPr//0iLVCQg6Wr9//8PH4AAAAAASIPCBEk513LaRYXSf/JFidTrDUSLVCQQSIuMJJAAAABE"
    . "idBIiVQkIEQp4Ou2DxB0JDBIg8RIW15fXUFcQV1BXkFfw0WGCDlBUA+PBPr//+lA/f//Dx9AAFdWU4tcJEhEichIY/JIY1QkQEWJyA+2xEHB6BBBicKLRCRYD6/GSJhIAdBM"
    . "jRyBi0QkUA+vxkiYSAHQSI0UgUw52nNsRQ+2wEUPttJFD7bJg/4BdBTraWYPH4QAAAAAAEiDwgRMOdpzRw+2SgFEKdGJyPfYD0jBD7ZKAkQpwYnO994PSc45yA9MwQ+2CkQp"
    . "yYnO994PSc45yA9MwTnDfcAxwFteX8NmLg8fhAAAAAAAuAEAAABbXl/DDx+AAAAAAEjB5gLrEmYuDx+EAAAAAABIAfJMOdpz2A+2SgJEKcGJyPfYD0jBD7ZKAUQp0YnP998P"
    . "Sc85yA9MwQ+2CkQpyYnP998PSc85yA9MwTnDfcExwOuPZmYuDx+EAAAAAABmkFZTD69UJDiLXCRASGPSSInOSGNMJFBEichFicoPtsRBweoQSAHRTI0cjkhjTCRISAHKSI0U"
    . "lkw52nNdRQ+20kQPtsBFD7bJ6xAPH4AAAAAASIPCBEw52nM/D7ZKAkQp0YnI99gPSMEPtkoBRCnBic733g9JzjnID0zBD7YKRCnJic733g9JzjnID0zBOcN9wDHAW17DDx8A"
    . "uAEAAABbXsNEi1QkKE2FwInQD5TCTYXJQQ+Uw0QI2g+F4QAAAEiFyQ+E2AAAAEUPttJBadIAAQEARAnSgcoAAAD/Zg9u4mYPcNwAg/gDflREjVj8Zg9vyzHARYnaQcHqAkGN"
    . "UgFIweIEDx+AAAAAAPMPbwQBZg9v0GYP3MFmD9jRQQ8RBAFBDxEUAEiDwBBIOcJ13EH32kgB0UkB0UkB0EONBJOFwHReZg9uAWYPb8hmD9zDZg/Yy2ZBD34BZkEPfgiD+AF0"
    . "P2YPbkEEZg9vyGYP3MNmD9jLZkEPfkEEZkEPfkgEg/gCdB1mD25JCGYPb8FmD9jDZg/c2WZBD35ACGZBD35ZCDHAw2ZmLg8fhAAAAAAADx9AAEFXQVZBVUFUVVdWU0iD7GgP"
    . "EXQkQA8RfCRQi7Qk4AAAAIucJOgAAABNhclFicJNictIichBD5TAi4wk2AAAAEiDvCTQAAAAAEEPlMFFCMgPhREDAABIhcAPhAgDAABBic9ED77DRA+v/kUPr8dNY8hEicdN"
    . "ackfhetRwf8fScH5JUEp+UWJzkWJ0USLlCTwAAAAQSnxRYXSD4X+AgAAgPtkD4T1AgAARYXJD4i2AgAASGPSTGPRTImcJMgAAABFifNJidRIjTyVAAAAAEiJwk0p1EiJfCQY"
    . "Zg925EnB5AJFhf8PlcNFOfdKjTQgTIu0JMgAAABBD53CRCHTRI1R/ESJ0MHoAo14AffYRY0sgonYSMHnBESJw0Ux0kGJwEiJ0Eg51g+CJQIAAEWEwA+EWgIAAESJfCQMiVwk"
    . "OESJXCQIRIlUJCBEiEQkKEiJdCQQSIlUJDBEiUwkPA8fgAAAAACLXCQMi2wkCEiJwk2J8UyLlCTQAAAAZi4PH4QAAAAAADH2RTHbQYnIg/kDD46jAAAADx+AAAAAAPMPbwQy"
    . "80EPbwwx80EPbxQyZg/eyGYP3tBmD3TB80EPbwwySIPGEGYPdMpmD9vBZg92xGZED9f4RYn4ZkHR6GZBgeBVVUUpx0WJ+GZBwe8CZkGB4DMzZkGB5zMzRQHHRYn4ZkHB6ARF"
    . "AfhmQYHgDw9FicdmQcHvCEUB+GZBwegCQYPgB0UBw0g5/g+FcP///0kB+UkB+kgB+kWJ6EWFwA+EwAAAAGYPbhJmQQ9uGmZBD24JZg9vwmYP3spmD97DZg90ymYPdMNmD9vB"
    . "Zg92xGYP1/CD5gFBAfNBg/gBdHlmD25SBGZBD25aBGZBD25JBGYPb8JmD97KZg/ew2YPdMpmD3TDZg/bwWYPdsRmD9fwg+YBQQHzQYP4AnQ8ZkEPbkoIZg9uQghmQQ9uUQhm"
    . "D2/ZZg/e0GYP3thmD3TCZg90y2YP28FmD3bEZg/X8IPmAUEB8w8fRAAAScHgAk0BwU0BwkwBwkQp3UwB4inLdAg53Q+Ocf7//4XtD44lBAAASIPABEg5RCQQD4M6/v//RIt8"
    . "JAyLXCQ4RItcJAhEi1QkIEQPtkQkKEiLdCQQSItUJDBEi0wkPEiLRCQYQYPCAUgBwkgBxkU5yg+Ot/3//zHADxB0JEAPEHwkUEiDxGhbXl9dQVxBXUFeQV/DSIPABEg5xnLC"
    . "g/tjf/JFid5Eid3ppQMAAEUPtkMCRQ+2UwFIi5wk0AAAAEHB4ghBweAQRQnQRQ+2E0UJ0EQPtlMBZkEPbthED7ZDAkHB4ghmD3DbAEHB4BBFCdBED7YTRQnQQYHIAAAA/2ZB"
    . "D27gZg9w5ABFhckPiGb///9IY9JMY8FmD3bSSYnUTSnEScHkAkWF/0EPlcJFOfdKjTQgQQ+dwEUhwkmJwESIVCQYTI0UlQAAAACNUfyJ0MHoAo1oAffYRI0sgkjB5QQx0kyJ"
    . "wGYPb8xMOcYPgn0CAACJVCQ4TIlEJCBMiVQkKESJTCQwDx9EAABIifJIKcJIwfoCg8IBg/oDfxbpZQIAAJCD6gRIg8AQg/oDD45UAgAA8w9vAGYPb/NmD2/pZg/e6GYP3vBm"
    . "D3TGZg906WYP28VmD3bCZkQP18BFhcB0wvNFD7zAQcH4Aklj0EiNBJCAfCQYAESJ9w+EyQEAAESJfCQISInCTYnZRIn7RIl0JAxMi5Qk0AAAAEiJdCQQDx9AAEUx9jH2QYnI"
    . "g/kDD46kAAAADx+AAAAAAPNCD28EMvNDD28sMfNDD280MmYP3uhmD97wZg90xfNDD28sMkmDxhBmD3TuZg/bxWYPdsJmRA/X+EWJ+GZB0ehmQYHgVVVFKcdFifhmQcHvAmZB"
    . "geAzM2ZBgeczM0UBx0WJ+GZBwegERQH4ZkGB4A8PRYnHZkHB7whFAfhmQcHoAkGD4AdEAcZJOe4PhW////9JAelJAepIAepFiehFhcAPhMcAAABmD24yZkEPbjpmQQ9uKWYP"
    . "b8ZmD97uZg/ex2YPdO5mD3THZg/bxWYPdsJmRA/X8EGD5gFEAfZBg/gBdH5mD25yBGZBD256BGZBD25pBGYPb8ZmD97uZg/ex2YPdO5mD3THZg/bxWYPdsJmRA/X8EGD5gFE"
    . "AfZBg/gCdD9mQQ9uaghmD25CCGZBD25xCGYPb/1mD97wZg/e+GYPdMZmD3TvZg/bxWYPdsJmRA/X8EGD5gFEAfZmDx9EAABJweACTAHCTQHBTQHCKfdMAeIpy3QIOd8Pjmr+"
    . "//9Ei3wkCESLdCQMSIt0JBCF/w+OpgAAAEiDwARIOcYPg679//+LVCQ4TItEJCBMi1QkKESLTCQwg8IBTQHQTAHWRDnKD45h/f//6XL8//+F0nTSTI0EkA8fQABmD24AZg9v"
    . "82YPb+lmD97oZg/e8GYPdMZmD3TpZg/bxWYPdsJmD9fQg+IBD4Wt/f//SIPABEw5wHXG645Ei3QkCEiDvCT4AAAAAA+EGPz//0iLnCT4AAAAQSnuRIkz6QX8//9Ig7wk+AAA"
    . "AAAPhPb7//9Ii5wk+AAAAESJ8in6iRPp4vv//2YuDx+EAAAAAABBVUFUVVdWU0iB7KgAAABIi7QkAAEAAEyLnCQIAQAAi6wkEAEAAESLrCQYAQAASIX2SIucJDABAAAPlMBN"
    . "hdtJicoPlMFJidSLlCQgAQAACMgPhREBAABNheQPhAgBAAAxwEiNfCQguQwAAADzSKuLhCQoAQAAiWwkYIhUJGiFwESJRCRITI1EJCAPlcCA+mQPvtJMiVQkOA+UwUEPr+1M"
    . "iWQkQAnIRIlMJExMidEPtsBIiXQkUA+v1YlEJGxMiVwkWESJbCRkSGPCwfofiWwkcEhpwB+F61FIwfglKdAPtlYBiUQkdA+2RgLB4gjB4BAJ0A+2FgnQQQ+2UwFmD27IQQ+2"
    . "QwLB4ghmD3DBAMHgEA8RhCSAAAAACdBBD7YTCdBIjRVZ7v//DQAAAP9mD27QZg9wwgAPEYQkkAAAAEH/ktAAAABIhdt0BotEJDCJA0iLRCQoSIHEqAAAAFteX11BXEFdww8f"
    . "QAAxwEiBxKgAAABbXl9dQVxBXcNmDx9EAABBVkFUVVdWU0yLVCRYi1wkeIu0JIAAAABIhckPhP8AAABNhdIPhPYAAACLRCRoRTHbRAnAC0QkYAnQD4jQAAAAhdsPjtgAAACF"
    . "9g+O0AAAAEUPr8FIY9JNY8lIY3wkcEqNLI0AAAAARI1L/EjB5wJJY8BIAdBIY1QkYEiNDIGLRCRoD69EJHBImEgB0EmNFIJEicjB6AJEjUAB99hJweAERY0kgQ8fQAAxwIP7"
    . "Aw+OfQAAAA8fRAAA8w9vBAIPEQQBSIPAEEw5wHXuSo0EAk6NFAFFheR0JEWJ4USLMEWJMkGD+QF0FUSLcARFiXIEQYP5AnQHi0AIQYlCCEGDwwFIAelIAfpEOd5/nkG7AQAA"
    . "AESJ2FteX11BXEFeww8fQABFMdtEidhbXl9dQVxBXsOQQYnZSYnKSInQ658PH0QAAEiD7HhMi5wkqAAAAEiJyEiF0g+E2AAAAE2F2w+EzwAAAIuMJLgAAABFMdJECckLjCSw"
    . "AAAARAnBD4inAAAARIuUJMgAAABFhdIPjqEAAACLjCTQAAAAhckPjpIAAABIiVQkMIuUJKAAAABIicFmD26MJMAAAABEiUQkOEyNRCQgZg9ulCTIAAAAiVQkQGYPboQksAAA"
    . "AIuUJNAAAADHRCQgAAAAAGYPbpwkuAAAAGYPYspIiUQkKIlUJGBIjRWO6v//Zg9iw0SJTCQ8Zg9swUyJXCRIDxFEJFD/kNAAAABBugEAAABEidBIg8R4ww8fAEUx0kSJ0EiD"
    . "xHjDDx9EAAC4AQAAAMOQkJCQkJCQkJCQ"
    mcode_imgutil_column_uniform := 0x000790 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x0008b0 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_make_sat_masks := 0x000950 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000a60 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x0011f0 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x001370 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x0014b0 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x0015b0 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                   
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    }

    ;############################################################################################################
    ; -march=x86-64-v2 optimized SSE4 machine code blob
    ;############################################################################################################
    i_get_mcode_map_v2() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 5280 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64-v2 -D MARCH_x86_64_v2 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "QVZVV1ZTSYnLi0lASYtDCEGLazgPr9FBi3MgRIuIyAAAAEGJ0InQMdJB9/Ex0kGJwkKNBAFJY0swQffxQYtTNEQB0g+v1Uhj0kgBykmLSyhMjQSRQYtTHEljSxhEAdIPr9ZI"
    . "Y9JIAcpJi0sQTI0MkUE5wg+N1QAAAA8fgAAAAABBi1s8g/sDD47LAAAAjWv8MdKJ7sHuAo1OAUjB4QRmkPNBD28EEEEPEQQRSIPCEEg50XXs995JjTwJTAHBjVS1AEGLazhB"
    . "i3MghdJ0HkSLMUSJN4P6AXQTRItxBESJdwSD+gJ0BotRCIlXCEhj1UhjzkGDwgFIweICSMHhAkkB0EkByUQ50HRGg/sDD49v////RYtbPA8fAEWF23QiQYsYQYkZQYP7AXQW"
    . "QYtYBEGJWQRBg/sCdAhBi1gIQYlZCEGDwgFJAdBJAclEOdB/ylteX11BXsMPHwCJ2kyJz0yJwelk////ZmYuDx+EAAAAAABBV0FWQVVBVFVXVlNIg+xIDxF0JDAx0mYPdslI"
    . "iciJ0UG4AQAAAPBED8EAi1AsK1BERDnCD4wyBQAATGNgKESLUEBMi0ggRQ+vxElj0kkp1ItQTEnB5AJNY8BPjQSBT400IIXSD4TWAgAATTnGcrFFjUr88w9vYGBBic9NifNE"
    . "icrzD29YcMHqAo1qAffaSMHlBEWNLJFmLg8fhAAAAAAATInaTCnCSMH6AoPCAYP6A38e6fEBAABmDx+EAAAAAACD6gRJg8AQg/oDD47YAQAA80EPbwBmD2/sZg9v02YP3tBm"
    . "D97oZg90xWYPdNNmD9vCZg92wWYP18iFyXTD8w+8ycH5Akhj0U2NBJBEi0hURItwUEiLcDBIi1g4RTnxD4/PAQAATInBRInPRYX2D4TAAQAARIlMJAhMiUQkEA8fADHSRTHA"
    . "QYP6Aw+OUQEAAJDzD28EEfMPbxQW8w9vLBNmD97QZg/e6GYPdMLzD28UE0iDwhBmD3TVZg/bwmYPdsFmRA/XyPNFD7jJQcH5AkUByEg51XW6SAHuSAHrSAHpRInqhdIPhLkA"
    . "AABmD24pZg9uM2YPbhZmD2/FZg/e1WYP3sZmD3TVZg90xmYP28JmD3bBZkQP18hBg+EBRQHIg/oBdHNmD25pBGYPbnMEZg9uVgRmD2/FZg/e1WYP3sZmD3TVZg90xmYP28Jm"
    . "D3bBZkQP18hBg+EBRQHIg/oCdDdmD25TCGYPbkEIZg9ubghmD2/yZg/e6GYP3vBmD3TFZg901mYP28JmD3bBZkQP18hBg+EBRQHISMHiAkgB1kgB00gB0UQpx0wB4UUp1nQJ"
    . "RDn3D47J/v//RItMJAhMi0QkEIX/fnVJg8AETTnDD4MO/v//RIn56Yb9//9mDx9EAABEidLp+v7//4XSdOZJjQyQZkEPbgBmD2/sZg9v02YP3tBmD97oZg90xWYPdNNmD9vC"
    . "Zg92wWYP19CD4gEPhSn+//9Jg8AESTnIdcVEifnpLf3//0SJz4X/f4tEickp+UiNUBRBugEAAABFidFEhgpFhMl19TlIEA+NZQIAAIlIEEyJQAhEhgo7SFAPjPD8//+LUCyH"
    . "EOnm/P//Zg8fRAAATTnGD4LSAQAARIt4UESLSFRBjXL8SIt4MInyRTn5SIl8JBAPnsNIi3g4RYX/QQ+Vw8HqAkiJfCQYjXoB99pIwecERI0slkSE2w+EsgEAAIlMJCxIiYQk"
    . "kAAAAA8fRAAATIlEJAhIi1wkGEyJwkSJ/kyLXCQQRInNDx+EAAAAAAAxwDHJQYP6Aw+OggEAAGaQ8w9vBALzQQ9vFAPzD28cA2YP3tBmD97YZg90wvMPbxQDSIPAEGYPdNNm"
    . "D9vCZg92wWZED9fA80UPuMBBwfgCRAHBSDnHdblJAftIAftIAfpEieiFwA+EvAAAAGYPbhpmD24jZkEPbhNmD2/DZg/e02YP3sRmD3TTZg90xGYP28JmD3bBZkQP18BBg+AB"
    . "RAHBg/gBdHVmD25aBGYPbmMEZkEPblMEZg9vw2YP3tNmD97EZg9002YPdMRmD9vCZg92wWZED9fAQYPgAUQBwYP4AnQ4Zg9uUwhmD25CCGZBD25bCGYPb+JmD97YZg/e4GYP"
    . "dMNmD3TUZg/bwmYPdsFmRA/XwEGD4AFEAcFIweACSQHDSAHDSAHCKc1MAeJEKdZ0CDn1D47H/v//TItEJAiF7X5WSYPABE05xg+Dkf7//4tMJCxIi4QkkAAAAEiDfCQgAA+E"
    . "+fr//0yLRCQg6c79//8PH4AAAAAASYPABE05xnLaRYXJf/JEic3rFQ8fRAAARInQ6cv+//9Ii4QkkAAAAESJyUyJRCQgKenrrw8QdCQwSIPESFteX11BXEFdQV5BX8NEhgo5"
    . "SFAPj5L6///pnf3//2ZmLg8fhAAAAAAAZpBXVlOLXCRIRInISGPySGNUJEBFicgPtsRBwegQQYnCi0QkWA+vxkiYSAHQTI0cgYtEJFAPr8ZImEgB0EiNFIFMOdpzbEUPtsBF"
    . "D7bSRQ+2yYP+AXQU62lmDx+EAAAAAABIg8IETDnac0cPtkoBRCnRicj32A9IwQ+2SgJEKcGJzvfeD0nOOcgPTMEPtgpEKcmJzvfeD0nOOcgPTME5w33AMcBbXl/DZi4PH4QA"
    . "AAAAALgBAAAAW15fww8fgAAAAABIweYC6xJmLg8fhAAAAAAASAHyTDnac9gPtkoCRCnBicj32A9IwQ+2SgFEKdGJz/ffD0nPOcgPTMEPtgpEKcmJz/ffD0nPOcgPTME5w33B"
    . "McDrj2ZmLg8fhAAAAAAAZpBWUw+vVCQ4i1wkQEhj0kiJzkhjTCRQRInIRYnKD7bEQcHqEEgB0UyNHI5IY0wkSEgBykiNFJZMOdpzXUUPttJED7bARQ+2yesQDx+AAAAAAEiD"
    . "wgRMOdpzPw+2SgJEKdGJyPfYD0jBD7ZKAUQpwYnO994PSc45yA9MwQ+2CkQpyYnO994PSc45yA9MwTnDfcAxwFteww8fALgBAAAAW17DRItUJChNhcCJ0A+Uwk2FyUEPlMNE"
    . "CNoPheEAAABIhckPhNgAAABFD7bSQWnSAAEBAEQJ0oHKAAAA/2YPbuJmD3DcAIP4A35URI1Y/GYPb8sxwEWJ2kHB6gJBjVIBSMHiBA8fgAAAAADzD28EAWYPb9BmD9zBZg/Y"
    . "0UEPEQQBQQ8RFABIg8AQSDnCddxB99pIAdFJAdFJAdBDjQSThcB0XmYPbgFmD2/IZg/cw2YP2MtmQQ9+AWZBD34Ig/gBdD9mD25BBGYPb8hmD9zDZg/Yy2ZBD35BBGZBD35I"
    . "BIP4AnQdZg9uSQhmD2/BZg/Yw2YP3NlmQQ9+QAhmQQ9+WQgxwMNmZi4PH4QAAAAAAA8fQABBV0FWQVVBVFVXVlNIg+xYDxF0JDAPEXwkQIu0JNAAAACLnCTYAAAATYXJTYnP"
    . "SGPCRInCQQ+UwUSLhCTIAAAASIO8JMAAAAAAQQ+UwkUI0Q+FlwIAAEiFyQ+EjgIAAEWJxkQPvssp8kQPr/ZFicpFD6/WTWPaRYnRTWnbH4XrUUHB+R9JwfslRSnLQYnRi5Qk"
    . "4AAAAIXSD4WGAgAAgPtkD4R9AgAARYXJD4g+AgAASWPQSYnEZg925Ekp1EnB5AJFhfYPlcNFOd4PncJIweACIdNIiUQkCEiJyIneSo0cIUGNSPyJysHqAo16AffaRI0skUSJ"
    . "ykjB5wRBifExyUSJ1kGJ0kiJwkg5ww+CxgEAAEWEyQ+E/QEAAESJdCQQiXQkFESJHCSJTCQoRIhMJBhIiUQkIESJVCQsDx+AAAAAAIt0JBCLLCRIidFNiflMi5QkwAAAAA8f"
    . "ADHARTHbQYP4Aw+OyQQAAGYPH4QAAAAAAPMPbwQB80EPbwwB80EPbxQCZg/eyGYP3tBmD3TB80EPbwwCSIPAEGYPdMpmD9vBZg92xGZED9fw80UPuPZBwf4CRQHzSDn4dbdJ"
    . "AflJAfpIAflEieiFwA+EwAAAAGYPbhFmQQ9uGmZBD24JZg9vwmYP3spmD97DZg90ymYPdMNmD9vBZg92xGZED9fwQYPmAUUB84P4AXR4Zg9uUQRmQQ9uWgRmQQ9uSQRmD2/C"
    . "Zg/eymYP3sNmD3TKZg90w2YP28FmD3bEZkQP1/BBg+YBRQHzg/gCdDpmQQ9uSghmD25BCGZBD25RCGYPb9lmD97QZg/e2GYPdMJmD3TLZg/bwWYPdsRmRA/X8EGD5gFFAfOQ"
    . "SMHgAkkBwUkBwkgBwUQp3UwB4UQpxnQIOfUPjrj+//+F7Q+O+QMAAEiDwgRIOdMPg4v+//9Ei3QkEIt0JBREixwki0wkKEQPtkwkGEiLRCQgRItUJCxIi1QkCIPBAUgB0EgB"
    . "00Q50Q+OF/7//zHSDxB0JDAPEHwkQEiJ0EiDxFhbXl9dQVxBXUFeQV/DSIPCBEg503LAg/5jf/JEid3pggMAAEEPtlcCRQ+2VwFIi5wkwAAAAEHB4gjB4hBECdJFD7YXRAnS"
    . "RA+2UwFmD27aSIuUJMAAAABBweIIZg9w2wAPtlICweIQRAnSRA+2E0QJ0oHKAAAA/2YPbuJmD3DkAEWFyQ+IZP///0lj0EiJxUSJdCQUZg920kgp1USJ20jB5QJFhfZBD5XC"
    . "RTneTI0sKQ+dwkEh0kGNUPxEiFQkLEyNFIUAAAAAidDB6AKNeAH32ESNJIJIwecEMcBmD2/MSTnND4IuAgAAiUQkKEQPtlwkLESJykiJTCQYTIlUJCBIiQwkDx9EAABMiwwk"
    . "TInoTCnISMH4AoPAAYP4A38a6SkCAAAPH0QAAIPoBEmDwRCD+AMPjhACAADzQQ9vAWYPb/NmD2/pZg/e6GYP3vBmD3TGZg906WYP28VmD3bCZg/XyIXJdMPzD7zJwfkCSGPB"
    . "SY0EgUiJBCSJ3kWE2w+EaQEAAEiLDCREi3QkFIlcJBBNiflEiFwkCEyLlCTAAAAAkDHARTHbQYP4Aw+OkQEAAJDzD28EAfNBD28sAfNBD280AmYP3uhmD97wZg90xfNBD28s"
    . "AkiDwBBmD3TuZg/bxWYPdsJmD9fY8w+428H7AkEB20g5+HW6SQH5SQH6SAH5RInghcAPhMMAAABmD24xZkEPbjpmQQ9uKWYPb8ZmD97uZg/ex2YPdO5mD3THZg/bxWYPdsJm"
    . "D9fYg+MBQQHbg/gBdH1mD25xBGZBD256BGZBD25pBGYPb8ZmD97uZg/ex2YPdO5mD3THZg/bxWYPdsJmD9fYg+MBQQHbg/gCdEFmQQ9uaghmD25BCGZBD25xCGYPb/1mD97w"
    . "Zg/e+GYPdMZmD3TvZg/bxWYPdsJmD9fYg+MBQQHbZi4PH4QAAAAAAEjB4AJIAcFJAcFJAcJEKd5IAelFKcZ0CUQ59g+Ov/7//4tcJBBED7ZcJAiF9g+O1AAAAEiDBCQESIsE"
    . "JEk5xQ+DA/7//4tEJChIi0wkGEGJ0UyLVCQgg8ABTAHRTQHVRDnID46z/f//6cD8//8PHwBEicDpjfv//w8fhAAAAAAARInA6br+//9MiQwkhcB0tUiLNCRIjQyGSInw6wwP"
    . "HwBIg8AESDnIdJxmD24AZg9v82YPb+lmD97oZg/e8GYPdMZmD3TpZg/bxWYPdsJmRA/XyEGD4QF0yEiJBCTp1v3//0SLHCRIg7wk6AAAAAAPhDv8//9Ii4Qk6AAAAEEp60SJ"
    . "GOko/P//SIO8JOgAAAAASIsUJEGJ2w+EEvz//0iLhCToAAAAQSnzRIkY6f/7//9BVUFUVVdWU0iB7KgAAABIi7QkAAEAAEyLnCQIAQAAi6wkEAEAAESLrCQYAQAASIX2SIuc"
    . "JDABAAAPlMBNhdtJicoPlMFJidSLlCQgAQAACMgPhREBAABNheQPhAgBAAAxwEiNfCQguQwAAADzSKuLhCQoAQAAiWwkYIhUJGiFwESJRCRITI1EJCAPlcCA+mQPvtJMiVQk"
    . "OA+UwUEPr+1MiWQkQAnIRIlMJExMidEPtsBIiXQkUA+v1YlEJGxMiVwkWESJbCRkSGPCwfofiWwkcEhpwB+F61FIwfglKdAPtlYBiUQkdA+2RgLB4gjB4BAJ0A+2FgnQQQ+2"
    . "UwFmD27IQQ+2QwLB4ghmD3DBAMHgEA8RhCSAAAAACdBBD7YTCdBIjRV57///DQAAAP9mD27QZg9wwgAPEYQkkAAAAEH/ktAAAABIhdt0BotEJDCJA0iLRCQoSIHEqAAAAFte"
    . "X11BXEFdww8fQAAxwEiBxKgAAABbXl9dQVxBXcNmDx9EAABBVkFUVVdWU0yLVCRYi1wkeIu0JIAAAABIhckPhP8AAABNhdIPhPYAAACLRCRoRTHbRAnAC0QkYAnQD4jQAAAA"
    . "hdsPjtgAAACF9g+O0AAAAEUPr8FIY9JNY8lIY3wkcEqNLI0AAAAARI1L/EjB5wJJY8BIAdBIY1QkYEiNDIGLRCRoD69EJHBImEgB0EmNFIJEicjB6AJEjUAB99hJweAERY0k"
    . "gQ8fQAAxwIP7Aw+OfQAAAA8fRAAA8w9vBAIPEQQBSIPAEEw5wHXuSo0EAk6NFAFFheR0JEWJ4USLMEWJMkGD+QF0FUSLcARFiXIEQYP5AnQHi0AIQYlCCEGDwwFIAelIAfpE"
    . "Od5/nkG7AQAAAESJ2FteX11BXEFeww8fQABFMdtEidhbXl9dQVxBXsOQQYnZSYnKSInQ658PH0QAAEiD7HhMi5wkqAAAAEiJyEiF0g+E2AAAAE2F2w+EzwAAAIuMJLgAAABF"
    . "MdJECckLjCSwAAAARAnBD4ijAAAARIuUJMgAAABFhdIPjqEAAACLjCTQAAAAhckPjpIAAABIiVQkMIuUJKAAAABIicFmD26MJMAAAABEiUQkOEyNRCQgZg86IowkyAAAAAGJ"
    . "VCRAZg9uhCSwAAAAi5Qk0AAAAEiJRCQoZg86IoQkuAAAAAHHRCQgAAAAAIlUJGBIjRWu6///Zg9swUSJTCQ8TIlcJEgPEUQkUP+Q0AAAAEG6AQAAAESJ0EiDxHjDDx+AAAAA"
    . "AEUx0kSJ0EiDxHjDDx9EAAC4AgAAAMOQkJCQkJCQkJCQ"
    mcode_imgutil_column_uniform := 0x000710 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x000830 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_make_sat_masks := 0x0008d0 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x0009e0 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x0010d0 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x001250 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x001390 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x001490 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
    
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    }

    ;############################################################################################################
    ; -march=x86-64-v3 optimized AVX2 machine code blob
    ;############################################################################################################
    i_get_mcode_map_v3() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 6016 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64-v3 -D MARCH_x86_64_v3 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "V1ZTSInLi0lASItDCA+v0USLiMgAAABBidCJ0DHSQffxMdKJx0KNBAFIY0swQffxi1M0AfoPr1M4SGPSSAHKSItLKEyNFJGLUxxIY0sYAfoPr1MgSGPSSAHKSItLEEyNDJE5"
    . "xw+NowAAAGYPH0QAAItTPIP6Bw+OnAAAAESNQvgx0kSJxsHuA41OAUjB4QWQxMF+bwQSxMF+fwQRSIPCIEg50XXr995NjRwKTAHJQY0U8IP6A34VxMF6bwtIg8EQSYPDEIPq"
    . "BMX6f0nwhdJ0H0WLA0SJAYP6AXQURYtDBESJQQSD+gJ0B0GLUwiJUQhIY1M4g8cBTY0UkkhjUyBNjQyROfgPhWb////F+HdbXl/DDx+AAAAAAEyJyU2J0+uSQVdBVkFVQVRV"
    . "V1ZTSIHs6AAAAMX4EbQkkAAAAMX4EbwkoAAAAMV4EYQksAAAAMV4EYwkwAAAAMV4EZQk0AAAAMXldtvF8XbJSI1UJF/HRCQsAAAAAEiJyEiD4uBIiVQkOLkBAAAA8A/BCItQ"
    . "LCtQRDnKD4wmBgAASGN4KItYQEyLQCAPr89IY9NIKdeLUExIwecCSGPJTY0MiEmNNDlIiXQkEIXSD4SdAwAATDnOcrGNS/jF+m9wYMX6b2BwicrF+m+QgAAAAEyLdCQ4weoD"
    . "xXpvgJAAAABEjWoB99pEjTzRScHlBUiJ8UiJxg8fRAAASInIxMF6fxZMKcjEQXp/RhDEwX5vLkjB+ALEwXp/diCDwAHEwXp/ZjCD+AcPjjUCAADEwX5vfiDrFmYPH0QAAIPo"
    . "CEmDwSCD+AcPjhcCAADEwX5vAcVV3sjFRd7Qxa10wMU1dM3FtdvAxf12w8X919CF0nTL8w+80oPiPEkB0USLXlBMi1YwTItGOItuVEWF2w+EaAIAAEyJykGJ7EQ53Q+PWQIA"
    . "AIlsJAhMiUwkEEiJTCQYDx9AADHAMe2D+wcPjpsBAAAPHwDF/m8EAsTBfd4sAMTBfd48AsTBVXQsAEiDwCDF/XTHxf3bxcX9dsPF/dfI8w+4ycH5AgHNSTnFdcdNAepNAehM"
    . "AepEifiD+AMPjjoBAADF+m8CxMF53ihJg8IQg+gExMF53nrwSYPAEEiDwhDEwVF0aPDF+XTHxfnbxcX5dsHF+dfI8w+4ycH5AoXAD4SwAAAAxfluOsRBeW4IxMF5birFwd7t"
    . "xbHex8WxdMDF0XTvxfnbxcX5dsHFedfIQYPhAUQByYP4AXRtxfluegTEQXluSATEwXluagTFwd7txbHex8WxdMDF0XTvxfnbxcX5dsHFedfIQYPhAUQByYP4AnQ0xfluQgjE"
    . "wXluaAjEwXluegjFUd7Ixfne/8X5dMfFsXTtxfnbxcX5dsHFedfIQYPhAUQByUjB4AJJAcJJAcBIAcIB6UgB+kEpzEEp23QJRTncD46Z/v//i2wkCEyLTCQQSItMJBhFheQP"
    . "jtUAAABJg8EETDnJD4O9/f//SInw6Sb9//8PH0QAADHJ6fr+//9mDx+EAAAAAACJ2Omm/v//xMF6b34gxMF6by6D+AN+LcTBem8BxVHeyMV53tfFqXTAxEFRdMnFsdvAxfl2"
    . "wcX519CF0nVNSYPBEIPoBIXAdJtJjRSBDx9AAMTBeW4BxVHeyMVB3tDFqXTAxTF0zcWx28DF+XbBxfnXwKgBD4Wm/f//SYPBBEk50XXOSInw6Yf8//9m8w+8wmbB6AIPt8BN"
    . "jQyB6YD9//9BiexFheQPjyv///9BietIifBFKeNEiVwkLEiNUBRBuAEAAABEicGGCoTJdfeLfCQsOXgQD425AgAAiXgQTIlICIYKO3hQD4wm/P//i1AshxDpHPz//w8fAEw5"
    . "TCQQD4L2AQAARItAUESLaFREjVv4SItwMESJ2kU5xUEPnsJFhcBIiXQkGEiLcDgPlcHB6gONagH32kiJdCQgSMHlBUWNPNNBhMoPhNEBAABIiYQkMAEAAGYPH0QAAEyJTCQI"
    . "TItcJCBMicpEicZMi1QkGEWJ7DHARTHJg/sHD46yAQAAZpDF/m8EAsTBfd4UA8TBfd4kAsTBbXQUA0iDwCDF/XTExf3bwsX9dsPF/dfI8w+4ycH5AkEByUg5xXXGSQHqSQHr"
    . "SAHqRIn4g/gDD45ZAQAAxfpvAsTBed4TSYPCEIPoBMTBed5i8EmDwxBIg8IQxMFpdFPwxfl0xMX528LF+XbBxfnXyPMPuMnB+QKFwA+EsAAAAMX5biLEwXluK8TBeW4Sxdne"
    . "0sXZ3sXF+XTFxel01MX528LF+XbBxXnX8EGD5gFEAfGD+AF0bcX5bmIExMF5bmsExMF5blIExdne0sXZ3sXF+XTFxel01MX528LF+XbBxXnX8EGD5gFEAfGD+AJ0NMX5bkII"
    . "xMF5blMIxMF5bmIIxene6MX53uTF+XTExel01cX528LF+XbBxXnX8EGD5gFEAfFIweACSQHDSQHCSAHCRAHJSAH6QSnMKd50CUE59A+OmP7//0yLTCQIRYXkflVJg8EETDlM"
    . "JBAPg2f+//9Ii4QkMAEAAEiDfCQwAA+EDPr//0yLTCQw6ar9//+QSYPBBEw5TCQQct5Fhe1/8EWJ7OsaDx8AMcnp2/7//5CJ2OmP/v//SIuEJDABAABFKeVMiUwkMESJbCQs"
    . "66vF+HfF+BC0JJAAAADF+BC8JKAAAADFeBCEJLAAAADFeBCMJMAAAADFeBCUJNAAAABIgcToAAAAW15fXUFcQV1BXkFfw4YKi3wkLDl4UA+PcPn//+lF/f//Zi4PH4QAAAAA"
    . "AFdWU4tcJEhEichIY/JIY1QkQEWJyA+2xEHB6BBBicKLRCRYD6/GSJhIAdBMjRyBi0QkUA+vxkiYSAHQSI0UgUw52nNsRQ+2wEUPttJFD7bJg/4BdBTraWYPH4QAAAAAAEiD"
    . "wgRMOdpzRw+2SgFEKdGJyPfYD0jBD7ZKAkQpwYnO994PSc45yA9MwQ+2CkQpyYnO994PSc45yA9MwTnDfcAxwFteX8NmLg8fhAAAAAAAuAEAAABbXl/DDx+AAAAAAEjB5gLr"
    . "EmYuDx+EAAAAAABIAfJMOdpz2A+2SgJEKcGJyPfYD0jBD7ZKAUQp0YnP998PSc85yA9MwQ+2CkQpyYnP998PSc85yA9MwTnDfcExwOuPZmYuDx+EAAAAAABmkFZTD69UJDiL"
    . "XCRASGPSSInOSGNMJFBEichFicoPtsRBweoQSAHRTI0cjkhjTCRISAHKSI0Ulkw52nNdRQ+20kQPtsBFD7bJ6xAPH4AAAAAASIPCBEw52nM/D7ZKAkQp0YnI99gPSMEPtkoB"
    . "RCnBic733g9JzjnID0zBD7YKRCnJic733g9JzjnID0zBOcN9wDHAW17DDx8AuAEAAABbXsNEi1QkKE2FwInQD5TCTYXJQQ+Uw0QI2g+FBgEAAEiFyQ+E/QAAAEUPttJBadIA"
    . "AQEARAnSgcoAAAD/xflu0sTifVjSg/gHflJEjVj4xf1vyjHARYnaQcHqA0GNUgFIweIFDx+AAAAAAMX+bxwBxeXYwcTBfn8EAMX13MPEwX5/BAFIg8AgSDnCdd5B99pIAdFJ"
    . "AdFJAdBDjQTTxflvwoP4A34nxfpvIUmDwRBIg8EQSYPAEIPoBMXZ2MrEwXp/SPDF6dzMxMF6f0nwhcB0YsX5bgnF8djQxfncycTBeX4QxMF5fgmD+AF0R8X5bkkExfHY0MX5"
    . "3MnEwXl+UATEwXl+SQSD+AJ0KcX5blEIxenYyMX53MLEwXl+SAjEwXl+QQjF+HcxwMNmLg8fhAAAAAAAxfh3McDDZi4PH4QAAAAAAEFXQVZBVUFUVVdWU0iB7MgAAADF+BF0"
    . "JEDF+BF8JFDFeBFEJGDFeBFMJHDFeBGUJIAAAADFeBGcJJAAAADFeBGkJKAAAADFeBGsJLAAAACLnCRAAQAARIucJEgBAABMiYwkKAEAAEiJyEiDvCQoAQAAAEhjykEPlMJE"
    . "i4wkOAEAAESJwkiDvCQwAQAAAEAPlMZBCPIPhdYCAABIhcAPhM0CAABFichFD77TKdpED6/Di5wkUAEAAEUPr9BNY+JEidZNaeQfhetRwf4fScH8JUEp9IXbD4USAwAAQYD7"
    . "ZA+ECAMAAIXSD4iEAgAATWPZSYnORIlUJDjF5XbbTSnexel20knB5gJFhcAPlcNFOeBKjSwwQQ+dw0Qh20WNWfhBid1IjRyNAAAAAESJ2cHpA0WJ6kWJxUyLhCQwAQAAjXEB"
    . "99lFjTzLidFIweYFSInaRTHbictIicFIOcUPgvoBAABFhNIPhGUCAABEiFQkGESJbCQMRIlkJAhEiVwkIEiJRCQoSIlUJDBIiWwkEIlcJDyLbCQMi3wkCEiJykyJw0yLnCQo"
    . "AQAAZi4PH4QAAAAAADHARTHkQYP5Bw+OkQUAAJDF/m8EAsX93gwDxMF93iQDxfV0DANIg8Agxf10xMX928HF/XbDxX3X0PNFD7jSQcH6AkUB1Eg5xnXGSQHzSAHzSAHyRIn4"
    . "g/gDD44xBQAAxfpvAsX53guD6ARJg8MQxMF53mPwSIPDEEiDwhDF8XRL8MX5dMTF+dvBxfl2wsV519DzRQ+40kHB+gKFwA+EswAAAMX5biLF+W4rxMF5bgvF2d7JxdnexcX5"
    . "dMXF8XTMxfnbwcX5dsLFedfoQYPlAUUB6oP4AXRxxfluYgTF+W5rBMTBeW5LBMXZ3snF2d7Fxfl0xcXxdMzF+dvBxel2wMV51+hBg+UBRQHqg/gCdDnF+W5CCMX5bksIxMF5"
    . "bmMIxfHe6MX53uTF+XTExfF0zcX528HF6XbAxXnX6EGD5QFFAepmDx9EAABIweACSQHDSAHDSAHCRQHiTAHyRCnXRCnNdAg57w+Olf7//4X/D47gBAAASIPBBEg5TCQQD4Ne"
    . "/v//RA+2VCQYRItsJAxEi2QkCESLXCQgSItEJChIi1QkMEiLbCQQi1wkPEGDwwFIAdBIAdVBOdsPjuf9///F+HcxycX4EHQkQMX4EHwkUEiJyMV4EEQkYMV4EEwkcMV4EJQk"
    . "gAAAAMV4EJwkkAAAAMV4EKQkoAAAAMV4EKwksAAAAEiBxMgAAABbXl9dQVxBXUFeQV/DSIPBBEg5zXKMg3wkOGN/8EiDvCRYAQAAAESJ5w+FMAQAAMX4d+uGSIu0JCgBAABE"
    . "D7ZWAkQPtl4BQcHiEEHB4whFCdpED7YeSIu0JDABAABFCdpED7ZeAcRBeW7SRA+2VgJBweMIxEJ9WNJBweIQRQnaRA+2HkUJ2kGBygAAAP/EQXluysRCfVjJhdIPiBb///9N"
    . "Y9HFeX/WxXl/zEmJzcRBeW/Cxel20sXldttNKdVJweUCRYXAQQ+Vw0U54EqNLChBD53CRYnfRY1Z+EUh10yNFI0AAAAARInZwekDjXkB99lFjTTLSMHnBUUx28X5b/zFfX/V"
    . "xX1/yUiJwUg5xQ+CWAIAAESJXCQ4SIlEJBhMiVQkIIlUJChmkEiJ6EgpyEjB+AKDwAGD+Ad/HumBAgAAZg8fhAAAAAAAg+gISIPBIIP4Bw+OaAIAAMX+bwHFdd7YxVXe4MWd"
    . "dMDFJXTZxaXbwMX9dsPF/dfQhdJ0zPMPvNKD4jxIAdFEieZFhP8PhLEBAABEiUQkCEiJykSJw0yLnCQwAQAARIlkJAxMi5QkKAEAAESIfCQQkDHARTH/QYP5Bw+O8QEAAJDF"
    . "/m8EAsRBfd4cA8RBfd4kAsRBJXQcA0iDwCDFnXTAxaXbwMX9dsPFfdfA80UPuMBBwfgCRQHHSDn4dcRJAfpJAftIAfpEifCD+AMPjo8BAADF+m8CxEF53huD6ARJg8IQxEF5"
    . "3mLwSYPDEEiDwhDEQSF0W/DFmXTAxaHbwMX5dsLFedfA80UPuMBBwfgChcAPhL8AAADFeW4ixEF5bivEQXluGsRBGd7bxMEZ3sXFkXTAxEEhdNzFodvAxfl2wsV51+BBg+QB"
    . "RQHgg/gBdHnFeW5iBMRBeW5rBMRBeW5aBMRBGd7bxMEZ3sXFkXTAxEEhdNzFodvAxel2wMV51+BBg+QBRQHgg/gCdD3F+W5CCMRBeW5bCMRBeW5iCMUh3ujEQXne5MWZdMDE"
    . "QSF03cWh28DF6XbAxXnX4EGD5AFFAeAPH4AAAAAASMHgAkkBwkkBw0gBwkUB+EwB6kQpxkQpy3QIOd4PjoX+//9Ei0QkCESLZCQMRA+2fCQQhfYPjioBAABIg8EESDnND4PQ"
    . "/f//RItcJDhIi0QkGEyLVCQgi1QkKEGDwwFMAdBMAdVBOdMPjn39///F+HfpMvz//2aQRTHS6QL7//8PH4QAAAAAAESJyOmu+v//Dx+EAAAAAABFMcDppv7//w8fhAAAAAAA"
    . "RInI6VD+//+D+AN+LMX6bwHFWd7YxXne5sWZdMDEQVl028Wh28DF+XbCxfnX0IXSdUxIg8EQg+gEhcAPhF////9IjRSBDx8AxfluAcVB3tjFOd7gxZl0wMUhdN/FodvAxfl2"
    . "wsX518CoAQ+FXv3//0iDwQRIOdF1z+ki////ZvMPvMJmwegCD7fASI0Mgek7/f//SIO8JFgBAAAARItkJAgPhND7//9Ii4QkWAEAAEEp/ESJIMX4d+lF+///SIO8JFgBAAAA"
    . "D4Sr+///SIuEJFgBAABBKfREiSDF+HfpIPv//2ZmLg8fhAAAAAAADx8AQVZBVUFUVVdWU0iB7NAAAABIi6wkMAEAAEyLnCQ4AQAARIukJEABAABEi7QkSAEAAEiLtCRgAQAA"
    . "SI1cJD9JicpJidWLlCRQAQAASIPj4EiF7Q+UwE2F2w+UwQjID4UFAQAATYXtD4T8AAAAMcC5DAAAAEiJ3/NIq4uEJFgBAABEiWNAiFNIhcBMiVMYD5XAgPpkD77SRIlDKA+U"
    . "wUUPr+ZEiUssSYnYCchMiVs4TInRD7bATIlrIEEPr9SJQ0xIiWswRIlzREhjwsH6H0SJY1BIacAfhetRSMH4JSnQD7ZVAYlDVA+2RQLB4gjB4BAJ0A+2VQAJ0EEPtlMBxflu"
    . "wEEPtkMCweIIxOJ9WMDB4BDF/n9DYAnQQQ+2EwnQSI0VfOz//w0AAAD/xfluwMTifVjAxf5/g4AAAADF+HdB/5LQAAAASIX2dAWLQxCJBkiLQwhIgcTQAAAAW15fXUFcQV1B"
    . "XsMPH0AAMcDr5g8fQABBVkFUVVdWU0yLVCRYi1wkeIu0JIAAAABIhckPhCcBAABNhdIPhB4BAACLRCRoRTHbRAnAC0QkYAnQD4j5AAAAhdsPjgABAACF9g+O+AAAAEUPr8FI"
    . "Y9JNY8lIY3wkcEqNLI0AAAAARI1L+EjB5wJJY8BIAdBIY1QkYEiNDIGLRCRoD69EJHBImEgB0EmNFIJEicjB6ANEjUAB99hFjSTBScHgBUUxyWYPH4QAAAAAADHAg/sHD46l"
    . "AAAADx9EAADF/m8EAsX+fwQBSIPAIEk5wHXtTo0UAkqNBAFFieNBg/wDfhbEwXpvCkiDwBBJg8IQQYPrBMX6f0jwRYXbdCJFizJEiTBBg/sBdBZFi3IERIlwBEGD+wJ0CEWL"
    . "UghEiVAIQYPBAUgB6UgB+kQ5zn+AQbsBAAAAxfh3RInYW15fXUFcQV7DDx8ARTHbRInYW15fXUFcQV7DZg8fhAAAAAAAQYnbSInISYnSg/sDD49y////64tmZi4PH4QAAAAA"
    . "AJBIg+x4TIucJKgAAABIichIhdIPhNgAAABNhdsPhM8AAACLjCS4AAAARTHSRAnJC4wksAAAAEQJwQ+IpAAAAESLlCTIAAAARYXSD46hAAAAi4wk0AAAAIXJD46SAAAASIlU"
    . "JDCLlCSgAAAASInBxflulCTAAAAARIlEJDhMjUQkIMTjaSKMJMgAAAABiVQkQMX5bpwksAAAAIuUJNAAAABIiUQkKMTjYSKEJLgAAAABx0QkIAAAAACJVCRgSI0Vzuj//8X5"
    . "bMFEiUwkPEyJXCRIxfp/RCRQ/5DQAAAAQboBAAAARInQSIPEeMNmDx9EAABFMdJEidBIg8R4ww8fRAAAuAMAAADDkJCQkJCQkJCQkA=="
    mcode_imgutil_column_uniform := 0x000820 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x000940 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_make_sat_masks := 0x0009e0 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000b20 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x001380 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x0014f0 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x001670 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x001770 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform  
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                )
    } 

    ;############################################################################################################
    ; -march=x86-64-v4 optimized AVX512 machine code blob
    ;############################################################################################################
    i_get_mcode_map_v4() {
        static b64 := ""
    . "" ; imgutil_all.c
    . "" ; 5296 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -march=x86-64-v4 -D MARCH_x86_64_v4 -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "VVdWU0SLQUBIi0EIRIuQyAAAAEEPr9BBidGJ0DHSQffyMdKJw0ONBAhMY0EwQffyi1E0AdoPr1E4SGPSTAHCTItBKE2NDJCLURxMY0EYAdoPr1EgSGPSTAHCTItBEE2NFJA5"
    . "ww+NgwAAAL4BAAAAkItRPIP6Dw+OnwAAAESNWvAx0kSJ38HvBESNRwFJweAGYtH+SG8MEWLR/kh/DBJIg8JASTnQdenB5wREidpLjSwBTQHQKfqF0nQ+xOJp99aNev+DwwHF"
    . "+JLPYvF+yW9FAGLRfkl/AEhjUThNjQyRSGNRIE2NFJI5w3WGxfh3W15fXcNmDx9EAABIY1E4g8MBTY0MkUhjUSBNjRSSOdh024tRPIP6Dw+PYf///02J0EyJzeuTZmYuDx+E"
    . "AAAAAABmkEFXQVZBVUFUVVdWU0iD7EhFMcli831IJcD/Qb8BAAAASYnNuAEAAADwQQ/BRQBBi1VMQStVZDnCD4wcBgAAQYt9SEmLVUBJY01gD6/HiXwkPEiYTI0cgkhjx0iJ"
    . "ykgpyEGLTWxJjQSDSIlEJBCFyQ+EdQMAAEw52HKpRI1i8CnXSIlcJChi0f5Ib20CRIngRIlMJDBIY+9i0f5Ib2UDwegEQYPkD0jB5QKJRCQ4Dx8ASItEJBBMKdhIwfgCg8AB"
    . "g/gPD462AgAAYvH9SG/dYvH9SG/U6xpmLg8fhAAAAAAAg+gQSYPDQIP4Dw+OjgIAAGLRf0hvC2LzdUg+ywVi83VJPsoCYvJ+SCjJYvN1SB/AAMX4mMB0ycX4k8Bm8w+8wA+3"
    . "wEmNNINBi0V0RYtNcE2LVVBJi11YiUQkHEGJw0WFyQ+EEAIAAEQ5yA+PBwIAAItEJDhIifFIifdEjXABTIl0JAiD+g8PjnQCAABIi3QkCEUxwDHASMHmBmYPH0QAAGKxf0hv"
    . "FAFik21IPgwCBWKzbUk+DAMCSYPAQGLyfkgoyWLzdUgf+ADFeJP380UPuPZEAfBJOfB1x00BwkwBw0wBwU1jxEWFwA+FGgEAAESLdCQ8QSnDRInISIn+KdBBKdZNY/ZJweYC"
    . "TAHxRDnYD4xjAQAAhcAPhFsBAACLfCQ4SIl0JAhIiWwkIESNTwFJweEGZg8fRAAAg/oPD45fBAAAMfZFMcBmLg8fhAAAAAAAYvF/SG8UMWLTbUg+DDIFYvNtST4MMwJIg8ZA"
    . "YvJ+SCjJYvN1SB/4AMX4k//zD7j/QQH4TDnOdchNAcpMActMAclFKcMp0EwB8UQ52HwEhcB1lkiLdCQISItsJCBFhdsPj8sAAACLfCQcSItcJChIifFEKd9BiflJjUUUQbgB"
    . "AAAARInChhCE0nX3RTlNEA+NqgMAAEWJTRBJiU0IhhBFO01wD4xL/f//QYtFTEGHRQDpPv3//w8fAMTCOff3g+4BScHgAsX7ks5i8X7Jbwli0X7JbxpNAcJi8X7JbxNMAcNJ"
    . "Aehi83VIPtMFTAHBYvN1Sj7SAmLyfkgoymLzdUgfwADF/EHhxfiT9GbzD7j2D7f2AcZBKfNBKdF0CUU5yw+OD/7//0iJ/kWF2w+ONf///0yNXgRMOVwkEA+DQf3//0iLXCQo"
    . "RItMJDDppfz//4XAdO3Ewnn3x4PoAcX4kshi0X7Jbwti83VIPtUFYvN1Sj7EAmLyfkgoyGLzdUkfyADF+JjJdLrF+JPBZvMPvMAPt8BJjTSDSIX2D4VZ/f//SItcJChEi0wk"
    . "MOlG/P//Dx8ATGPCMcDp2/3//0w5XCQQD4KjAQAASYtFUIn9jUrwQYt9dEWLdXAp1UiJXCQwxMH5buVIiUQkIEmLRVhIY+1EiUwkPEjB5QJFifVIiUQkKInIg+EPwegEiXwk"
    . "OIlEJByJyEyJ2UGJw2YPH4QAAAAAAIt8JDhIi1wkIESJ6EiLdCQoQYn6RYXtD4QEAQAARDnvD4/7AAAAi3wkHEmJyUSNdwFMiXQkCIP6Dw+OoQEAAJBMi3QkCDH/RTHAScHm"
    . "BmaQYtF/SG8sOWLzVUg+DDsFYvNVST4MPgJIg8dAYvJ+SCjJYvN1SB/oAMV4k+XzRQ+45EUB4Ew593XHSAH7SQH5SAH+SWP7hf8PhcMAAABFKcIp0EQ50Hx6hcB0dot8JBxJ"
    . "AelEjWcBScHkBmYPH0QAAIP6Dw+OIgEAADH/RTHAZpBi0X9Ibyw5YvNVSD4MOwVi81VJPgw+AkiDx0Bi8n5IKMli83VIH/AAxXiT9vNFD7j2RQHwTDnndcdMAeNNAeFMAeZF"
    . "KcJJAekp0HQFQTnCfp9FhdIPjskAAABIg8EESDlMJBAPg8f+//9Ii1wkMESLTCQ8xMH5fuVIhdsPhIL6//9Iidnp/vz//w8fgAAAAADEQkH350WNdCT/SMHnAinQxMF7ks5i"
    . "0X7Jbwli8X7JbxtIAfti8X7JbxZIAf5IAe9i83VIPtMFSQH5YvN1Sj7SAmLyfkgoymLzdUgfwADF/EHZxXiT42bzRQ+45EUPt+RFAcRFKeJEOdAPjFL///+FwA+ESv///4P6"
    . "Dw+PYP7//0hj+kUxwOmq/v//RTHA6R////+LfCQ4xMH5fuVIictEKddBifnpPv///8X4d0iDxEhbXl9dQVxBXUFeQV/DhhBFOU1wD4+p+f//6Vn8//+QRTHA6en7//8PH4QA"
    . "AAAAAFdWU0SLVCRITGPCi1QkWESJyEWJy0xjTCRAD7bcQcHrEEEPr9BIY9JMAcpIjTSRi1QkUEEPr9BIY9JMAcpIjRSRSDnyc2pFD7bbD7bbRA+2yEGD+AF0EutnDx+AAAAA"
    . "AEiDwgRIOfJzRw+2SgEp2YnI99gPSMEPtkoCRCnZQYnIQffYQQ9JyDnID0zBD7YKRCnJQYnIQffYQQ9JyDnID0zBQTnCfboxwFteX8MPH0AAuAEAAABbXl/DDx+AAAAAAEnB"
    . "4ALrEmYuDx+EAAAAAABMAcJIOfJz2A+2SgJEKdmJyPfYD0jBD7ZKASnZic/33w9JzznID0zBD7YKRCnJic/33w9JzznID0zBQTnCfcExwOuVZmYuDx+EAAAAAABmkFZTD69U"
    . "JDhMY0QkUESLVCRASGPSSQHQRInIRInLSo00gUxjRCRID7bEwesQTAHCSI0UkUg58nNgD7bbRA+22EUPtsnrDA8fAEiDwgRIOfJzRw+2SgIp2YnI99gPSMEPtkoBRCnZQYnI"
    . "QffYQQ9JyDnID0zBD7YKRCnJQYnIQffYQQ9JyDnID0zBQTnCfboxwFteww8fRAAAuAEAAABbXsNEi1QkKE2FwInQD5TCTYXJQQ+Uw0QI2g+FtgAAAEiFyQ+ErQAAAEUPttJB"
    . "adIAAQEARAnSgcoAAAD/YvJ9SHzSg/gPflhEjVjwYvH9SG/KMcBFidpBweoEQY1SAUjB4gZi8X9IbxwBYvFlSNjBYtH+SH8EAGLxdUjcw2LR/kh/BAFIg8BASDnQddZIAcFJ"
    . "AcFJAcBBweIERInYRCnQhcB0P7oBAAAAxOJ598KD6AHF+JLIYvF+yW8BYvF9SNjKYvF9SNzCYtF+SX8IYtF+SX8Bxfh3McDDZi4PH4QAAAAAAMX4dzHAw2YuDx+EAAAAAABB"
    . "V0FWQVVBVFVXVlNIg+w4i7QksAAAAEyLlCTIAAAATImMJJgAAABIichEicNMY9pIg7wkmAAAAACLlCSoAAAAD5TBRIuMJLgAAABIg7wkoAAAAABBD5TARAjBD4WBAQAASIXA"
    . "D4R4AQAAidFFD77BKfMPr85ED6/BiUwkCEljyESJx0hpyR+F61HB/x9IwfklKflBic+LjCTAAAAAhckPhVQBAABBgPlkD4RKAQAAhdsPiCsBAABIY8pNidxEjWrwRIlEJChJ"
    . "KcyLTCQISIlEJBhi83VIJcn/ScHkAolcJCxBvgEAAABEOflMiZQkyAAAAEqNLCBBD53BhckPlcFBIclKjQydAAAAAEUx20iJTCQgRInpwekERIhMJBCNeQHB4QREiVwkDEEp"
    . "zUjB5wZEiWwkBEiLRCQYSYnBSDnFD4J8BAAAgHwkEAB0EullAwAASYPBBEw5zQ+CYwQAAIN8JChjf+xMi5QkyAAAAESJ/k2F0g+FrgQAAMX4d+tnhcB0N8TCeffGg+gBxfiS"
    . "yGLRfslvAWLzfUg+1QVi831KPsQCYvJ+SCjAYvN9SR/BAMX4mMAPha4BAABIi0QkEEyLXCQYRItEJCCLXCQoQYPAAUwB2EwB3UE52A+O+AAAAMX4d0UxyUyJyEiDxDhbXl9d"
    . "QVxBXUFeQV/DSIu0JJgAAABIi4wkmAAAAEQPtkYBD7ZJAkHB4AjB4RBECcFED7YGSIu0JKAAAABECcFED7ZGAWLyfUh86UiLjCSgAAAAQcHgCA+2SQLB4RBECcFED7YGRAnB"
    . "gckAAAD/YvJ9SHzhhdsPiHj///9IY8pNidxEjWrwRIl8JAxJKcyLTCQITImUJMgAAABBvgEAAABJweQCYvN1SCXJ/4XJSo0sIEEPlcBEOfkPncFJweMCQSHIRIhEJCxJicBE"
    . "iejB6ASNeAHB4ARBKcUxwEjB5wZEiWwkBInBTInAQYnISYnBYvH9SG/dYvH9SG/USDnFD4Ld/v//SIlEJBAPtkwkLEyJXCQYRIlEJCCJXCQoZg8fhAAAAAAASInoTCnISMH4"
    . "AoPAAYP4D38e6Vf+//9mDx+EAAAAAACD6BBJg8FAg/gPD44+/v//YtF/SG8BYvN9SD7LBWLzfUk+ygJi8n5IKMFi831IH8EAxfiYwHTJxfiTwGbzD7zAi3QkDA+3wE2NDIGE"
    . "yQ+E8AAAAEiLnCSgAAAATIucJJgAAABNichEi1QkCIt0JAyQMcBFMf+D+g8PjgABAABmkGLRf0hvBABi031IPgwDBWLzfUk+DAMCSIPAQGLyfkgowWLzfUgf8QDFeJPu80UP"
    . "uO1FAe9IOfh1x0hjRCQESQH7SQH4SAH7hcAPhJEAAADEQnn37kGD7QFIweACQSnSxMF7ks1i0X7JbwBiwX7JbwNJAcNi4X7JbwtIAcNMAeBis31IPtAFSQHAYrN9Sj7RAmLy"
    . "fkgowmLzfUgfwQDF/EHpxXiT7WbzRQ+47UUPt+1FAf1EKe5BOfJ8CUWF0g+FLf///4X2D466AQAASYPBBEw5zQ+DiP7//+ks/f//Dx8ARCn+TQHgQSnSdNhEOdZ/0zHARTH/"
    . "g/oPD48C////SGPC6UH///9IiekPH4AAAAAASIucJKAAAABEi1QkCE2JyESJ/kyLnCSYAAAADx9EAAAxwEUx7YP6Dw+OIAEAAGaQYtF/SG8kAGLTXUg+DAMFYvNdST4MAwJI"
    . "g8BAYvJ+SCjBYvN9SB/ZAMX4k+vzD7jtQQHtSDn4dchIY0QkBEkB+0kB+EgB+4XAD4SyAAAAxMJ59+6D7QFIweACQSnSxfuSzWLRfslvAGLRfslvG0kBw2LxfslvE0gBw0wB"
    . "4GLzfUg+0wVJAcBi831KPtICYvJ+SCjCYvN9SB/BAMX8QeHF+JPsZvMPuO0Pt+1EAe0p7kQ51n8JRYXSD4Uz////hfZ+ZUmDwQRMOckPgwL///9Iic1Ii3QkIINEJAwBi0wk"
    . "LItEJAxIAXQkGEgB9TnID45R+///xfh36ff7//8PH0QAAEQp7k0B4EEp0nSyRDnWf60xwEUx7YP6Dw+P4v7//0hjwukg////TIuUJMgAAABNhdIPhFL7//9BKfdFiTrF+Hfp"
    . "sPv//0yLlCTIAAAARIt8JAxNhdIPhC77//9Eifgp8EGJAsX4d+mK+///Dx9EAABBVUFUVVdWU0iB7FgBAABMi5wksAEAAEyLlCS4AQAAi7wkwAEAAESLpCTIAQAAi4Qk0AEA"
    . "AEiLtCTgAQAASI1cJF9Ig+PATYXbQA+UxU2F0kEPlMVECO0PhQMBAABIhdIPhPoAAADF+e/AYvF/SH9DAUiJU0CLlCTYAQAARIlDSIXSiXtgD5XCPGSIQ2gPvsBBD5TAQQ+v"
    . "/GLxf0h/A0QJwkiJSxhJidgPttJEiUtMD6/HiVNsTIlbUEyJU1hIY9DB+B9EiWNkSGnSH4XrUYl7cEjB+iUpwkEPtkMCiVN0QQ+2UwHB4BDB4ggJ0EEPthMJ0EEPtlIBYvJ9"
    . "SHzAQQ+2QgJi8X5If0MCweIIweAQCdBBD7YSCdBIjRVC7///DQAAAP9i8n1IfMBi8X5If0MDxfh3/5HQAAAASIX2dAWLQxCJBkiLQwhIgcRYAQAAW15fXUFcQV3DZg8fhAAA"
    . "AAAAMcBIgcRYAQAAW15fXUFcQV3DZmYuDx+EAAAAAAAPHwBBVUFUVVdWU0iLXCRYRItUJHhEi5wkgAAAAEiFyQ+EBQEAAEiF2w+E/AAAAItEJGgx9kQJwAtEJGAJ0A+IsQAA"
    . "AEWF0g+O3gAAAEWF2w+O1QAAAEUPr8FIY9JBjXLwTWPJSo0sjQAAAABBvAEAAABFMclJY8BIAdBIY1QkYEiNDIGLRCRoD69EJHBImEgB0EiNFIOJ8EhjXCRwwegERI1AAcHg"
    . "BEjB4wJJweAGKcZmkDHAQYP6Dw+OfAAAAA8fQABi8f5IbwwCYvH+SH8MAUiDwEBJOcB16YX2dSVBg8EBSAHpSAHaRTnLf8a+AQAAAMX4d4nwW15fXUFcQV3DDx8ATo0sAkqN"
    . "PAGJ8MTCeffEg+gBxfiSyGLRfslvRQBi8X5Jfwfrtg8fADH2ifBbXl9dQVxBXcMPHwBEidBIic9JidXrx2ZmLg8fhAAAAAAAZpBIg+x4TIucJKgAAABIhdIPhNMAAABNhdsP"
    . "hMoAAACLhCS4AAAARTHSRAnIC4QksAAAAEQJwA+IoQAAAESLlCTIAAAARYXSD46cAAAAi4Qk0AAAAIXAD46NAAAAi4QkoAAAAEiJVCQwSI0V8uv//8X5bpQkwAAAAESJRCQ4"
    . "TI1EJCDE42kijCTIAAAAAYlEJEDF+W6cJLAAAACLhCTQAAAASIlMJCjE42EihCS4AAAAAcdEJCAAAAAARIlMJDzF+WzBTIlcJEiJRCRgxfp/RCRQ/5HQAAAAQboBAAAARInQ"
    . "SIPEeMMPH0AARTHSRInQSIPEeMNmZi4PH4QAAAAAAGaQuAQAAADDkJCQkJCQkJCQkA=="
    mcode_imgutil_column_uniform := 0x0007c0 ; u32 imgutil_column_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 x, i32 tolerance, i32 ymin, i32 ymax)
    mcode_imgutil_row_uniform    := 0x0008e0 ; i32 imgutil_row_uniform(argb *ptr, i32 width, i32 height, argb refc, i32 y, i32 tolerance, i32 xmin, i32 xmax)
    mcode_imgutil_make_sat_masks := 0x000980 ; u32 imgutil_make_sat_masks(u32 *__restrict needle, i32 pixelcount, u32 *__restrict needle_lo, u32 *__restrict needle_hi, u8 t)
    mcode_imgutil_imgsrch        := 0x000a70 ; argb *imgutil_imgsrch(argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_imgsrch_multi  := 0x0010d0 ; argb *imgutil_imgsrch_multi(mt_ctx *ctx, argb *haystack, i32 haystack_w, i32 haystack_h, argb *needle_lo, argb *needle_hi, i32 needle_w, i32 needle_h, i8 pctmatchreq, i32 force_topleft, i32 *ppixels_matched)
    mcode_imgutil_blit           := 0x001250 ; i32 imgutil_blit(argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_imgutil_blit_multi     := 0x0013a0 ; i32 imgutil_blit_multi(mt_ctx *ctx, argb *dst, i32 dx, i32 dy, i32 dstride, argb *src, i32 sx, i32 sy, i32 sstride, i32 w, i32 h)
    mcode_get_blob_psabi_level   := 0x0014a0 ; u32 get_blob_psabi_level()
    ;----------------- end of ahkmcodegen auto-generated section ------------------
                                                
        static code := this.i_b64decode(b64)
        return Map(   "imgutil_column_uniform",    code + mcode_imgutil_column_uniform
                    , "imgutil_row_uniform",       code + mcode_imgutil_row_uniform
                    , "imgutil_make_sat_masks",    code + mcode_imgutil_make_sat_masks
                    , "imgutil_imgsrch",           code + mcode_imgutil_imgsrch
                    , "imgutil_imgsrch_multi",     code + mcode_imgutil_imgsrch_multi
                    , "imgutil_blit",              code + mcode_imgutil_blit
                    , "imgutil_blit_multi",        code + mcode_imgutil_blit_multi
                    , "get_blob_psabi_level",      code + mcode_get_blob_psabi_level
                    )
    }

    ;############################################################################################################
    ; base code, independent of optimization level/architecture
    ;############################################################################################################
    i_get_mcode_map_base() {
        ; this can't be part of the main blob as we don't want GCC to taint it with
        ; vectorization or the use of other instructions that may not be available
        ; on older CPUs
        static b64 := ""
    . "" ; imgutil_lib.c
    . "" ; 2880 bytes
    . "" ; gcc.exe (Rev2, Built by MSYS2 project) 13.2.0
    . "" ; flags: -mabi=ms -m64 -D __HEADLESS__ -O3
    . "" ; GNU assembler (GNU Binutils) 2.41
    . "" ; flags: -O2
    . "VVdWU0iD7Di/AQAAAEiJy/APwbnMAAAASIuRkAAAAEhjx0iNdCQg8w9+BMJIjSzFAAAAAA8WgZgAAAAPEUQkIOsjZg8fRAAASIuLwAAAAIn6/5O4AAAASIuDoAAAAEiLDCj/"
    . "U3BFMcBBuf////9IifK5AgAAAP+TiAAAAIXAdMgxwEiDxDhbXl9dww8fRAAAVlNIg+woMcBIictIhcl1EEiDxChbXsNmDx+EAAAAAABIh5G4AAAATIeBwAAAAIuJyAAAAIXJ"
    . "dCQx9mYPH0QAAEiLg5AAAABIiwzwSIPGAf9TcIuLyAAAADnOcuRIi5OgAAAAQbn/////QbgBAAAA/5OIAAAAuAEAAABIg8QoW17DZmYuDx+EAAAAAAAPH0AAVVdWU0iD7BhF"
    . "McBFMdtFMclEicBEicEPokSJwUyNBR0IAACJxrgAAACASY2o0AEAAA+iicdBi1AMQYsAQTnTRA9C2j0AAACAdj45x3JCRInJRYtQCA+iiQQkSWNABIlcJASJTCQIiVQkDEQj"
    . "FIR0IEmDwBBJOeh1vESJ2EiDxBhbXl9dww8fADnGc8KFwHi+QYPrAUSJ2EiDxBhbXl9dw2VIiwQlYAAAAEiLQBhIi0AgSIsASIsASItAIMNHZXRQcm9jQWRkcmVzcwAPH0QA"
    . "AFZTSYnLTInZi0E8SAHISI1AGEiNQHBIi8CLEEiNBBGLWBiLUCCF23RTRTHSSY00E0KLFJZBuEcAAABMjQ2r////TAHaD7YKhMl1HusmDx8ARDjBdR4PtkoBSIPCAUmDwQFF"
    . "D7YBhMl0BUWEwHXiRDjBdA5Jg8IBSTnadbQxwFtew4tQJEuNDFOLQBwPtxQRSY0Uk4sEAkwB2Fteww8fQABWU0iD7ChIictIhckPhLYAAABIi4mYAAAA/1NwSIuTqAAAAIuL"
    . "yAAAAEG5/////0G4AQAAAP+TiAAAAEiLi5gAAAD/k4AAAACLg8gAAACFwHRFMfYPH0AASIuDqAAAAEiLDPD/k4AAAABIi4OgAAAASIsM8P+TgAAAAEiLg5AAAABIiwzwSIPG"
    . "Af+TgAAAADuzyAAAAHLBSIuLoAAAAP9TKEiLi5AAAAD/UyhIi4uoAAAA/1MoSItDKEiJ2UiDxChbXkj/4A8fAEiDxChbXsOQVVdWU0iD7EhIi0FQx0QkOAAAAABIic5IhcAP"
    . "hAABAABIjXwkPEUxyTHSMclJifjHRCQ8AAAAAEjHRCQgAAAAAP/Qi1QkPLlAAAAA/1YgSInDSIXAD4S2AAAARTHJi1QkPEmJ+EiJwUjHRCQgAAAAAP9WUIXAD4SVAAAARItE"
    . "JDxFhcAPhC8BAABIidoxyUG6/////0Ux2zHtRTHJ6x5mkIPFAUGJwmYuDx+EAAAAAACLAgHBSAHCRDnBczSLQgSFwHXtD7ZCD0Q50HTkQYPBAYB6EgB0ykGJwosCQYPDAQHB"
    . "SAHCRDnBctMPH4AAAAAARInPKe9FhdtBD0T5SInZ/1YoifhIg8RIW15fXcMPHwAx/4n4SIPESFteX13DDx8AMdtIjXwkOOsuDx+AAAAAAP9WMIP4enXYSIXbdAZIidn/ViiL"
    . "VCQ4uUAAAAD/ViBIicNIhcB0uUiJ+kiJ2f9WSIXAdMyLRCQ4g/gfdkuNSOAx/0iJ2EGJyEHB6AVBjVABSMHiBUgB2mYPH4QAAAAAAIN4CAGD1wBIg8AgSDnCdfBBweAFichE"
    . "KcCJRCQ46Ur///9mDx9EAAAx/+k9////R2xvYmFsRnJlZQBHbG9iYWxBbGxvYwBMb2FkTGlicmFyeUEARnJlZUxpYnJhcnkAkEdldExvZ2ljYWxQcm9jZXNzb3JJbmZvcm1h"
    . "dGlvbgBHZXRTeXN0ZW1DcHVTZXRJbmZvcm1hdGlvbgBHZXRMYXN0RXJyb3IAUXVlcnlQZXJmb3JtYW5jZUNvdW50ZXIAUXVlcnlQZXJmb3JtYW5jZUZyZXF1ZW5jeQBDcmVh"
    . "dGVUaHJlYWQAV2FpdEZvclNpbmdsZU9iamVjdABDcmVhdGVFdmVudEEAU2V0RXZlbnQAUmVzZXRFdmVudABDbG9zZUhhbmRsZQBXYWl0Rm9yTXVsdGlwbGVPYmplY3RzAGaQ"
    . "QVVBVFVXVlNIg+w4ZUiLBCVgAAAASItAGEiLQCBIiwBIiwBIi0AgSInGic1IhcAPhOUCAABIicHog/v//0iNFav+//9IifFIicf/0EiNFaf+//9IifFJicX/17rYAAAAuUAA"
    . "AABJicT/0EiJw0iFwA+EpAIAAEiNBeP5//9IjRWC/v//SInxSIkzSImD0AAAAEyJYyBIiXsITIlrKP/XSI0Vbf7//0iJ8UiJQxD/10iNFWr+//9IifFIiUMY/9dIjRV5/v//"
    . "SInxSIlDSP/XSI0VhP7//0iJ8UiJQ1D/10iNFYH+//9IifFIiUMw/9dIjRWJ/v//SInxSIlDOP/XSI0Vk/7//0iJ8UiJQ0D/10iNFZD+//9IifFIiUNY/9dIjRWU/v//SInx"
    . "SIlDYP/XSI0Vkf7//0iJ8UiJQ2j/10iNFYr+//9IifFIiUNw/9dIjRWF/v//SInxSIlDeP/XSI0Vgf7//0iJ8UiJg4AAAAD/10iJg4gAAACF7Q+EVwEAAI0U7QAAAAC5QAAA"
    . "AImryAAAAEH/1LlAAAAASImDqAAAAIuDyAAAAI0UxQAAAABB/9S5QAAAAEiJg5AAAACLg8gAAACNFMUAAAAAQf/UMclFMclFMcBIiYOgAAAAugEAAAD/U2hIg7uoAAAAAEjH"
    . "g7gAAAAAAAAASImDmAAAAEiLi5AAAABIx4PAAAAAAAAAAMeDzAAAAAAAAAAPhM8AAABIhckPhMYAAABIi4OgAAAASIXAD4S2AAAAi5PIAAAAhdJ0fTHtTI0lg/f//+sIkEiL"
    . "g6AAAABIjTTtAAAAAEUxyUUxwDHSSI08MDHJSIPFAf9TaEUxyUUxwDHSSIkHSIu7kAAAADHJ/1NoSYnZTYngMdJIAfcxyUiJB0gDs6gAAABIx0QkKAAAAADHRCQgAAAAAP9T"
    . "WEiJBjuryAAAAHKPSInYSIPEOFteX11BXEFdww8fgAAAAABIidnoUPr//4nF6Zr+//9mDx+EAAAAAAD/k4AAAABIi4ugAAAA/1MoSIuLqAAAAP9TKEiLi7AAAAD/UyhIidlB"
    . "/9Ux20iJ2EiDxDhbXl9dQVxBXcMPH0AAAQAAAAMAAAABAAAAAQAAAAEAAAADAAAAAAEAAAEAAAABAAAAAwAAAAAIAAABAAAAAQAAAAMAAAAAgAAAAQAAAAEAAAADAAAAAAAA"
    . "AQEAAAABAAAAAwAAAAAAgAABAAAAAQAAAAMAAAAAAAABAQAAAAEAAAADAAAAAAAAAgEAAAABAAAAAwAAAAAAAAQBAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAACAAAAIA"
    . "AAABAAAAAgAAAAAACAACAAAAAQAAAAIAAAAAABAAAgAAAAEAAAACAAAAAACAAAIAAAABAACAAgAAAAEAAAACAAAAAQAAAAIAAAAAEAAAAwAAAAEAAAACAAAAAABAAAMAAAAB"
    . "AAAAAgAAAAAAAAgDAAAAAQAAAAIAAAAAAAAQAwAAAAEAAAACAAAAAAAAIAMAAAABAACAAgAAACAAAAADAAAABwAAAAEAAAAIAAAAAwAAAAcAAAABAAAAIAAAAAMAAAAHAAAA"
    . "AQAAAAABAAADAAAABwAAAAEAAAAAAAEABAAAAAcAAAABAAAAAAACAAQAAAAHAAAAAQAAAAAAABAEAAAABwAAAAEAAAAAAABABAAAAAcAAAABAAAAAAAAgAQAAACQkJCQkJCQ"
    . "kJCQkJCQkJCQ"
    mcode_mt_threadproc         := 0x000000 ; 
    mcode_mt_run                := 0x000090 ; 
    mcode_get_cpu_psabi_level   := 0x000120 ; int get_cpu_psabi_level()
    mcode_gpa_getkernel32       := 0x0001c0 ; 
    mcode_gpa_getgetprocaddress := 0x0001f0 ; 
    mcode_mt_deinit             := 0x000290 ; 
    mcode_mt_get_cputhreads     := 0x000360 ; int mt_get_cputhreads(mt_ctx *ctx)
    mcode_mt_init               := 0x000630 ; 
    ;----------------- end of ahkmcodegen auto-generated section ------------------
            
        static code := this.i_b64decode(b64)
        codemap := Map( "get_cpu_psabi_level",       code + mcode_get_cpu_psabi_level
                      , "mt_get_cputhreads",         code + mcode_mt_get_cputhreads
                      , "mt_init",                   code + mcode_mt_init
                      , "mt_deinit",                 code + mcode_mt_deinit
                      )
        return codemap
    }

































































































